ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 1/full_catalog_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 1/full_catalog_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 1/incremental_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 1/incremental_saerch.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/confirm.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/init.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/on_confirm.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/on_init.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/on_select.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/on_status_delivered.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/on_status_out_for_delivery.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/on_status_packed.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/on_status_pending.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 2/select.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/confirm.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/init.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/on_confirm.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/on_init.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/on_select (remove out of stock item from cart).json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/on_select (with 1 out of stock item).json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/on_status_delivered.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/on_status_out_for_delivery.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/on_status_packed.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/on_status_pending.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/select (remove out of stock item from cart).json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group A/Flow 3/select (with 1 out of stock item).json

ShopEG Retail v1.2.0 Logs

---

Krenai_Retail/Krenai-retail-logs-update/Flow-1/full_on_search.json
Krenai_Retail/Krenai-retail-logs-update/Flow-1/full_search.json
Krenai_Retail/Krenai-retail-logs-update/Flow-1/on_search_incr.json
Krenai_Retail/Krenai-retail-logs-update/Flow-1/search_incr.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/confirm.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/init.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/on_confirm.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/on_init.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/on_select.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/on_status_delivered.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/on_status_pending.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/on_status_picked_up.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/on_track.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/select.json
Krenai_Retail/Krenai-retail-logs-update/Flow-2/track.json
Krenai_Retail/Krenai-retail-logs-update/Flow-4/cancel.json
Krenai_Retail/Krenai-retail-logs-update/Flow-4/on_cancel.json
Krenai_Retail/Krenai-retail-logs-update/Flow-5/on_cancel.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-1 seller part cancelation/on_update.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-2 return with reverse QC/on_update_return_approved.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-2 return with reverse QC/on_update_return_delivered.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-2 return with reverse QC/on_update_return_initiated.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-2 return with reverse QC/on_update_return_picked_up.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-2 return with reverse QC/update.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-3 return with liquidation/on_update_liquidated.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-3 return with liquidation/on_update_return_initiated.json
Krenai_Retail/Krenai-retail-logs-update/Flow-6/Scenario-3 return with liquidation/update.json

We have updated the logs as per feedback and have also added the logs for update flow

updated logs & addition of update flow

---

COSTBO/retail-v120-logs/flow1/Incremental_on_search_response.json
COSTBO/retail-v120-logs/flow1/Incremental_search.json
COSTBO/retail-v120-logs/flow1/fullcatalog_refresh_search.json
COSTBO/retail-v120-logs/flow1/on_search.json
COSTBO/retail-v120-logs/flow2/Init.json
COSTBO/retail-v120-logs/flow2/confirm.json
COSTBO/retail-v120-logs/flow2/on_confirm.json
COSTBO/retail-v120-logs/flow2/on_init.json
COSTBO/retail-v120-logs/flow2/on_select.json
COSTBO/retail-v120-logs/flow2/on_status_delivered.json
COSTBO/retail-v120-logs/flow2/on_status_packed_pending.json
COSTBO/retail-v120-logs/flow2/on_status_picked_inprogress.json
COSTBO/retail-v120-logs/flow2/select.json
COSTBO/retail-v120-logs/flow3/confirm.json
COSTBO/retail-v120-logs/flow3/init.json
COSTBO/retail-v120-logs/flow3/on_confirm.json
COSTBO/retail-v120-logs/flow3/on_init.json
COSTBO/retail-v120-logs/flow3/on_select.json
COSTBO/retail-v120-logs/flow3/on_select_updated.json
COSTBO/retail-v120-logs/flow3/on_status_delivered.json
COSTBO/retail-v120-logs/flow3/on_status_pending_packed.json
COSTBO/retail-v120-logs/flow3/on_status_picked_inprogress.json
COSTBO/retail-v120-logs/flow3/select.json
COSTBO/retail-v120-logs/flow3/select_updated.json

Pull requests submitted for retails logs from COSTBO.  Please review and approve at the earliest.

retail logs v120

---

CSC/IGM preprod.ondc.adya.ai/Flow 1/issue(close).json
CSC/IGM preprod.ondc.adya.ai/Flow 1/issue.json
CSC/IGM preprod.ondc.adya.ai/Flow 1/issue_status.json
CSC/IGM preprod.ondc.adya.ai/Flow 1/on_issue.json
CSC/IGM preprod.ondc.adya.ai/Flow 1/on_issue_status(unsolicited).json
CSC/IGM preprod.ondc.adya.ai/Flow 1/on_issue_status.json
CSC/IGM preprod.ondc.adya.ai/Flow 2/issue(close).json
CSC/IGM preprod.ondc.adya.ai/Flow 2/issue.json
CSC/IGM preprod.ondc.adya.ai/Flow 2/issue_status.json
CSC/IGM preprod.ondc.adya.ai/Flow 2/on_issue.json
CSC/IGM preprod.ondc.adya.ai/Flow 2/on_issue_status(unsolicited).json
CSC/IGM preprod.ondc.adya.ai/Flow 3/issue(close).json
CSC/IGM preprod.ondc.adya.ai/Flow 3/issue.json
CSC/IGM preprod.ondc.adya.ai/Flow 3/issue_status.json
CSC/IGM preprod.ondc.adya.ai/Flow 3/on_issue.json
CSC/IGM preprod.ondc.adya.ai/Flow 3/on_issue_status(unsolicited).json
CSC/IGM preprod.ondc.adya.ai/Flow 3/on_issue_status.json

IGM update

---

wits-adapter/magento/IGM/issue.json
wits-adapter/magento/IGM/issue_status.json
wits-adapter/magento/IGM/on_issue.json
wits-adapter/magento/IGM/on_issue_status(unsolicited).json
wits-adapter/magento/IGM/on_issue_status.json

wits-adapter magento IGM logs

---

Chattybao/Logs_Dec_09/IGM/Flow 1/issue(close).json
Chattybao/Logs_Dec_09/IGM/Flow 1/issue.json
Chattybao/Logs_Dec_09/IGM/Flow 1/issue_status.json
Chattybao/Logs_Dec_09/IGM/Flow 1/on_issue.json
Chattybao/Logs_Dec_09/IGM/Flow 1/on_issue_status(solciited).json
Chattybao/Logs_Dec_09/IGM/Flow 1/on_issue_status(unsolicited).json
Chattybao/Logs_Dec_09/IGM/Flow 2/issue(close).json
Chattybao/Logs_Dec_09/IGM/Flow 2/issue.json
Chattybao/Logs_Dec_09/IGM/Flow 2/issue_status.json
Chattybao/Logs_Dec_09/IGM/Flow 2/on_issue.json
Chattybao/Logs_Dec_09/IGM/Flow 2/on_issue_status(solciited).json
Chattybao/Logs_Dec_09/IGM/Flow 2/on_issue_status(unsolicited).json

Flow 1
// on_issue_status
Refund Amount for /on_issue_status should only be when action type is REFUND
created_at' should match issue's 'created_at
Above feedback issues are fixed and logs updated

Chattybao - fixed feedback on IGM Logs

---

jubilant/Flow2/confirm.json
jubilant/Flow2/init.json
jubilant/Flow2/on_confirm.json
jubilant/Flow2/on_init.json
jubilant/Flow2/on_select.json
jubilant/Flow2/on_status_accepted.json
jubilant/Flow2/on_status_delivered.json
jubilant/Flow2/on_status_in_progress.json
jubilant/Flow2/on_status_order_picked_up.json
jubilant/Flow2/on_status_out_for_delivery.json
jubilant/Flow2/select.json

Corrected timestamp issue between picked up and delivered

Corrected timestamp issue between picked up and delivered

---

jubilant/Flow2/confirm.json
jubilant/Flow2/init.json
jubilant/Flow2/on_confirm.json
jubilant/Flow2/on_init.json
jubilant/Flow2/on_select.json
jubilant/Flow2/on_status_accepted.json
jubilant/Flow2/on_status_delivered.json
jubilant/Flow2/on_status_in_progress.json
jubilant/Flow2/on_status_order_picked_up.json
jubilant/Flow2/on_status_out_for_delivery.json
jubilant/Flow2/select.json

Added logs for customizable item

Added logs for customizable item

---

Adya/Rsp/RSP-LSP/FLOW 1/collector_recon.json
Adya/Rsp/RSP-LSP/FLOW 1/on_collector_recon.json
Adya/Rsp/RSP-LSP/FLOW 1/on_receiver_recon.json
Adya/Rsp/RSP-LSP/FLOW 1/on_settle.json
Adya/Rsp/RSP-LSP/FLOW 1/receiver_recon.json
Adya/Rsp/RSP-LSP/FLOW 1/settle.json
Adya/Rsp/RSP-LSP/FLOW 2/Correction Flow/collector_recon.json
Adya/Rsp/RSP-LSP/FLOW 2/Correction Flow/on_collector_recon.json
Adya/Rsp/RSP-LSP/FLOW 2/Correction Flow/on_receiver_recon.json
Adya/Rsp/RSP-LSP/FLOW 2/Correction Flow/on_settle.json
Adya/Rsp/RSP-LSP/FLOW 2/Correction Flow/receiver_recon.json
Adya/Rsp/RSP-LSP/FLOW 2/Correction Flow/settle.json
Adya/Rsp/RSP-LSP/FLOW 2/Normal Flow/collector_recon.json
Adya/Rsp/RSP-LSP/FLOW 2/Normal Flow/on_collector_recon.json
Adya/Rsp/RSP-LSP/FLOW 2/Normal Flow/on_receiver_recon.json
Adya/Rsp/RSP-LSP/FLOW 2/Normal Flow/on_settle.json
Adya/Rsp/RSP-LSP/FLOW 2/Normal Flow/receiver_recon.json
Adya/Rsp/RSP-LSP/FLOW 2/Normal Flow/settle.json

Regarding last Adya LSP (RSP) - compliance check #319 
For the issue point 1 , which is "settlement_status" in collector_recon, we have followed as per ondc Dataset Schema and sample payload of RSP, which says "settlement_status" will be "READY" in the collector_recon, please correct if we are worng. 
And remaining points were resolved and submitted.Kindly verify,Thank you.

Adya RSP-LSP Log

---

COSTBO/RSF-logs/on_receiver_recon-corrected.json
COSTBO/RSF-logs/on_settle.json
COSTBO/RSF-logs/receiver_recon-corrected.json
COSTBO/RSF-logs/settle.json

Costbo RSP logs Updated with fixes for requestedcomments

Costbo RSP logs Updated with fixes for requestedcomments

---

COSTBO/COSTBO-IGM-logs/IGM-comments-addressed-for-messageId-and-updatedat-for-onissuestatus/On_issue_status.json
COSTBO/COSTBO-IGM-logs/IGM-comments-addressed-for-messageId-and-updatedat-for-onissuestatus/issue(closed).json
COSTBO/COSTBO-IGM-logs/IGM-comments-addressed-for-messageId-and-updatedat-for-onissuestatus/issue.json
COSTBO/COSTBO-IGM-logs/IGM-comments-addressed-for-messageId-and-updatedat-for-onissuestatus/issue_status.json
COSTBO/COSTBO-IGM-logs/IGM-comments-addressed-for-messageId-and-updatedat-for-onissuestatus/on_issue_status(unsolicited-resolved).json
COSTBO/COSTBO-IGM-logs/IGM-comments-addressed-for-messageId-and-updatedat-for-onissuestatus/onissue.json
COSTBO/retail-v120-logs/Retail-Reupdate-on_search_and_on_select_fix-requestedon-dec22/on_search.json
COSTBO/retail-v120-logs/Retail-Reupdate-on_search_and_on_select_fix-requestedon-dec22/on_select.json
COSTBO/retail-v120-logs/Update-on_search_and_on_select_fix/on_search.json
COSTBO/retail-v120-logs/Update-on_search_and_on_select_fix/on_select.json

COSTBO - Retail logs update and IGM logs update 
Updated comments as per Rishabh for IGM
reupdate the retail logs for Sahil  for latest comments.

COSTBO - Retail logs update and IGM logs update 

---

Paytm/SellerApp/V1.2 Paytm Seller Logs/Search:On_Search/location_temporary_disable_incremental.json

location_temporary_disable_incremental.json added

[Paytm] Create location_temporary_disable_incremental.json

---

Paytm/SellerApp/V1.2 Paytm Seller Logs/incremental/product_incremental.json

Added log for Incremental pull request for product type.

[Paytm] Create product_incremental.json

---

COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/confirm.json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/init.json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/on_Init.json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/on_confirm.json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/on_search.json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/on_select.json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/on_status(In-Progress).json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/on_status(accepted).json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/on_status(completed).json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/search.json
COSTBO/retail-v120-logs/Dec29-search-onsearch-to-ordercompleted-Flow2/select.json

COSTBO - Retaillogs-fixes for comments from CharanpreetChawla-onDec29
Includes fixes for 
Flow 1
/on_search
Categories not present even when parent_item_id is present in items
Flow 2
/on_select
slots and tracking are not available as per flow
message.fulfillments.type is not present. (Delivery/self-pickup)
/on_init
message.order.items[n].parent_item_id not present. (but present in on_search).
/on_confirm
message.order.items[n].parent_item_id not present. (but present in on_search).
message.order.fulfillments.tracking is "true". (but false in /on_select, /on_init)

COSTBO - Retaillogs-fixes for comments from CharanpreetChawla-onDec29

---

mytra/Buyer NP/Flow 1/Inc/on_search.json

@bluecypher - Incorrect log uploaded in the previous PR. Now changed.

Mytra Buyer App log review

---

COSTBO/COSTBO-IGM-logs/Flow1(Item)-4thJan-Corrected/Issue(closed).json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-4thJan-Corrected/issue-status.json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-4thJan-Corrected/issue.json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-4thJan-Corrected/on-issue-status(resolved).json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-4thJan-Corrected/on-issue-status.json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-4thJan-Corrected/onissue.json
COSTBO/RSF-logs/Corrected-4thJan/on_receiver_recon.json
COSTBO/RSF-logs/Corrected-4thJan/on_settle.json
COSTBO/RSF-logs/Corrected-4thJan/receiver_recon.json
COSTBO/RSF-logs/Corrected-4thJan/settle.json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/confirm.json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/init.json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/on_confirm.json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/on_init.json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/on_search.json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/on_select.json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/on_status(In-Progress).json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/on_status(accepted).json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/on_status(completed).json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/search.json
COSTBO/retail-v120-logs/update-Jan3-flow1-flow2/select.json

Costbo RSF Logs with correction requests
-  receiver recon
- on receiver recon
-  settle
- on settle

Costbo RSF Logs with correction requests

---

COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/confirm.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/init.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/on_confirm.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/on_init.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/on_search.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/on_select.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/on_status_Accepted.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/on_status_Completed.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/on_status_In-progress.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/on_status_solicited-response.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/search.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/select.json
COSTBO/retail-v120-logs/Jan8-search-to-OrderCompleted/status_solicited-request.json

COSTBO-Jan8-Retail-logs-   comments-from-Sahil-fixed

COSTBO-Jan8-Retail-logs-comments-fixed

---

MP2/LSP/RSF/Flow1/on_reciever_recon.json
MP2/LSP/RSF/Flow1/reciever_recon.json
MP2/LSP/RSF/Flow2/on_reciever_recon.json
MP2/LSP/RSF/Flow2/reciever_recon.json

Submitting the 2 Flows for RSF for MP2 LSP
@bluecypher Pls merge and review
cc: @Poornima-Aithal

MP2 LSP RSF Logs

---

COSTBO/COSTBO-IGM-logs/Flow1(Item)-9thJan-updated/Issue(closed).json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-9thJan-updated/issue-status.json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-9thJan-updated/issue.json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-9thJan-updated/on-issue-status(resolved).json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-9thJan-updated/on-issue-status.json
COSTBO/COSTBO-IGM-logs/Flow1(Item)-9thJan-updated/onissue.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/confirm.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/init.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-confirm.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-init.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-search.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-select.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-status-Accepted.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-status-Completed.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-status-In-Progress.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-status-solicited-reponse.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/on-status-solicited-requet.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/search.json
COSTBO/retail-v120-logs/Jan12-search-to-orderCompleted/select.json

COSTBO - Jan12 - Fixed Feedback from Sahil

Costbo v120ph1 retaillogs

---

COSTBO/RSF-logs/corrected-16thJan/on-receiver-recon.json
COSTBO/RSF-logs/corrected-16thJan/on-settle.json
COSTBO/RSF-logs/corrected-16thJan/receiver_recon.json
COSTBO/RSF-logs/corrected-16thJan/settle.json

COSTBO RSF logs corrected.  Fixed for the comments posted on Jan15th.

COSTBO RSF logs corrected

---

Phonepe/sellerApp/Flow1/confirm.json
Phonepe/sellerApp/Flow1/init.json
Phonepe/sellerApp/Flow1/on_confirm.json
Phonepe/sellerApp/Flow1/on_init.json
Phonepe/sellerApp/Flow1/on_select.json
Phonepe/sellerApp/Flow1/on_status1.json
Phonepe/sellerApp/Flow1/on_status2.json
Phonepe/sellerApp/Flow1/on_status3.json
Phonepe/sellerApp/Flow1/on_status4.json
Phonepe/sellerApp/Flow1/select.json
Phonepe/sellerApp/Flow2/cancel.json
Phonepe/sellerApp/Flow2/confirm.json
Phonepe/sellerApp/Flow2/init.json
Phonepe/sellerApp/Flow2/on_cancel.json
Phonepe/sellerApp/Flow2/on_confirm.json
Phonepe/sellerApp/Flow2/on_init.json
Phonepe/sellerApp/Flow2/on_select.json
Phonepe/sellerApp/Flow2/on_status.json
Phonepe/sellerApp/Flow2/select.json
Phonepe/sellerApp/SearchFlow/on_search.json
Phonepe/sellerApp/SearchFlow/search.json

Please find seller Application logs from Phonepe attached here

seller logs from Phonepe

---

Phonepe/buyerApp/Flow1/on_search_bpc.json
Phonepe/buyerApp/Flow1/on_search_fashion.json
Phonepe/buyerApp/Flow1/search_bpc.json
Phonepe/buyerApp/Flow1/search_fashion.json

Please find search requests for other categories attached here

other category based searches

---

COSTBO/retail-v120-logs/Jan18-retail-logs/confirm.json
COSTBO/retail-v120-logs/Jan18-retail-logs/init.json
COSTBO/retail-v120-logs/Jan18-retail-logs/on_confirm.json
COSTBO/retail-v120-logs/Jan18-retail-logs/on_init.json
COSTBO/retail-v120-logs/Jan18-retail-logs/on_search.json
COSTBO/retail-v120-logs/Jan18-retail-logs/on_select.json
COSTBO/retail-v120-logs/Jan18-retail-logs/on_status_InProgress.json
COSTBO/retail-v120-logs/Jan18-retail-logs/on_status_accepted.json
COSTBO/retail-v120-logs/Jan18-retail-logs/on_status_completed.json
COSTBO/retail-v120-logs/Jan18-retail-logs/search.json
COSTBO/retail-v120-logs/Jan18-retail-logs/select.json
COSTBO/retail-v120-logs/Jan18-retail-logs/solicited_On_status_response.json
COSTBO/retail-v120-logs/Jan18-retail-logs/solicited_status_request.json

COSTBO - RETAIL -  Jan18th-Addressing Sahils comment on fulfilment timestamp

COSTBO - RETAIL -  Jan18th-Addressing Sahils comment on fulfilment timestamp

---

COSTBO/COSTBO-IGM-logs/Flow1(item)-18thJan-updated/issue-closed.json
COSTBO/COSTBO-IGM-logs/Flow1(item)-18thJan-updated/issue.json
COSTBO/COSTBO-IGM-logs/Flow1(item)-18thJan-updated/on-issue-statue-resolved.json
COSTBO/COSTBO-IGM-logs/Flow1(item)-18thJan-updated/on-issue.json
COSTBO/COSTBO-IGM-logs/Flow1(item)-18thJan-updated/solicited-issue-status.json
COSTBO/COSTBO-IGM-logs/Flow1(item)-18thJan-updated/solicited-on-issus-status.json

COSTBO-IGM-repeat-after-preprodbuyerappv2-fix

COSTBO-IGM-repeat-after-preprodbuyerappv2-fix

---

COSTBO/RSF-logs/RSF-correction-and-successflow-Jan20-2024/on-receiver-recon.json
COSTBO/RSF-logs/RSF-correction-and-successflow-Jan20-2024/on-settle.json
COSTBO/RSF-logs/RSF-correction-and-successflow-Jan20-2024/receiver_recon.json
COSTBO/RSF-logs/RSF-correction-and-successflow-Jan20-2024/settle.json

COSTBO-5-orderbooks-with-correction-and-successflow-Jan20-2024

COSTBO-5-orderbooks-with-correction-and-successflow-Jan20-2024

---

Gofrugal/Flow 3/on_select-with_stock.json
Gofrugal/Flow 3/on_select-without_stock (1).json
Gofrugal/Flow 3/select-with_stock.json
Gofrugal/Flow 3/select-without_stock (1).json

/on_select (out of stock) error code changes

Fixed /on_select (out of stock) error message

---

Udyamwell/Retailer Buyer and seller np logs/Flow1/Full_catalog_on_search.json
Udyamwell/Retailer Buyer and seller np logs/Flow1/Incremental_search.json
Udyamwell/Retailer Buyer and seller np logs/Flow1/incremental_on_search.json
Udyamwell/Retailer Buyer and seller np logs/Flow2/confirm.json
Udyamwell/Retailer Buyer and seller np logs/Flow2/on_confirm.json
Udyamwell/Retailer Buyer and seller np logs/Flow2/on_init.json
Udyamwell/Retailer Buyer and seller np logs/Flow2/on_select.json
Udyamwell/Retailer Buyer and seller np logs/Flow2/unsolisted_on_status(agent-assign).json
Udyamwell/Retailer Buyer and seller np logs/Flow2/unsolisted_on_status(order-deliver-completed).json
Udyamwell/Retailer Buyer and seller np logs/Flow2/unsolisted_on_status(picked-up).json

We have resolved the issues as per suggestion for retails flow 1 & 2
Please review it and merge this pull request

Updated logs for Retail flow 1 & Flow 2

---

ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/full_catalog_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/full_catalog_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/incremental_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/incremental_search.json

Updated Flow 1 logs as per the latest feedback in #92 
@bluecypher

#92 Flow 1 - updated logs

---

Nivea Shop/RSF/Correction Flow/on_receiver_recon.json
Nivea Shop/RSF/Correction Flow/receiver_recon.json
Nivea Shop/RSF/Success Recon/on_receiver_recon.json
Nivea Shop/RSF/Success Recon/receiver_recon.json

@bluecypher  added  latest logs for RSF
Successful reconciliation by the receiver for 5 or more transactions
Correction flow initiated by the receiver in /on_receiver_recon

Nivea Shop - RSF Updated Logs

---

Krenai_Retail/IGM/IGM-LOG-30-JAN-2024-FINAL/FLOW-1/issue.json
Krenai_Retail/IGM/IGM-LOG-30-JAN-2024-FINAL/FLOW-1/issue_close.json
Krenai_Retail/IGM/IGM-LOG-30-JAN-2024-FINAL/FLOW-1/issue_status.json
Krenai_Retail/IGM/IGM-LOG-30-JAN-2024-FINAL/FLOW-1/on_issue.json
Krenai_Retail/IGM/IGM-LOG-30-JAN-2024-FINAL/FLOW-1/on_issue_close.json
Krenai_Retail/IGM/IGM-LOG-30-JAN-2024-FINAL/FLOW-1/on_issue_status.json

Updated IGM logs

---

Xpressbees/cancellation/cancel.json
Xpressbees/cancellation/confirm.json
Xpressbees/cancellation/init.json
Xpressbees/cancellation/on_cancel.json
Xpressbees/cancellation/on_confirm.json
Xpressbees/cancellation/on_init.json
Xpressbees/cancellation/on_search.json
Xpressbees/cancellation/on_status_cancelled.json
Xpressbees/cancellation/on_status_created_pending.json
Xpressbees/cancellation/on_update.json
Xpressbees/cancellation/search.json
Xpressbees/cancellation/status.json
Xpressbees/cancellation/update.json
Xpressbees/forward/confirm.json
Xpressbees/forward/init.json
Xpressbees/forward/on_confirm.json
Xpressbees/forward/on_init.json
Xpressbees/forward/on_search.json
Xpressbees/forward/on_status_completed_order-deilvered.json
Xpressbees/forward/on_status_created_pending.json
Xpressbees/forward/on_status_inporgress_agent-assigned.json
Xpressbees/forward/on_status_inporgress_order-picked-up.json
Xpressbees/forward/on_status_inporgress_out-for-delivery.json
Xpressbees/forward/on_update.json
Xpressbees/forward/search.json
Xpressbees/forward/status.json
Xpressbees/forward/update.json

submitted the log of v1.2.0 phase 1. kindly review it.
@bluecypher

xpressbees log for v1.2.0 phase 1

---

Paytm/GV2.0.0/GV_IGM_LOGS/Fulfilment Flow /issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Fulfilment Flow /issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Fulfilment Flow /on_issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Fulfilment Flow /on_issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/on_issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/on_issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/on_issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/on_issue_status.json
Paytm/GV2.0.0/GV_Order_Flow/Multi Item/Confirm.json
Paytm/GV2.0.0/GV_Order_Flow/Multi Item/Init.json
Paytm/GV2.0.0/GV_Order_Flow/Multi Item/Select.json
Paytm/GV2.0.0/GV_Order_Flow/Search.json
Paytm/GV2.0.0/GV_Order_Flow/Single Item/Cancel.json
Paytm/GV2.0.0/GV_Order_Flow/Single Item/Confirm.json
Paytm/GV2.0.0/GV_Order_Flow/Single Item/Init.json
Paytm/GV2.0.0/GV_Order_Flow/Single Item/Select.json
Paytm/GV2.0.0/GV_RSP_Logs/Correction Flow/Correction-Flow-1.json
Paytm/GV2.0.0/GV_RSP_Logs/Settlement flow/Settlement-Flow-1.json
Paytm/GV2.0.0/GV_RSP_Logs/Settlement flow/Settlement-Flow-2.json
Paytm/buyer_app/RSP Logs/overpaid/on_receiver_recon.json
Paytm/buyer_app/RSP Logs/overpaid/receiver_recon.json
Paytm/buyer_app/RSP Logs/paid/on_receiver_recon.json
Paytm/buyer_app/RSP Logs/paid/receiver_recon.json
Paytm/buyer_app/RSP Logs/underpaid/on_receiver_recon.json
Paytm/buyer_app/RSP Logs/underpaid/receiver_recon.json

- GV RSP Logs ( with Correction Flow and Settlement Flow)
- GV Order Journey ( For Single Item with cancel and Multi Item )
- GV IGM Logs ( For Item, Fulfilment and Payment)
- Buyer RSP Logs (For paid, Overpaid and underpaid scenarios)

Uploading logs for GV - Order Journey, RSP and IGM

---

Phonepe/buyerApp/Flow1/on_search_appliances.json
Phonepe/buyerApp/Flow1/on_search_health.json
Phonepe/buyerApp/Flow1/on_search_home_decor.json
Phonepe/buyerApp/Flow1/search_appliances.json
Phonepe/buyerApp/Flow1/search_health.json
Phonepe/buyerApp/Flow1/search_home_decor.json

Please find the logs attached for RET15, RET16 and RET18 in this PR

required search logs for phonepe buyerApp

---

COSTBO/RSF-logs/RSF-ReceiverFlow-success-and-corrected-flow-Feb2nd-2024/Recon-Flow/receiver_recon.json
COSTBO/RSF-logs/RSF-ReceiverFlow-success-and-corrected-flow-Feb2nd-2024/Settle-Flow/settle.json

COSTBO - RSF - update - fixes pushed for settle & receiver_recon

COSTBO - RSF - update - fixes pushed for settle & receiver_recon

---

TMBill/Group A/Flow 1/full_catalogue_on_search.json
TMBill/Group A/Flow 1/full_catalogue_search.json

fix: TMBill Logs ReSubmission

---

Nivea Shop/RSF/Correction Flow/on_receiver_recon.json
Nivea Shop/RSF/Correction Flow/receiver_recon.json
Nivea Shop/RSF/Success Recon/on_receiver_recon.json
Nivea Shop/RSF/Success Recon/receiver_recon.json

@bluecypher 
- corrected finder fee type
- corrected settlement_timestamp

Nivea Shop - RSF Logs(updated)

---

jubilant/IGM/flow1/issue_CLOSED.json
jubilant/IGM/flow1/issue_CREATED.json
jubilant/IGM/flow1/issue_status.json
jubilant/IGM/flow1/on_issue_CREATED.json
jubilant/IGM/flow1/on_issue_status_IN_PROGRESS.json
jubilant/IGM/flow1/on_issue_status_RESOLVED.json
jubilant/IGM/flow2/issue_close.json
jubilant/IGM/flow2/issue_create.json
jubilant/IGM/flow2/issue_status.json
jubilant/IGM/flow2/on_issue_create.json
jubilant/IGM/flow2/on_issue_status_IN_PROGRESS.json
jubilant/IGM/flow2/on_issue_status_RESOLVED.json

IGM Log submission

---

Xpressbees/Flow 1/on_search.json
Xpressbees/Flow 1/search.json
Xpressbees/Flow 2/confirm.json
Xpressbees/Flow 2/init.json
Xpressbees/Flow 2/on_confirm.json
Xpressbees/Flow 2/on_init.json
Xpressbees/Flow 2/on_status_agent_assigned.json
Xpressbees/Flow 2/on_status_order_delivered.json
Xpressbees/Flow 2/on_status_order_picked_up.json
Xpressbees/Flow 2/on_status_out_for_delivery.json
Xpressbees/Flow 3/confirm.json
Xpressbees/Flow 3/init.json
Xpressbees/Flow 3/on_confirm.json
Xpressbees/Flow 3/on_init.json
Xpressbees/Flow 3/on_status_agent_assigned.json
Xpressbees/Flow 3/on_status_order_picked_up.json
Xpressbees/Flow 3/on_status_out_for_delivery.json
Xpressbees/Flow 3/on_status_rto_delivered.json
Xpressbees/Flow 3/on_status_rto_initiated.json

@bluecypher 
logs tested with LBNP sellerApp 1.2.0 phase 1

logs tested with LBNP sellerApp v1.2.0 phase 1

---

Nivea Shop/Group A/Flow 1/on_search_full_catalog.json
Nivea Shop/Group A/Flow 1/on_search_inc_catalog_local.json
Nivea Shop/Group A/Flow 1/search_full_catalog.json
Nivea Shop/Group A/Flow 1/search_inc_catalog_local.json
Nivea Shop/Group A/Flow 2/confirm.json
Nivea Shop/Group A/Flow 2/init.json
Nivea Shop/Group A/Flow 2/on_confirm.json
Nivea Shop/Group A/Flow 2/on_init.json
Nivea Shop/Group A/Flow 2/on_select.json
Nivea Shop/Group A/Flow 2/on_status_Order-delivered.json
Nivea Shop/Group A/Flow 2/on_status_Order-picked-up.json
Nivea Shop/Group A/Flow 2/on_status_Out-for-delivery.json
Nivea Shop/Group A/Flow 2/on_status_Pending.json
Nivea Shop/Group A/Flow 2/on_track.json
Nivea Shop/Group A/Flow 2/select.json
Nivea Shop/Group A/Flow 2/track.json
Nivea Shop/Group A/Flow 3/confirm.json
Nivea Shop/Group A/Flow 3/init.json
Nivea Shop/Group A/Flow 3/on_confirm.json
Nivea Shop/Group A/Flow 3/on_init.json
Nivea Shop/Group A/Flow 3/on_select.json
Nivea Shop/Group A/Flow 3/on_select_(out_of_stock).json
Nivea Shop/Group A/Flow 3/on_status_Order-delivered.json
Nivea Shop/Group A/Flow 3/on_status_Order-picked-up.json
Nivea Shop/Group A/Flow 3/on_status_Out-for-delivery.json
Nivea Shop/Group A/Flow 3/on_status_Pending.json
Nivea Shop/Group A/Flow 3/on_track.json
Nivea Shop/Group A/Flow 3/select.json
Nivea Shop/Group A/Flow 3/select_(out_of_stock).json
Nivea Shop/Group A/Flow 3/track.json

@bluecypher Group A logs Submitted

Nivea Shop- Seller Group A-Updated Logs

---

Fynd/SellerApp/January 2024/RET12/Flow 3/On_init.json
Fynd/SellerApp/January 2024/RET12/Flow 3/confirm.json
Fynd/SellerApp/January 2024/RET12/Flow 3/init.json
Fynd/SellerApp/January 2024/RET12/Flow 3/on_Select.json
Fynd/SellerApp/January 2024/RET12/Flow 3/on_Select_updated.json
Fynd/SellerApp/January 2024/RET12/Flow 3/on_confirm.json
Fynd/SellerApp/January 2024/RET12/Flow 3/on_status_accepted.json
Fynd/SellerApp/January 2024/RET12/Flow 3/on_status_delivered.json
Fynd/SellerApp/January 2024/RET12/Flow 3/on_status_out_for_delivery.json
Fynd/SellerApp/January 2024/RET12/Flow 3/on_status_packed.json
Fynd/SellerApp/January 2024/RET12/Flow 3/on_status_picked.json
Fynd/SellerApp/January 2024/RET12/Flow 3/select.json
Fynd/SellerApp/January 2024/RET12/Flow 3/select_updated.json

Fynd Seller app updated logs for flow 3

Fynd Seller App - Flow 3 updated logs

---

mytra/Seller NP/Flow 5/confirm.json
mytra/Seller NP/Flow 5/init.json
mytra/Seller NP/Flow 5/on_confirm.json
mytra/Seller NP/Flow 5/on_init.json
mytra/Seller NP/Flow 5/on_select.json
mytra/Seller NP/Flow 5/on_status_out_for_delivery.json
mytra/Seller NP/Flow 5/on_status_packed.json
mytra/Seller NP/Flow 5/on_status_pending.json
mytra/Seller NP/Flow 5/on_status_picked.json
mytra/Seller NP/Flow 5/select.json

@bluecypher - I have updated the flow 5 in this commit. The other flows are already merged by you.

Mytra Seller App - Flow 5 - updated

---

Krenai_Retail/RSP/CORRECTION FLOW/on_receiver_recon.json
Krenai_Retail/RSP/CORRECTION FLOW/receiver_recon.json
Krenai_Retail/RSP/SUCCESS FLOW/on_receiver_recon.json
Krenai_Retail/RSP/SUCCESS FLOW/receiver_recon.json

RSF logs updated as per latest doc

RSF logs updated as per latest doc

---

More Retail Private Limited/IGM Logs/Flow 1/issue(close).json
More Retail Private Limited/IGM Logs/Flow 1/issue.json
More Retail Private Limited/IGM Logs/Flow 1/issue_status.json
More Retail Private Limited/IGM Logs/Flow 1/on_issue.json
More Retail Private Limited/IGM Logs/Flow 1/on_issue_status(unsolicited).json
More Retail Private Limited/IGM Logs/Flow 1/on_issue_status.json

Please check the IGM Logs.
We will update the issue of Retail Logs as soon as possible.

IGM Logs From More Retail Private Limited

---

Tipplr/Tipplr - IGM/flow-1/1_issue(open).json
Tipplr/Tipplr - IGM/flow-1/2_on_issue(processing).json
Tipplr/Tipplr - IGM/flow-1/3_issue_status.json
Tipplr/Tipplr - IGM/flow-1/4_on_issue_status(processing).json
Tipplr/Tipplr - IGM/flow-1/5_on_issue_status(refund).json
Tipplr/Tipplr - IGM/flow-1/6_issue(closed).json
Tipplr/Tipplr - IGM/flow-2/1_issue(open).json
Tipplr/Tipplr - IGM/flow-2/2_on_issue(processing).json
Tipplr/Tipplr - IGM/flow-2/3_issue_status.json
Tipplr/Tipplr - IGM/flow-2/4_on_issue_status(processing).json
Tipplr/Tipplr - IGM/flow-2/5_on_issue_status(refund).json
Tipplr/Tipplr - IGM/flow-2/6_issue(closed).json
Tipplr/Tipplr - IGM/readme.md
Tipplr/Tipplr-RSF-updated(Feb-16)/Flow 1 Success/on_receiver_recon.json
Tipplr/Tipplr-RSF-updated(Feb-16)/Flow 1 Success/receiver_recon.json
Tipplr/Tipplr-RSF-updated(Feb-16)/Flow 2 Correction/on_receiver_recon.json
Tipplr/Tipplr-RSF-updated(Feb-16)/Flow 2 Correction/receiver_recon.json

Hi there,
I have corrected as mentioned by you. Please verify them.
Thanks

Tipplr SA -Added correct rsf flow

---

jubilant/IGM/flow1/issue_CLOSED.json
jubilant/IGM/flow1/issue_CREATED.json
jubilant/IGM/flow1/issue_status.json
jubilant/IGM/flow1/on_issue_CREATED.json
jubilant/IGM/flow1/on_issue_status_IN_PROGRESS.json
jubilant/IGM/flow1/on_issue_status_RESOLVED.json
jubilant/IGM/flow2/issue_close.json
jubilant/IGM/flow2/issue_create.json
jubilant/IGM/flow2/issue_status.json
jubilant/IGM/flow2/on_issue_create.json
jubilant/IGM/flow2/on_issue_status_IN_PROGRESS.json
jubilant/IGM/flow2/on_issue_status_RESOLVED.json

IGM Logs Corrections

---

Dailybee/Logs_Feb_20/Ret:10/Flow1/on_search_full_catalog_refresh.json
Dailybee/Logs_Feb_20/Ret:10/Flow1/on_search_inc_refresh.json
Dailybee/Logs_Feb_20/Ret:10/Flow1/search_full_catalog_refresh.json
Dailybee/Logs_Feb_20/Ret:10/Flow1/search_inc_refresh.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/confirm.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/init.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/on_confirm.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/on_init.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/on_select.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/on_status_delivered.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/on_status_packed.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/on_status_pending.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/on_status_picked.json
Dailybee/Logs_Feb_20/Ret:10/Flow2/select.json

https://github.com/ONDC-Official/v1.2.0-logs/issues/803
@bluecypher

Dailybee (SA: RET10) - addressed compliance checks

---

Channelier/RET:10/Group A/Flow 1/on_search_full_catalog_refresh.json
Channelier/RET:10/Group A/Flow 1/on_search_incremental_catalog_refresh.json
Channelier/RET:10/Group A/Flow 1/search_full_catalog_refresh.json
Channelier/RET:10/Group A/Flow 1/search_incremental_catalog_refresh.json
Channelier/RET:10/Group A/Flow 2/confirm.json
Channelier/RET:10/Group A/Flow 2/init.json
Channelier/RET:10/Group A/Flow 2/on_confirm.json
Channelier/RET:10/Group A/Flow 2/on_init.json
Channelier/RET:10/Group A/Flow 2/on_select.json
Channelier/RET:10/Group A/Flow 2/on_status_accepted.json
Channelier/RET:10/Group A/Flow 2/on_status_delivered.json
Channelier/RET:10/Group A/Flow 2/on_status_out_for_delivery.json
Channelier/RET:10/Group A/Flow 2/on_status_packed.json
Channelier/RET:10/Group A/Flow 2/on_status_picked_up.json
Channelier/RET:10/Group A/Flow 2/on_track.json
Channelier/RET:10/Group A/Flow 2/select.json
Channelier/RET:10/Group A/Flow 2/track.json

Channelier ONDC Logs for RET:10 after feedback #879

logs after feedbacks

---

ShopEG/RSF - With local mock server/Flow 1 - success flow/on_receiver_recon.json
ShopEG/RSF - With local mock server/Flow 1 - success flow/on_settle.json
ShopEG/RSF - With local mock server/Flow 1 - success flow/receiver_recon.json
ShopEG/RSF - With local mock server/Flow 1 - success flow/settle.json
ShopEG/RSF - With local mock server/Flow 2 - correction flow /on_receiver_recon.json
ShopEG/RSF - With local mock server/Flow 2 - correction flow /on_settle.json
ShopEG/RSF - With local mock server/Flow 2 - correction flow /receiver_recon.json
ShopEG/RSF - With local mock server/Flow 2 - correction flow /settle.json

- Tested using local mock server utility
- onSettle and onReceiverRecon data modified in the local server yaml files to simulate real order data from preprod ondc buyer app
- order ids reused for both flows

ShopEG - RSF - 2 flows and merchant settlement - Tested with local mock server

---

Krenai_Retail/RSP/CORRECTION/on_receiver_recon.json
Krenai_Retail/RSP/CORRECTION/receiver_recon.json
Krenai_Retail/RSP/SUCCESS/on_receiver_recon.json
Krenai_Retail/RSP/SUCCESS/receiver_recon.json

RSF logs updated

---

mytra/Seller NP/Flow 1/Full/on_search.json
mytra/Seller NP/Flow 1/Full/search.json
mytra/Seller NP/Flow 1/Inc/on_search.json
mytra/Seller NP/Flow 1/Inc/search.json
mytra/Seller NP/Flow 3/confirm.json
mytra/Seller NP/Flow 3/init.json
mytra/Seller NP/Flow 3/on_confirm.json
mytra/Seller NP/Flow 3/on_init.json
mytra/Seller NP/Flow 3/on_select.json
mytra/Seller NP/Flow 3/on_select_out_of_stock.json
mytra/Seller NP/Flow 3/on_status_delivered.json
mytra/Seller NP/Flow 3/on_status_out_for_delivery.json
mytra/Seller NP/Flow 3/on_status_packed.json
mytra/Seller NP/Flow 3/on_status_pending.json
mytra/Seller NP/Flow 3/on_status_picked.json
mytra/Seller NP/Flow 3/select.json
mytra/Seller NP/Flow 3/select_out_of_stock.json

Logs submitted in response to the [issues raised](https://github.com/ONDC-Official/v1.2.0-logs/issues/849)

Mytra Seller App - Revised Logs as per issues raised.

---

jubilant/IGM/flow1/issue_CLOSED.json
jubilant/IGM/flow1/issue_CREATED.json
jubilant/IGM/flow1/issue_status.json
jubilant/IGM/flow1/on_issue_CREATED.json
jubilant/IGM/flow1/on_issue_status_IN_PROGRESS.json
jubilant/IGM/flow1/on_issue_status_RESOLVED.json
jubilant/IGM/flow2/issue_close.json
jubilant/IGM/flow2/issue_create.json
jubilant/IGM/flow2/issue_status.json
jubilant/IGM/flow2/on_issue_create.json
jubilant/IGM/flow2/on_issue_status_IN_PROGRESS.json
jubilant/IGM/flow2/on_issue_status_RESOLVED.json

Fixed Feedback Points

---

Tipplr/Tipplr-RSF-updated(Feb-29)/Flow 1 Success/on_receiver_recon.json
Tipplr/Tipplr-RSF-updated(Feb-29)/Flow 1 Success/receiver_recon.json
Tipplr/Tipplr-RSF-updated(Feb-29)/Flow 2 Correction/on_receiver_recon.json
Tipplr/Tipplr-RSF-updated(Feb-29)/Flow 2 Correction/receiver_recon.json

Hi there,
Have made changes as per compliance raised related to RSF by ondc team please merge my pr.
Thank you

Tipplr SA(RSF) - updated as per compliance

---

Dailybee/Logs_Feb_29/RET:10/Flow1/on_search_full_catalog_refresh.json
Dailybee/Logs_Feb_29/RET:10/Flow1/search_full_catalog_refresh.json

https://github.com/ONDC-Official/v1.2.0-logs/issues/803

chore: extracted modified logs for flow 1

---

ShopEG/RSF - With local mock server/Flow 1 - success flow/on_receiver_recon.json
ShopEG/RSF - With local mock server/Flow 1 - success flow/on_settle.json
ShopEG/RSF - With local mock server/Flow 1 - success flow/receiver_recon.json
ShopEG/RSF - With local mock server/Flow 1 - success flow/settle.json
ShopEG/RSF - With local mock server/Flow 2 - correction flow /on_receiver_recon.json
ShopEG/RSF - With local mock server/Flow 2 - correction flow /on_settle.json
ShopEG/RSF - With local mock server/Flow 2 - correction flow /receiver_recon.json
ShopEG/RSF - With local mock server/Flow 2 - correction flow /settle.json

RSF flow redo because of context.bpp_id in settle/on_settle

---

CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/full_catalog_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/full_catalog_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/incremental_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/incremental_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/full_catalog_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/full_catalog_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/incremental_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/incremental_search.json

BPC, Home & Kitchen catalog logs

Bpc, Home & kitchen catalog logs update

---

MaasErp/RSP/RSP_logs_02_03_24/Flow1/on_receiver_recon.json
MaasErp/RSP/RSP_logs_02_03_24/Flow1/receiver_recon.json
MaasErp/RSP/RSP_logs_02_03_24/Flow2/on_receiver_recon(after correction).json
MaasErp/RSP/RSP_logs_02_03_24/Flow2/on_receiver_recon.json
MaasErp/RSP/RSP_logs_02_03_24/Flow2/receiver_recon(correction).json
MaasErp/RSP/RSP_logs_02_03_24/Flow2/receiver_recon.json

RSP_logs_02_03_24 MaasERP

---

Phonepe/sellerApp/SearchFlow/on_search2.json
Phonepe/sellerApp/SearchFlow/search2.json

Please find modified search and on_search logs in this PR

search logs v2

---

MaasErp/RSP/RSP_logs_06_03_24/Flow1/on_receiver_recon.json
MaasErp/RSP/RSP_logs_06_03_24/Flow1/receiver_recon.json
MaasErp/RSP/RSP_logs_06_03_24/Flow2/on_receiver_recon(after%20correction).json
MaasErp/RSP/RSP_logs_06_03_24/Flow2/on_receiver_recon.json
MaasErp/RSP/RSP_logs_06_03_24/Flow2/receiver_recon(correction).json
MaasErp/RSP/RSP_logs_06_03_24/Flow2/receiver_recon.json

MaasErp updated Flows of RSP

---

ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/full_catalog_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/full_catalog_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/incremental_item_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/incremental_provider_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/incremental_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 1/incremental_store_on_search.json

ShopEG - Flow 1 resubmission 

---

Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow1/1. search_full_catalog.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow1/2. on_search_full_catalog.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow1/3. search_incremental.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow1/4. on_search_incremental.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/1. select.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/2. on_select.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/3. init.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/4. on_init.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/5. confirm.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/6. on_confirm.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/7. on_status_order_accepted.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/8. on_status_out_for_delivery.json
Tipplr/seller-app-corrected-Mar-05(F&B-RET11)/Group A/Flow2/9. on_status_order_delivered.json

Hi @bluecypher,
I have added Retail logs as per the compliance opened.
I have only added the flow for which they have raised the issue.
I have already added all the flows(1-6) as per required(https://github.com/ONDC-Official/v1.2.0-logs/tree/master/Tipplr/seller-app-v1.2-logs(F%26B-RET11)/Group%20A).
Please accept my pr.
Thank you

Tipplr SA - Added Retails logs as per compliance

---

Ecom_Express_logs/RSF/Flow 1/on_receiver_recon_mock_server.json
Ecom_Express_logs/RSF/Flow 1/receiver_recon_mock_server.json
Ecom_Express_logs/RSF/Flow2/on_receiver_recon_mock_server.json
Ecom_Express_logs/RSF/Flow2/receiver_recon_mock_server.json

Updated logs with correct timestamp

Updated logs with correct timestamp

---

Dailybee/Logs_Mar_10/RET:10/Flow1/on_search_full_catalog_refresh.json
Dailybee/Logs_Mar_10/RET:10/Flow1/search_full_catalog_refresh.json

https://github.com/ONDC-Official/v1.2.0-logs/issues/803

Dailybee (SA: RET10) - logs for compliance check

---

More Retail Private Limited/RSP Logs/correction_flow/on_receiver_recon.json
More Retail Private Limited/RSP Logs/correction_flow/receiver_recon.json
More Retail Private Limited/RSP Logs/success_flow/on_receiver_recon.json
More Retail Private Limited/RSP Logs/success_flow/receiver_recon.json

Hi @RupalSingla
can you check the RSP Logs for the issue mentioned in #973 ?
Regards
Chinmaya M G

RSP Logs Fixes - More Retail Private Limited #973

---

More Retail Private Limited/RSP Logs/correction_flow/on_receiver_recon.json
More Retail Private Limited/RSP Logs/correction_flow/receiver_recon.json
More Retail Private Limited/RSP Logs/success_flow/on_receiver_recon.json
More Retail Private Limited/RSP Logs/success_flow/receiver_recon.json

Hi @extedcouD
Can you check the logs for the issue #973 ?

RSP Issue FIxed Logs - More Retail Private Limited ( #973 )

---

Tipplr/Tipplr-RSF-updated(Mar-12)/Flow 1 Success/on_receiver_recon.json
Tipplr/Tipplr-RSF-updated(Mar-12)/Flow 1 Success/receiver_recon.json
Tipplr/Tipplr-RSF-updated(Mar-12)/Flow 2 Correction/on_receiver_recon.json
Tipplr/Tipplr-RSF-updated(Mar-12)/Flow 2 Correction/receiver_recon.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow1/1. search_full_catalog.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow1/2. on_search_full_catalog.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow1/3. search_incremental.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow1/4. on_search_incremental.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/1. select.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/2. on_select.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/3. init.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/4. on_init.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/5. confirm.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/6. on_confirm.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/7. on_status_order_accepted.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/8. on_status_out_for_delivery.json
Tipplr/seller-app-corrected-Mar-11(F&B-RET11)/Group A/Flow2/9. on_status_order_delivered.json

Hi there,
Have worked on rsf and have updated as per contract document.
Please approve my pr.
Thank you.

Tipplr SA - Updated rsf logs as per compliance

---

Futuresoft/ONDC:RET12/Flow1/inc-search.json
Futuresoft/ONDC:RET12/Flow1/incr-onsearch.json
Futuresoft/ONDC:RET12/Flow1/onsearch.json
Futuresoft/ONDC:RET12/Flow1/search.json
Futuresoft/ONDC:RET12/Flow2/confirm.json
Futuresoft/ONDC:RET12/Flow2/init.json
Futuresoft/ONDC:RET12/Flow2/onconfirm.json
Futuresoft/ONDC:RET12/Flow2/oninit.json
Futuresoft/ONDC:RET12/Flow2/onselect.json
Futuresoft/ONDC:RET12/Flow2/onstatus1.json
Futuresoft/ONDC:RET12/Flow2/onstatus2.json
Futuresoft/ONDC:RET12/Flow2/onstatus3.json
Futuresoft/ONDC:RET12/Flow2/onstatus4.json
Futuresoft/ONDC:RET12/Flow2/ontrack.json
Futuresoft/ONDC:RET12/Flow2/select.json
Futuresoft/ONDC:RET12/Flow2/track.json

Flow1 & Flow2 has been updated as per fixing raised issues of complaince team

Issue fixes - compliance checks #974

---

Magicpin_logistics_buyer/igm/issue.json
Magicpin_logistics_buyer/igm/on_issue.json
Magicpin_logistics_buyer/igm/on_issue_status.json

magicpin - logistics buyer igm logs
issue
on_issue
on_issue_status

magicpin - logistics buyer igm logs

---

Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow1/1. search_full_catalog.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow1/2. on_search_full_catalog.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow1/3. search_incremental.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow1/4. on_search_incremental.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/1. select.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/10. on_status_out_for_delivery.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/11. on_status_order_delivered.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/2. on_select.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/3. init.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/4. on_init.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/5. confirm.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/6. on_confirm.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/7. on_status_order_pending.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/8. on_status_order_packed.json
Tipplr/seller-app-corrected-Mar-15(F&B-RET11)/Group A/Flow2/9. on_status_picked.json

Hi there,
Have added retails logs as per compliance.
Have used log validation utlity. Have uploaded the request flow.
Please accept my pr.
Thanks

Tipplr SA - Added Retail(RET11) Logs as per compliance

---

instastack-V1.2/flow_1/01_issue.json
instastack-V1.2/flow_1/02_on_issue.json
instastack-V1.2/flow_1/03_issue_status.json
instastack-V1.2/flow_1/04_on_issue_status.json
instastack-V1.2/flow_1/05_issue_closed.json
instastack-V1.2/flow_1/log-validation-input.json
instastack-V1.2/flow_1/log-validation-output.json
instastack-V1.2/flow_2/01_issue.json
instastack-V1.2/flow_2/02_on_issue.json
instastack-V1.2/flow_2/03_issue_status.json
instastack-V1.2/flow_2/04_on_issue_status.json
instastack-V1.2/flow_2/05_issue_closed.json
instastack-V1.2/flow_2/log-validation-input.json
instastack-V1.2/flow_2/log-validation-output.json

IGM logs V1.2

---

CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/Flow 1/full_catalog_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/Flow 1/full_catalog_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/Flow 1/incremental_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/Flow 1/incremental_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/Flow 1/full_catalog_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/Flow 1/full_catalog_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/Flow 1/incremental_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/Flow 1/incremental_search.json

Catalog updates on RET13 & RET16

Catalog updates

---

Plotchv1.2.0/resubmit_ret_10/flow1/on_search.json
Plotchv1.2.0/resubmit_ret_10/flow1/search.json

on_search resubmitted for RET 10 for Plotch

on_search resubmitted for RET 10 for Plotch

---

Mystore/Seller App Grocery/FLOW3/confirm.json
Mystore/Seller App Grocery/FLOW3/init.json
Mystore/Seller App Grocery/FLOW3/on_confirm.json
Mystore/Seller App Grocery/FLOW3/on_init.json
Mystore/Seller App Grocery/FLOW3/on_select_out_of_stock.json
Mystore/Seller App Grocery/FLOW3/on_select_success.json
Mystore/Seller App Grocery/FLOW3/on_status.json
Mystore/Seller App Grocery/FLOW3/on_status_order_delivered.json
Mystore/Seller App Grocery/FLOW3/on_status_order_out_for_delivery.json
Mystore/Seller App Grocery/FLOW3/on_status_order_picked_up.json
Mystore/Seller App Grocery/FLOW3/select_out_of_stock.json
Mystore/Seller App Grocery/FLOW3/select_success.json
Mystore/Seller App Grocery/FLOW3/status.json
Mystore/Seller App/FLOW1/on_search_full_catalog.json
Mystore/Seller App/FLOW1/on_search_incremental.json
Mystore/Seller App/FLOW1/search_full_catalog.json
Mystore/Seller App/FLOW1/search_incremental.json

Mystore Fashion Flow 1 and Grocery Flow 3 logs as per complaince

Mystore Fashion Flow 1 and Grocery Flow 3 logs as per complaince

---

NDHGO/RET11/flow-1/on_search.json
NDHGO/RET11/flow-1/search.json
NDHGO/RET11/flow-2/confirm.json
NDHGO/RET11/flow-2/init.json
NDHGO/RET11/flow-2/on_confirm.json
NDHGO/RET11/flow-2/on_init.json
NDHGO/RET11/flow-2/on_select.json
NDHGO/RET11/flow-2/on_status-delivered.json
NDHGO/RET11/flow-2/on_status-packed.json
NDHGO/RET11/flow-2/on_status-pending.json
NDHGO/RET11/flow-2/on_status-picked.json
NDHGO/RET11/flow-2/on_status.json
NDHGO/RET11/flow-2/on_track.json
NDHGO/RET11/flow-2/select.json
NDHGO/RET11/flow-2/status.json
NDHGO/RET11/flow-2/track.json
NDHGO/RET11/flow-4/cancel.json
NDHGO/RET11/flow-4/confirm.json
NDHGO/RET11/flow-4/init.json
NDHGO/RET11/flow-4/on_cancel.json
NDHGO/RET11/flow-4/on_confirm.json
NDHGO/RET11/flow-4/on_init.json
NDHGO/RET11/flow-4/on_select.json
NDHGO/RET11/flow-4/on_status.json
NDHGO/RET11/flow-4/select.json

NDHGO - RET11 Log Issue Fixes 1

---

Mystore/Seller App Grocery/FLOW3/confirm.json
Mystore/Seller App Grocery/FLOW3/init.json
Mystore/Seller App Grocery/FLOW3/on_confirm.json
Mystore/Seller App Grocery/FLOW3/on_init.json
Mystore/Seller App Grocery/FLOW3/on_select.json
Mystore/Seller App Grocery/FLOW3/on_select_out_of_stock.json
Mystore/Seller App Grocery/FLOW3/on_status.json
Mystore/Seller App Grocery/FLOW3/on_status_order_delivered.json
Mystore/Seller App Grocery/FLOW3/on_status_order_out_for_delivery.json
Mystore/Seller App Grocery/FLOW3/on_status_order_picked_up.json
Mystore/Seller App Grocery/FLOW3/select.json
Mystore/Seller App Grocery/FLOW3/select_out_of_stock_items.json
Mystore/Seller App Grocery/FLOW3/status.json

Mystore Flow 3 (Grocery) as per complaince check

Mystore Flow 3 as per complaince check

---

CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/Flow 1/full_catalog_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/Flow 1/full_catalog_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/Flow 1/incremental_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/BPC/Flow 1/incremental_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/Flow 1/full_catalog_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/Flow 1/full_catalog_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/Flow 1/incremental_on_search.json
CSC/v2 seller with buyer-app-preprod-v2.ondc.org/Home & Kitchen/Flow 1/incremental_search.json

BPC, Home & Kitchen logs Updates

BPC, Home & Kitchen logs Updates

---

Paytm/GV2.0.0/GV_IGM_LOGS/Fulfilment Flow /close.json
Paytm/GV2.0.0/GV_IGM_LOGS/Fulfilment Flow /issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Fulfilment Flow /on_issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Fulfilment Flow /on_issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/close.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/on_issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Item flow/on_issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/close.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/issue_status.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/on_issue.json
Paytm/GV2.0.0/GV_IGM_LOGS/Payment Flow/on_issue_status.json

Updated logs with location change specially for GV for IGM.

Adding Logs for IGM GV

---

Tipplr/Tipplr - IGM - updated(Mar-28)/flow-1/1_issue(open).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-1/2_on_issue(processing).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-1/3_issue_status.json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-1/4_on_issue_status(processing).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-1/5_on_issue_status(refund).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-1/6_issue(closed).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-2/1_issue(open).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-2/2_on_issue(processing).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-2/3_issue_status.json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-2/4_on_issue_status(processing).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-2/5_on_issue_status(refund).json
Tipplr/Tipplr - IGM - updated(Mar-28)/flow-2/6_issue(closed).json
Tipplr/Tipplr - IGM - updated(Mar-28)/readme.md

Hi @sandeepshahi 
Was able to raise pr with out modifying logs of other NP's. Please accept my PR.
Thank you.

Tipplr SA -Updated IGM logs as per compliance

---

DeHaat/seller-app/28-03-2024/flow 3/1.1.select.json
DeHaat/seller-app/28-03-2024/flow 3/1.2.on_select.json
DeHaat/seller-app/28-03-2024/flow 3/10.on_status(In-progress, Order-picked-up).json
DeHaat/seller-app/28-03-2024/flow 3/11.on_status(In-progress, out-for-delivery).json
DeHaat/seller-app/28-03-2024/flow 3/12.on_status(Completed, Delivered).json
DeHaat/seller-app/28-03-2024/flow 3/2.1.select.json
DeHaat/seller-app/28-03-2024/flow 3/2.2.on_select.json
DeHaat/seller-app/28-03-2024/flow 3/3.init.json
DeHaat/seller-app/28-03-2024/flow 3/4.on_init.json
DeHaat/seller-app/28-03-2024/flow 3/5.confirm.json
DeHaat/seller-app/28-03-2024/flow 3/6.on_confirm.json
DeHaat/seller-app/28-03-2024/flow 3/7.on_status(Accepted).json
DeHaat/seller-app/28-03-2024/flow 3/8.on_status(Packed).json
DeHaat/seller-app/28-03-2024/flow 3/9.on_status(In-progress, Agent-assigned).json

https://github.com/ONDC-Official/v1.2.0-logs/issues/570\#issuecomment-2014699809

 Fix issues reported in dehaat seller and buyer app logs

---

Mystore/Buyer App logs v.12.0/Appliances/FLOW1/on_search_full_catalog.json
Mystore/Buyer App logs v.12.0/Appliances/FLOW1/search_full_catalog.json
Mystore/Buyer App logs v.12.0/BPC/FLOW1/on_search_full_catalog.json
Mystore/Buyer App logs v.12.0/BPC/FLOW1/search_full_catalog.json
Mystore/Buyer App logs v.12.0/Electronics/FLOW1/on_search_full_catalog.json
Mystore/Buyer App logs v.12.0/Electronics/FLOW1/search_full_catalog.json
Mystore/Buyer App logs v.12.0/Health and Wellness/FLOW1/on_search_full_catalog.json
Mystore/Buyer App logs v.12.0/Health and Wellness/FLOW1/search_full_catalog.json
Mystore/Buyer App logs v.12.0/Home & Decor/FLOW1/on_search_full_catalog.json
Mystore/Buyer App logs v.12.0/Home & Decor/FLOW1/search_full_catalog.json

Buyer app logs Flow 1 Full search for all supporting categories

Mystore Buyer app logs Flow 1 

---

Gofrugal/RSP/Flow 1 Successfull/on_receiver_recon.json
Gofrugal/RSP/Flow 1 Successfull/receiver_recon.json
Gofrugal/RSP/Flow 2 Correction/on_receiver_recon.json
Gofrugal/RSP/Flow 2 Correction/receiver_recon.json
Gofrugal/RSP/Settle log/on_settle.json
Gofrugal/RSP/Settle log/settle.json

Hi @sandeepshahi  
Here, I have submitted the logs for the RSP Receiver Flow and Settlement logs. Please verify and update accordingly.

RSP_Receiver log submission

---

Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 1/issue (Closed by Buyer app).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 1/issue.json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 1/issue_status.json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 1/on_issue.json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 1/on_issue_status (Resolved - Unsolicited).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 1/on_issue_status (Solicited).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/issue (Cascaded to LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/issue (Closed by buyer app).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/issue.json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/issue_status (Request to LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/issue_status.json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/on_issue (Processing from LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/on_issue.json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/on_issue_status (Processing - Unsolited response from LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/on_issue_status (Resolved - Unsolicited response to Buyer).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/on_issue_status (Resolved - Unsolited response from LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 2/on_issue_status (Solicited response from LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/issue (Cascaded to LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/issue (Closed - forwrded to LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/issue (Closed by buyer app).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/issue.json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/issue_status (Request forwarded to LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/issue_status.json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/on_issue (Processing - Solicited response from LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/on_issue (Processing - from Seller).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/on_issue_status (Added own resolution - Unsolicited response from Seller).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/on_issue_status (Processing - Solicited response from LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/on_issue_status (Processing - Unsolicited response from LSP).json
Unizap/unizap-logistics-v1.2-logs/IGM_logs/Flow 3/on_issue_status (Resolved - Unsolicited response from LSP).json

Submitting the IGM logs from Unizap, is a retail seller acting as a logistics buyer.

Submitting the IGM logs from Unizap, is a retail seller acting as a logistics buyer.

---

Mystore/Buyer App logs v.12.0/Appliances/FLOW1/on_search_full_catalog.json
Mystore/Buyer App logs v.12.0/Appliances/FLOW1/search_full_catalog.json
Mystore/Buyer App logs v.12.0/Electronics/FLOW1/on_search_full_catalog.json
Mystore/Buyer App logs v.12.0/Electronics/FLOW1/search_full_catalog.json
Mystore/Buyer App logs v.12.0/Health and Wellness/FLOW1/on_search_full_catalog.json
Mystore/Buyer App logs v.12.0/Health and Wellness/FLOW1/search_full_catalog.json

Mystore Buyer App Flow1 (RET15 RET18)

Mystore Buyer App Flow1 (RET15 RET18 RET14)

---

Addble/ONDC-RET10/Flow 1/on_search.json
Addble/ONDC-RET10/Flow 1/on_search_inc.json
Addble/ONDC-RET10/Flow 1/search.json
Addble/ONDC-RET10/Flow 1/search_inc.json
Addble/ONDC-RET10/Flow 2/confirm.json
Addble/ONDC-RET10/Flow 2/init.json
Addble/ONDC-RET10/Flow 2/on_confirm.json
Addble/ONDC-RET10/Flow 2/on_init.json
Addble/ONDC-RET10/Flow 2/on_select.json
Addble/ONDC-RET10/Flow 2/on_status_delivered.json
Addble/ONDC-RET10/Flow 2/on_status_out_for_delivery.json
Addble/ONDC-RET10/Flow 2/on_status_packed.json
Addble/ONDC-RET10/Flow 2/on_status_picked.json
Addble/ONDC-RET10/Flow 2/select.json
Addble/ONDC-RET10/Flow 3/confirm.json
Addble/ONDC-RET10/Flow 3/init.json
Addble/ONDC-RET10/Flow 3/on_confirm.json
Addble/ONDC-RET10/Flow 3/on_init.json
Addble/ONDC-RET10/Flow 3/on_select.json
Addble/ONDC-RET10/Flow 3/on_select_error.json
Addble/ONDC-RET10/Flow 3/on_status_delivered.json
Addble/ONDC-RET10/Flow 3/on_status_out_for_delivery.json
Addble/ONDC-RET10/Flow 3/on_status_packed.json
Addble/ONDC-RET10/Flow 3/on_status_picked.json
Addble/ONDC-RET10/Flow 3/select.json
Addble/ONDC-RET10/Flow 3/select_error.json

Submitting verification logs for Flow 1, Flow and Flow 3. 
Flow  4 and Flow 5 to follow.

Addble verification logs - RET10 - Flow 1 to Flow 3

---

ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/confirm.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/init.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_cancel.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_confirm.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_init.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_select.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_status_cancelled.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_status_order_picked_up.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_status_out_for_delivery.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_status_packed.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/on_status_pending.json
ShopEG/With buyer-app-preprod-v2.ondc.org/Group B/Flow 5/select.json

Resubmission of Flow 5 for adding on_init MSN and provider_tax_number in on_init order.tags
@BLR-0118 @sandeepshahi 
#92

ShopEG - Flow 5 resubmission

---

Mystore/SellerAppFlow1/Appliances/on_search.json
Mystore/SellerAppFlow1/Appliances/search.json
Mystore/SellerAppFlow1/BPC/on_search.json
Mystore/SellerAppFlow1/BPC/search.json
Mystore/SellerAppFlow1/Electronics/on_search.json
Mystore/SellerAppFlow1/Electronics/search.json
Mystore/SellerAppFlow1/Health and Wellness/on_search.json
Mystore/SellerAppFlow1/Health and Wellness/search.json

Mystore Flow 1 seller app(RET13,RET14,RET15 ,RET18)

Mystore Flow 1 seller app(RET13,RET14,RET15 ,RET18)

---

Thrive/flow_1/flow_1.json
Thrive/flow_4/cancel..json
Thrive/flow_4/confirm.json
Thrive/flow_4/flow_4.json
Thrive/flow_4/init.json
Thrive/flow_4/on_cancel.json
Thrive/flow_4/on_confirm.json
Thrive/flow_4/on_init.json
Thrive/flow_4/on_select.json
Thrive/flow_4/select.json
Thrive/flow_5/confirm.json
Thrive/flow_5/flow_5.json
Thrive/flow_5/init.json
Thrive/flow_5/on_cancel.json
Thrive/flow_5/on_confirm.json
Thrive/flow_5/on_init.json
Thrive/flow_5/on_select.json
Thrive/flow_5/on_status_out_for_delivery.json
Thrive/flow_5/on_status_packed.json
Thrive/flow_5/on_status_pending.json
Thrive/flow_5/on_status_picked.json
Thrive/flow_5/select.json

Updated the log to include recommended changes.

Updates Changes as mentioned in the issue - 1144

---

nStore/Retail Seller App/RET Catalogs/RET11.json
nStore/Retail Seller App/RET Catalogs/RET12.json
nStore/Retail Seller App/RET Catalogs/RET13.json
nStore/Retail Seller App/RET Catalogs/RET15.json
nStore/Retail Seller App/RET Catalogs/RET16.json
nStore/Retail Seller App/RET Catalogs/RET18.json

nStore Retail Catalog - 11 APR 2024

nStore Retail Catalog - 11 APR 2024

---

Channelier/RET:13/Flow 1/on_search_full_catalog_refresh.json
Channelier/RET:13/Flow 1/on_search_incremental_catalog_refresh.json
Channelier/RET:13/Flow 1/search_full_catalog_refresh.json
Channelier/RET:13/Flow 1/search_incremental_catalog_refresh.json

updated logs for channelier ONDC Retail 

---

SellerSetu/igm/Flow 2/5. issue_status(BUYER to SELLER).json
SellerSetu/igm/Flow 2/7. on_issue_status(LOGISTICS to SELLER-RESOLVED).json
SellerSetu/igm/Flow 2/8. on_issue_status(SELLER to BUYER).json
SellerSetu/igm/Flow 3/6. issue_status(SELLER to LOGISTICS).json
SellerSetu/igm/Flow 3/7. on_issue_status(LOGISTICS to SELLER-RESOLVED).json
SellerSetu/igm/Flow 3/8. on_issue_status(SELLER to BUYER - Seller provides its resolution).json

sellersetu_igm: corrected flow 2 and 3

---

NDHGO/RET16/flow-1/inc-on_search.json
NDHGO/RET16/flow-1/on_search.json
NDHGO/RET16/flow-1/search.json
NDHGO/RET16/flow-1/validation-report.json

Addressed Issues mentioned in: #1395

NDHGO - RET16 Log Issue Fixes 1

---

NDHGO/RET11/flow-1/on_search.json
NDHGO/RET11/flow-1/search.json

NDHGO MSN - RET11 Log Issue Fixes 3

---

Krenai_Retail/Retail_16/Flow1/incremental_search.json
Krenai_Retail/Retail_16/Flow1/on_incremental_search.json
Krenai_Retail/Retail_16/Flow1/on_search.json
Krenai_Retail/Retail_16/Flow1/search.json

flow 1 added fro RET16

---

Mystore/Seller App/FLOW6(returnpicked)/confirm.json
Mystore/Seller App/FLOW6(returnpicked)/init.json
Mystore/Seller App/FLOW6(returnpicked)/on_confirm.json
Mystore/Seller App/FLOW6(returnpicked)/on_init.json
Mystore/Seller App/FLOW6(returnpicked)/on_select.json
Mystore/Seller App/FLOW6(returnpicked)/on_status.json
Mystore/Seller App/FLOW6(returnpicked)/on_status_order_delivered.json
Mystore/Seller App/FLOW6(returnpicked)/on_status_order_picked_up.json
Mystore/Seller App/FLOW6(returnpicked)/on_update_return_approved.json
Mystore/Seller App/FLOW6(returnpicked)/on_update_return_delivered.json
Mystore/Seller App/FLOW6(returnpicked)/on_update_return_initiated.json
Mystore/Seller App/FLOW6(returnpicked)/on_update_return_picked.json
Mystore/Seller App/FLOW6(returnpicked)/select.json
Mystore/Seller App/FLOW6(returnpicked)/status.json
Mystore/Seller App/FLOW6(returnpicked)/update.json
Mystore/Seller App/FLOW6(returnpicked)/update_settlement.json
Mystore/SellerAppFlow1/Appliances/on_search.json
Mystore/SellerAppFlow1/Appliances/search.json
Mystore/SellerAppFlow1/Electronics/on_search.json
Mystore/SellerAppFlow1/Electronics/search.json
Mystore/SellerAppFlow1/Health and Wellness/on_search.json
Mystore/SellerAppFlow1/Health and Wellness/search.json

Mystore Seller App Flow 1 RET14,RET15 ,RET18,FLOW6b and FLOW6c

Mystore Seller App complaince check issues

---

NDHGO/RET13/flow-1/on_search.json
NDHGO/RET13/flow-1/search.json
NDHGO/RET16/flow-1/on_search.json
NDHGO/RET16/flow-1/search.json

NDHGO MSN - RET13 / RET16 Log Issue Fixes

---

Mappls-Buyer-App/IGM/Flow1/On_issue_status_unsolicitated call.json
Mappls-Buyer-App/IGM/Flow1/issue_closed.json

One File was wrongly added under different title , which got rectified now

Updated IGM logs based on the feedback

---

NDHGO/RET11/flow-1/on_search.json
NDHGO/RET11/flow-1/search.json

NDHGO MSN - RET11 Log Issue Fixes 4

---

Gofrugal/RSP/Flow 1 Successfull/on_receiver_recon.json
Gofrugal/RSP/Flow 1 Successfull/receiver_recon.json
Gofrugal/RSP/Flow 2 Correction/on_receiver_recon.json
Gofrugal/RSP/Flow 2 Correction/receiver_recon.json

Hi @sandeepshahi Based on the feedback, we have updated the changes and resubmitted the RSF Receiver logs. Kindly verify them.

Gofrugal RSF log resubmission for the receiver part based on feedback.

---

Sabhyasha/Logistics/Flow 1(Happy flow)/1. search.json
Sabhyasha/Logistics/Flow 1(Happy flow)/10. on_status_order_pickedup.json
Sabhyasha/Logistics/Flow 1(Happy flow)/11. on_status_out_for_delivery.json
Sabhyasha/Logistics/Flow 1(Happy flow)/12. on_status_order_delivered.json
Sabhyasha/Logistics/Flow 1(Happy flow)/2. on_search.json
Sabhyasha/Logistics/Flow 1(Happy flow)/3. init.json
Sabhyasha/Logistics/Flow 1(Happy flow)/4. on_init.json
Sabhyasha/Logistics/Flow 1(Happy flow)/5. confirm.json
Sabhyasha/Logistics/Flow 1(Happy flow)/6. on_confirm.json
Sabhyasha/Logistics/Flow 1(Happy flow)/7. update.json
Sabhyasha/Logistics/Flow 1(Happy flow)/8. on_update.json
Sabhyasha/Logistics/Flow 1(Happy flow)/9. on_status_agent_assigned.json
Sabhyasha/Logistics/Flow 3(TAT Breach flow)/1. search.json
Sabhyasha/Logistics/Flow 3(TAT Breach flow)/2. on_search.json
Sabhyasha/Logistics/Flow 3(TAT Breach flow)/3. init.json
Sabhyasha/Logistics/Flow 3(TAT Breach flow)/4. on_init.json
Sabhyasha/Logistics/Flow 3(TAT Breach flow)/5. confirm.json
Sabhyasha/Logistics/Flow 3(TAT Breach flow)/6. on_confirm.json
Sabhyasha/Logistics/Flow 3(TAT Breach flow)/7. cancel.json
Sabhyasha/Logistics/Flow 3(TAT Breach flow)/8. on_cancel.json

- Changed pincode for search and init calls
- Changed TAT breach cancellation reason id

Changes made as per the feedback on FLow 1 and 3

---

Addble/ONDC-AGR10/Flow 1/on_search.json
Addble/ONDC-AGR10/Flow 1/on_search_inc.json
Addble/ONDC-AGR10/Flow 1/search.json
Addble/ONDC-AGR10/Flow 1/search_inc.json

Addble- verification log files for ONDC:AGR10

---

Mystore/Seller App/FLOW6(returnpicked)/confirm.json
Mystore/Seller App/FLOW6(returnpicked)/init.json
Mystore/Seller App/FLOW6(returnpicked)/on_confirm.json
Mystore/Seller App/FLOW6(returnpicked)/on_init.json
Mystore/Seller App/FLOW6(returnpicked)/on_select.json
Mystore/Seller App/FLOW6(returnpicked)/on_status.json
Mystore/Seller App/FLOW6(returnpicked)/on_status_order_delivered.json
Mystore/Seller App/FLOW6(returnpicked)/on_status_order_picked_up.json
Mystore/Seller App/FLOW6(returnpicked)/on_update_return_approved.json
Mystore/Seller App/FLOW6(returnpicked)/on_update_return_delivered.json
Mystore/Seller App/FLOW6(returnpicked)/on_update_return_initiated.json
Mystore/Seller App/FLOW6(returnpicked)/on_update_return_picked.json
Mystore/Seller App/FLOW6(returnpicked)/select.json
Mystore/Seller App/FLOW6(returnpicked)/status.json
Mystore/Seller App/FLOW6(returnpicked)/update.json
Mystore/Seller App/FLOW6(returnpicked)/update_settlement.json

Mystore Flow6c as per complaince check

Mystore Flow6c as per complaince check

---

NDHGO/RET13/flow-1/inc-on_search.json
NDHGO/RET13/flow-1/inc-search.json
NDHGO/RET13/flow-1/on_search.json
NDHGO/RET13/flow-1/search.json
NDHGO/RET16/flow-1/inc-on_search.json
NDHGO/RET16/flow-1/inc-search.json
NDHGO/RET16/flow-1/on_search.json
NDHGO/RET16/flow-1/search.json

NDHGO MSN - RET13 / RET16 Log Issue Fixes 1

---

ShiSellerApp/BPC/Flow 1/on_search_full_catalog.json
ShiSellerApp/BPC/Flow 1/on_search_inc_refresh.json
ShiSellerApp/BPC/Flow 1/search_full_catalog.json
ShiSellerApp/BPC/Flow 1/search_inc_refresh.json
ShiSellerApp/BPC/Flow 1/util_request_body.json
ShiSellerApp/BPC/Flow 1/util_response.json

BPC -Flow 1

---

Easy Pay/BuyerApp/Flow-6/3.buyer return reverse QC flow/update.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_issue.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_issue_close.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_issue_status.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_on_issue.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_on_issue_status.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_on_issue_status_unsolicited.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_issue.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_issue_close.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_issue_status.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_on_issue.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_on_issue_status.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_on_issue_status_unsolicited.json

BuyerApp IGM Logs & reverse QC logs update json which we missed in previous PR

BuyerApp IGM Logs & reverse QC logs update json

---

Futuresoft/RSF/on_receiver_recon_1.json
Futuresoft/RSF/receiver_recon_1.json

RSF logs issue resolved

---

Mystore/SellerAppFlow1/AGRI/incremental_on_search.json
Mystore/SellerAppFlow1/AGRI/incremental_search.json
Mystore/SellerAppFlow1/AGRI/on_search.json
Mystore/SellerAppFlow1/AGRI/search.json
Mystore/SellerAppFlow1/AUTO/incremental_on_search.json
Mystore/SellerAppFlow1/AUTO/incremental_search.json
Mystore/SellerAppFlow1/AUTO/on_search.json
Mystore/SellerAppFlow1/AUTO/search.json

Mystore FLOW1 AGR10 and RET1A logs

Mystore FLOW1 AGR10 and RET1A

---

UniStack/RSF/flow1/on_receiver_recon.json
UniStack/RSF/flow1/receiver_recon.json
UniStack/RSF/flow2/correction_flow/on_receiver_recon.json
UniStack/RSF/flow2/correction_flow/receiver_recon.json
UniStack/RSF/flow2/normal_flow/on_receiver_recon.json
UniStack/RSF/flow2/normal_flow/receiver_recon.json

This was tested against our RSP in staging enviroment

Unistack RSF logs

---

Easy Pay/BuyerApp/RSF/Flow -2 Correction/on_receiver_recon.json
Easy Pay/BuyerApp/RSF/Flow -2 Correction/receiver_recon.json
Easy Pay/BuyerApp/RSF/Flow-1 Success/on_receiver_recon.json
Easy Pay/BuyerApp/RSF/Flow-1 Success/receiver_recon.json

EasyPay BuyerApp RSF logs added

EasyPay BuyerApp RSF logs added

---

QWQER/Logistics/Group B/Cancel (RTO-No)/confirm.json
QWQER/Logistics/Group B/Cancel (RTO-No)/init.json
QWQER/Logistics/Group B/Cancel (RTO-No)/on_cancel_RTO_dispose.json
QWQER/Logistics/Group B/Cancel (RTO-No)/on_confirm.json
QWQER/Logistics/Group B/Cancel (RTO-No)/on_init.json
QWQER/Logistics/Group B/Cancel (RTO-No)/on_search.json
QWQER/Logistics/Group B/Cancel (RTO-No)/on_status_RTO-Disposed.json
QWQER/Logistics/Group B/Cancel (RTO-No)/on_status_agent_assigned.json
QWQER/Logistics/Group B/Cancel (RTO-No)/on_status_picked_up.json
QWQER/Logistics/Group B/Cancel (RTO-No)/on_track.json
QWQER/Logistics/Group B/Cancel (RTO-No)/search.json
QWQER/Logistics/Group B/Cancel (RTO-No)/track.json

the start/end location [issue](https://github.com/ONDC-Official/v1.2.0-logs/issues/1196#issuecomment-2107306531) in RTO fulfillment is fixed.
@BLR-0118 @abhinavv245 @sandeepshahi

Updated RTO workflow logs

---

Easy Pay/BuyerApp/IGM/Flow-1/ret_issue.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_issue_close.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_issue_status.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_on_issue.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_on_issue_status.json
Easy Pay/BuyerApp/IGM/Flow-1/ret_on_issue_status_unsolicited.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_issue.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_issue_close.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_issue_status.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_on_issue.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_on_issue_status.json
Easy Pay/BuyerApp/IGM/Flow-2/ret_on_issue_status_unsolicited.json
Easy Pay/BuyerApp/RSF/Flow -2 Correction/on_receiver_recon.json
Easy Pay/BuyerApp/RSF/Flow -2 Correction/receiver_recon.json
Easy Pay/BuyerApp/RSF/Flow-1 Success/on_receiver_recon.json
Easy Pay/BuyerApp/RSF/Flow-1 Success/receiver_recon.json

Easy Pay Buyer App IGM & RSF logs update as per compliance observations

IGM & RSF logs update as per compliance observations - Buyer App

---

SellerSetu/rsf/correction flow/on_receiver_recon.json
SellerSetu/rsf/correction flow/receiver_recon.json
SellerSetu/rsf/success flow/on_receiver_recon.json
SellerSetu/rsf/success flow/receiver_recon.json

sellersetu_rsf: rsf compliance check

---

Mystore/SellerAppFlow1/AGRI/on_search.json
Mystore/SellerAppFlow1/AGRI/search.json

Mystore AGRI logs

---

eComviser/IGM/igm_validate_report.json
eComviser/IGM/igm_validate_request.json
eComviser/IGM/on_issue_status_unsolicited.json

fixed reported issue
https://github.com/ONDC-Official/v1.2.0-logs/issues/1587#issuecomment-2117342665

IGM reported issue fixed

---

Addble/ONDC-RET12/Flow 1/on_search.json
Addble/ONDC-RET12/Flow 1/search.json
Addble/ONDC-RET13/Flow 1/on_search.json
Addble/ONDC-RET13/Flow 1/on_search_inc.json
Addble/ONDC-RET13/Flow 1/search.json
Addble/ONDC-RET13/Flow 1/search_inc.json
Addble/ONDC-RET16/Flow 1/on_search.json
Addble/ONDC-RET16/Flow 1/on_search_inc.json
Addble/ONDC-RET16/Flow 1/search.json
Addble/ONDC-RET16/Flow 1/search_inc.json

Fixes for comments in #1653
@sandeepshahi - Please review

Addble - Fix for RET12, RET13 and RET16 review comments

---

eComviser/IGM/igm_validate_report.json
eComviser/IGM/igm_validate_request.json
eComviser/IGM/issue.json
eComviser/IGM/issue_close.json
eComviser/IGM/issue_status.json
eComviser/IGM/on_issue.json
eComviser/IGM/on_issue_status.json
eComviser/IGM/on_issue_status_unsolicited.json

Fixed this 
https://github.com/ONDC-Official/v1.2.0-logs/issues/1658
Also, one validation error 
"report": {
"ret_issue": {
"respTime": "Time of creation (created_at) and time of updation for /issue api should be the same"
}
},
issue response is generated from buyer app, https://buyer-app-preprod-v2.ondc.org/application/products where timestamp and created_add is different, it's not from our side.

fixed IGM issue

---

Mystore/SellerAppFlow1/AGRI/on_search.json
Mystore/SellerAppFlow1/AGRI/search.json
Mystore/SellerAppFlow1/AUTO/incremental_on_search.json
Mystore/SellerAppFlow1/AUTO/incremental_search.json
Mystore/SellerAppFlow1/AUTO/on_search.json
Mystore/SellerAppFlow1/AUTO/search.json

Mystore AGRI and AUTO logs as per complaince check

Mystore AGRI and AUTO logs

---

COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-22ndMay/1-search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-22ndMay/2-on_search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-22ndMay/3-incremental-search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-22ndMay/4-incremental-on_search.json
COSTBO/retail-RET18-healthandwellness/Flow1-28May/incr_onsearch.json
COSTBO/retail-RET18-healthandwellness/Flow1-28May/incr_search.json
COSTBO/retail-RET18-healthandwellness/Flow1-28May/onSearch.json
COSTBO/retail-RET18-healthandwellness/Flow1-28May/search.json
COSTBO/retail-RET18-healthandwellness/Flow1/1-search.json
COSTBO/retail-RET18-healthandwellness/Flow1/2-on_search.json
COSTBO/retail-RET18-healthandwellness/Flow1/3-incremental-search.json
COSTBO/retail-RET18-healthandwellness/Flow1/4-incremental-on_search.json

RET15 logs  for flow 1. =>. verified by certification / sumasoft team.  Need ONDC side approval.
RET18 logs for Flow 1. =>. Submitting for verification.  (As a seller MSN,  its a common code for us).

COSTBO RET15 and RET18 logs submission -Flow1

---

Mystore/SellerAppFlow1/AGRI/incremental_on_search.json
Mystore/SellerAppFlow1/AGRI/incremental_search.json
Mystore/SellerAppFlow1/AGRI/on_search.json
Mystore/SellerAppFlow1/AGRI/search.json
Mystore/SellerAppFlow1/AUTO/incremental_on_search.json
Mystore/SellerAppFlow1/AUTO/incremental_search.json
Mystore/SellerAppFlow1/AUTO/on_search.json
Mystore/SellerAppFlow1/AUTO/search.json

Mystore Logs as per complaince check (AGRI and AUTO)

Mystore Logs as per complaince check

---

COSTBO/retail-RET14/Flow1-30May/1-search.json
COSTBO/retail-RET14/Flow1-30May/2-on_search.json
COSTBO/retail-RET14/Flow1-30May/3-incremental-search.json
COSTBO/retail-RET14/Flow1-30May/4-incremental-on-search.json
COSTBO/retail-RET18-healthandwellness/Flow1-28May/onSearch-updated.json
COSTBO/retail-RET18-healthandwellness/Flow1-28May/search-updated.json

This push has the verified fixes from sumasoft for flow1-RET18.  
file names:   onsearch-updated. & search-updated.  {{reference}}

RET18-Flow1-search-onsearch-with-updates

---

Zyro Seller Process Logs/IGM/Flow1/issue.json
Zyro Seller Process Logs/IGM/Flow1/issue_status.json
Zyro Seller Process Logs/IGM/Flow1/on_issue.json
Zyro Seller Process Logs/IGM/Flow1/on_issue_status.json
Zyro Seller Process Logs/IGM/Flow2/issue.json
Zyro Seller Process Logs/IGM/Flow2/issue_status.json
Zyro Seller Process Logs/IGM/Flow2/on_issue.json
Zyro Seller Process Logs/IGM/Flow2/on_issue_status.json
Zyro Seller Process Logs/RSF/Flow1/on_receiver_recon.json
Zyro Seller Process Logs/RSF/Flow1/receiver_recon.json
Zyro Seller Process Logs/RSF/Flow2/on_receiver_recon.json
Zyro Seller Process Logs/RSF/Flow2/receiver_recon.json

IGM and RSF all flow logs have been added. 
@sandeepshahi  Please review.

IGM and RSF all flow logs have been added

---

COSTBO/retail-RET14/RET14-Electronics-flow1-1-Jun-24/1-search.json
COSTBO/retail-RET14/RET14-Electronics-flow1-1-Jun-24/2-on_search.json
COSTBO/retail-RET14/RET14-Electronics-flow1-1-Jun-24/3-incremental-search.json
COSTBO/retail-RET14/RET14-Electronics-flow1-1-Jun-24/4-incremental-on_search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-flow1-1-Jun-24/1-search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-flow1-1-Jun-24/2-on_search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-flow1-1-Jun-24/3-incremental-search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-flow1-1-Jun-24/4-incremental-on_search.json
COSTBO/retail-RET18-healthandwellness/RET18-Health-And-Wellness-flow1-1-Jun-24/1-search.json
COSTBO/retail-RET18-healthandwellness/RET18-Health-And-Wellness-flow1-1-Jun-24/2-on_search.json
COSTBO/retail-RET18-healthandwellness/RET18-Health-And-Wellness-flow1-1-Jun-24/3-incremental-search.json
COSTBO/retail-RET18-healthandwellness/RET18-Health-And-Wellness-flow1-1-Jun-24/4-incremental-on_search.json

COSTBO fixes included for Store-Pick under tags>timing.  
Flow 1 >  RET14, RET15, RET18

COSTBO fixes included for Store-Pick under tags>timing. RET14, RET15, RET18

---

Zyro Seller Process Logs/IGM/Flow1/issue.json
Zyro Seller Process Logs/IGM/Flow1/issue_status.json
Zyro Seller Process Logs/IGM/Flow1/on_issue.json
Zyro Seller Process Logs/IGM/Flow1/on_issue_status.json
Zyro Seller Process Logs/IGM/Flow2/issue.json
Zyro Seller Process Logs/IGM/Flow2/issue_status.json
Zyro Seller Process Logs/IGM/Flow2/on_issue.json
Zyro Seller Process Logs/IGM/Flow2/on_issue_status.json

IGM Process logs updated and issues resolved.

IGM Process logs updated

---

COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-4-Jun-24/1-search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-4-Jun-24/2-on_search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-4-Jun-24/3-incremental-search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-4-Jun-24/4-incremental-on_search.json

COSTBOO RET15 - Appliance - review completed

COSTBOO RET15 - Appliance - review completed

---

Aurikatech/IGM/FLOW 1/issue.json
Aurikatech/IGM/FLOW 1/issue_close.json
Aurikatech/IGM/FLOW 1/issue_status.json
Aurikatech/IGM/FLOW 1/on_issue.json
Aurikatech/IGM/FLOW 1/on_issue_status.json
Aurikatech/IGM/FLOW 1/on_issue_status_unsoliciated.json
Aurikatech/IGM/FLOW 1/readme.md
Aurikatech/IGM/FLOW 2/issue.json
Aurikatech/IGM/FLOW 2/issue_close.json
Aurikatech/IGM/FLOW 2/issue_status.json
Aurikatech/IGM/FLOW 2/on_issue.json
Aurikatech/IGM/FLOW 2/on_issue_status.json
Aurikatech/IGM/FLOW 2/on_issue_status_unsoliciated.json
Aurikatech/IGM/FLOW 2/readme.ms

featAdded IGM flows

---

Mystore/SellerAppFlow1/AGRI/incremental_on_search.json
Mystore/SellerAppFlow1/AGRI/incremental_search.json

Mystore AGRI incremental logs

---

Gupshup/IGM/issueClosure.json
Gupshup/IGM/issueCreation.json
Gupshup/IGM/issueStatus.json
Gupshup/IGM/on_IssueClosure.json
Gupshup/IGM/on_IssueCreation.json
Gupshup/IGM/on_IssueStatus.json

In this pull request, we have added IGM logs

Gupshup Buyer App IGM logs

---

COSTBO/retail-RET14/RET14-Electonics-flow1-10Jun24/RET14-onsearch-final.json
COSTBO/retail-RET14/RET14-Electonics-flow1-10Jun24/RET14-search.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-10Jun24/RET15-Onsearch-final.json
COSTBO/retail-RET15-Appliances/RET15-Appliances-Flow1-10Jun24/RET15-search.json
COSTBO/retail-RET18-healthandwellness/RET18-HealthandWellness-Flow1-10Jun24/RET18-onsearch-final.json
COSTBO/retail-RET18-healthandwellness/RET18-HealthandWellness-Flow1-10Jun24/RET18-search.json

Final logs submission after review.

COSTBO RET14-15-18-search-onsearch-fixes

---

Mystore/SellerAppFlow1/AGRI/incremental_on_search.json
Mystore/SellerAppFlow1/AGRI/incremental_search.json
Mystore/SellerAppFlow1/AGRI/on_search.json
Mystore/SellerAppFlow1/AGRI/search.json
Mystore/SellerAppFlow1/AUTO/incremental_on_search.json
Mystore/SellerAppFlow1/AUTO/incremental_search.json
Mystore/SellerAppFlow1/AUTO/on_search.json
Mystore/SellerAppFlow1/AUTO/search.json

Mystore RET1A and AGR10 logs as per complaince

Mystore RET1A and AGR10 logs as per complaince

---

eComviser/IGM/Flow-1/igm_validate_report.json
eComviser/IGM/Flow-1/igm_validate_request.json
eComviser/IGM/Flow-1/issue.json
eComviser/IGM/Flow-1/issue_close.json
eComviser/IGM/Flow-1/issue_status.json
eComviser/IGM/Flow-1/on_issue.json
eComviser/IGM/Flow-1/on_issue_status.json
eComviser/IGM/Flow-1/on_issue_status_unsolicited.json

Fixed:
https://github.com/ONDC-Official/v1.2.0-logs/issues/1587#issuecomment-2154141406
https://github.com/ONDC-Official/v1.2.0-logs/issues/1587#issuecomment-2137174299

IGM issue fixed #1587

---

Easy Pay/SellerApp/RET-10/Flow 1/on_search_full_catalog_refresh.json
Easy Pay/SellerApp/RET-10/Flow 1/on_search_inc_refresh.json
Easy Pay/SellerApp/RET-10/Flow 1/search_full_catalog_refresh.json
Easy Pay/SellerApp/RET-10/Flow 1/search_inc_refresh.json

EasyPay Seller App RET 10 - Flow 1 logs update

EasyPay Seller App RET 10 - Flow 1 logs update

---

Gupshup/IGM/issueClosure_ItemMissing.json
Gupshup/IGM/issueCreation_ItemMissing.json
Gupshup/IGM/issueStatus_ItemMissing.json
Gupshup/IGM/on_IssueCreation.json
Gupshup/IGM/on_issueClosure_ItemMissing.json
Gupshup/IGM/on_issueCreation_ItemMissing.json
Gupshup/IGM/on_issueStatus_ItemMissing.json

We have updated the flow according to the suggestion. Also added Item_missing logs

Gupshup Buyer App : Modified IGM logs

---

Udyamwell/IGM/Flow2/lsp_issue.json
Udyamwell/IGM/Flow2/lsp_issue_close.json
Udyamwell/IGM/Flow2/lsp_issue_status.json
Udyamwell/IGM/Flow2/lsp_on_issue.json
Udyamwell/IGM/Flow2/lsp_on_issue_status_unsolicited.json
Udyamwell/IGM/Flow2/ret_issue.json
Udyamwell/IGM/Flow2/ret_issue_close.json
Udyamwell/IGM/Flow2/ret_issue_status.json
Udyamwell/IGM/Flow2/ret_on_issue.json
Udyamwell/IGM/Flow2/ret_on_issue_status.json
Udyamwell/IGM/Flow2/ret_on_issue_status_unsolicited.json

@sandeepshahi Please merge our this PR

Flow 2 Updated as per the feedback

---

Easy Pay/SellerApp/RET-10/Flow 1/on_search_full_catalog_refresh.json
Easy Pay/SellerApp/RET-10/Flow 1/on_search_inc_refresh.json
Easy Pay/SellerApp/RET-10/Flow 1/search_full_catalog_refresh.json
Easy Pay/SellerApp/RET-10/Flow 1/search_inc_refresh.json

Updated EasyPay Seller logs for Flow-1 with resolved observations

Updated EasyPay Seller logs for Flow-1 with resolved observations

---

1Bridge/ONDC:RET16/on_search.json
1Bridge/ONDC:RET16/on_search_inc.json
1Bridge/ONDC:RET16/search.json
1Bridge/ONDC:RET16/search_inc.json

Updated logs for 1Bridge ONDC:RET16

updated logs as per review feedback

---

ShopEG/With buyer-app-preprod-v2.ondc.org/RET-13/Group B/Flow 1/full_catalog_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/RET-13/Group B/Flow 1/full_catalog_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/RET-13/Group B/Flow 1/inc_on_search.json
ShopEG/With buyer-app-preprod-v2.ondc.org/RET-13/Group B/Flow 1/inc_search.json

ShopEG RET13 search logs

---

1Bridge/ONDC:RET16/on_search.json
1Bridge/ONDC:RET16/on_search_inc.json
1Bridge/ONDC:RET16/search.json
1Bridge/ONDC:RET16/search_inc.json

1Bridge RET16: updated logs as per review feedback

1Bridge RET16: updated logs as per review feedback

---

Zoho/IGM/Flow 1 -Item/ret_issue.json
Zoho/IGM/Flow 1 -Item/ret_issue_close.json
Zoho/IGM/Flow 1 -Item/ret_issue_status.json
Zoho/IGM/Flow 1 -Item/ret_on_issue.json
Zoho/IGM/Flow 1 -Item/ret_onissue_status.json
Zoho/IGM/Flow 1 -Item/ret_onissue_status_unsoliticited.json

Fixed [https://github.com/ONDC-Official/v1.2.0-logs/issues/1990](url)

Zoho IGM Compliance Fix 

---

foxyCoop/IGM/Flow1/ret_issue.json
foxyCoop/IGM/Flow1/ret_issue_close.json
foxyCoop/IGM/Flow1/ret_issue_status.json
foxyCoop/IGM/Flow1/ret_on_issue.json
foxyCoop/IGM/Flow1/ret_on_issue_status.json
foxyCoop/IGM/Flow1/ret_on_issue_status_unsolicited.json
foxyCoop/IGM/Flow2/ret_issue.json
foxyCoop/IGM/Flow2/ret_issue_close.json
foxyCoop/IGM/Flow2/ret_issue_status.json
foxyCoop/IGM/Flow2/ret_on_issue.json
foxyCoop/IGM/Flow2/ret_on_issue_status.json
foxyCoop/IGM/Flow2/ret_on_issue_status_unsolicited.json

foxyCoop (BA) IGM logs

---

1Bridge/ONDC:RET16/on_search.json
1Bridge/ONDC:RET16/on_search_inc.json
1Bridge/ONDC:RET16/search.json
1Bridge/ONDC:RET16/search_inc.json

Updated logs as per review feedback.

1Bridge: RET16 updated logs as per review feedback

---

COSTBO/retail-RET1A/Flow1-17thJune2024/incremental-onsearch.json
COSTBO/retail-RET1A/Flow1-17thJune2024/onsearch.json
COSTBO/retail-RET1A/Flow1-9thJuly2024/incremental-onsearch.json
COSTBO/retail-RET1A/Flow1-9thJuly2024/incremental-search.json
COSTBO/retail-RET1A/Flow1-9thJuly2024/onsearch.json
COSTBO/retail-RET1A/Flow1-9thJuly2024/search.json

COSTBO RET1A Flow1 logs

---

Easy Pay/SellerApp/RET-10/Flow 1/on_search_inc_refresh.json
Easy Pay/SellerApp/RET-10/Flow 1/search_inc_refresh.json

Resolved observation provided on 10 JULY,  For incremental search date issue - Easy Pay Seller NP  RET-10

EasyPay seller RET-10 ( Flow 1 - Incremental Search) update as per observation provided

---

Mystore/SellerAppFlow1/AUTO/incremental_on_search.json
Mystore/SellerAppFlow1/AUTO/incremental_search.json
Mystore/SellerAppFlow1/AUTO/on_search.json
Mystore/SellerAppFlow1/AUTO/search.json

Mystore AUTO logs buyer and seller

Mystore Auto logs

---

foxyCoop/IGM/Flow2/ret_issue.json
foxyCoop/IGM/Flow2/ret_issue_close.json
foxyCoop/IGM/Flow2/ret_issue_status.json
foxyCoop/IGM/Flow2/ret_on_issue.json
foxyCoop/IGM/Flow2/ret_on_issue_status.json
foxyCoop/IGM/Flow2/ret_on_issue_status_unsolicited.json

Updated as feedback received from CA. Please merge.

Updated as feedback received from CA

---

COSTBO/retail-RET12-Fashion/Flow1-Search-15thJuly/1-Search.json
COSTBO/retail-RET12-Fashion/Flow1-Search-15thJuly/2-on_search.json
COSTBO/retail-RET12-Fashion/Flow1-Search-15thJuly/3-incr-search.json
COSTBO/retail-RET12-Fashion/Flow1-Search-15thJuly/4-incr-on_search.json

COSTBO Ret12 Fashion

---

Mystore/SellerAppFlow1/AUTO/incremental_on_search.json
Mystore/SellerAppFlow1/AUTO/incremental_search.json
Mystore/SellerAppFlow1/AUTO/on_search.json
Mystore/SellerAppFlow1/AUTO/search.json

Mystore Logs as per complaince

Mystore RET1A Logs as per complaince

---

shopclues/seller-logs/RET14/FLOW-1/on_search_full_catalogue.json
shopclues/seller-logs/RET14/FLOW-1/on_search_incremental.json
shopclues/seller-logs/RET14/FLOW-1/search_full_catalogue.json
shopclues/seller-logs/RET14/FLOW-1/search_incremental.json
shopclues/seller-logs/RET16/FLOW-1/on_search_full_catalogue.json
shopclues/seller-logs/RET16/FLOW-1/on_search_incremental.json
shopclues/seller-logs/RET16/FLOW-1/search_full_catalogue.json
shopclues/seller-logs/RET16/FLOW-1/search_incremental.json

RET 14 and RET 16 flow1 
as discussed please check and approve

Shopclues RET14 and RET 16

---

NDHGO/RET15/flow-1/inc-on_search.json
NDHGO/RET15/flow-1/inc-search.json
NDHGO/RET15/flow-1/on_search.json
NDHGO/RET15/flow-1/search.json
NDHGO/RET15/flow-1/validation-report.json

Addresses Issues mentioned in #2129

NDHGO MSN - RET15 Logs Issue Fixes 1

---

NDHGO/RET15/flow-1/inc-on_search.json
NDHGO/RET15/flow-1/inc-search.json
NDHGO/RET15/flow-1/on_search.json
NDHGO/RET15/flow-1/search.json
NDHGO/RET15/flow-1/validation-report.json

NDHGO MSN - RET15 Logs Issue Fixes 2

---

SellerSetu/Retail-1.2/RET16/Flow1/on_search_full_catalog_refresh.json
SellerSetu/Retail-1.2/RET16/Flow1/search_full_catalog_refresh.json
SellerSetu/Retail-1.2/RET16/Flow1/utility_payload.json
SellerSetu/Retail-1.2/RET16/Flow1/utility_response.json
SellerSetu/Retail-1.2/RET16/Flow4/cancel.json
SellerSetu/Retail-1.2/RET16/Flow4/confirm.json
SellerSetu/Retail-1.2/RET16/Flow4/init.json
SellerSetu/Retail-1.2/RET16/Flow4/on_cancel.json
SellerSetu/Retail-1.2/RET16/Flow4/on_confirm.json
SellerSetu/Retail-1.2/RET16/Flow4/on_init.json
SellerSetu/Retail-1.2/RET16/Flow4/on_select.json
SellerSetu/Retail-1.2/RET16/Flow4/select.json
SellerSetu/Retail-1.2/RET16/Flow4/utility_payload.json
SellerSetu/Retail-1.2/RET16/Flow4/utility_response.json

Latest RET16 search

---

Easy Pay/SellerApp/RSF/Flow-1 Success/on_receiver_recon.json
Easy Pay/SellerApp/RSF/Flow-1 Success/receiver_recon.json
Easy Pay/SellerApp/RSF/Flow-2 Correction/on_receiver_recon.json
Easy Pay/SellerApp/RSF/Flow-2 Correction/receiver_recon.json

Easy Pay Seller NP - RSF Flow with at least 5 orders for both flows.

Easy Pay Seller NP - RSF Flow with at least 5 orders for both flows

---

NDHGO/RET14/flow-1/inc-on_search.json
NDHGO/RET14/flow-1/inc-search.json
NDHGO/RET14/flow-1/on_search.json
NDHGO/RET14/flow-1/search.json
NDHGO/RET14/flow-1/validation-report.json

Addressed issues mentioned in #2068

NDHGO MSN - RET14 Logs Issue Fixes 1

---

Buynxt_Greenreceipt/RET10-05_08_24/on_search.json
Buynxt_Greenreceipt/RET10-05_08_24/on_search_inc_catalog.json
Buynxt_Greenreceipt/RET10-05_08_24/on_search_inc_store_close.json
Buynxt_Greenreceipt/RET10-05_08_24/on_search_inc_store_disable.json
Buynxt_Greenreceipt/RET10-05_08_24/on_search_inc_store_open.json
Buynxt_Greenreceipt/RET10-05_08_24/search.json
Buynxt_Greenreceipt/RET10-05_08_24/search_inc_start.json
Buynxt_Greenreceipt/RET13-05_08_24/on_search.json
Buynxt_Greenreceipt/RET13-05_08_24/on_search_inc_store_close.json
Buynxt_Greenreceipt/RET13-05_08_24/on_search_inc_store_open.json
Buynxt_Greenreceipt/RET13-05_08_24/search.json
Buynxt_Greenreceipt/RET13-05_08_24/search_inc_start.json
Buynxt_Greenreceipt/RET16-05_08_24/on_search.json
Buynxt_Greenreceipt/RET16-05_08_24/on_search_inc_store_close.json
Buynxt_Greenreceipt/RET16-05_08_24/on_search_inc_store_open.json
Buynxt_Greenreceipt/RET16-05_08_24/search.json
Buynxt_Greenreceipt/RET16-05_08_24/search_inc_start.json

Added a Store Disable and OnsSearch Incremental Payload as well for RET:10 as asked.

RET-10,13,16 Flow 1 Logs For Review

---

DeHaat/RSF/08-08-2024/flow 1/1.receiver_recon(5 orders).json
DeHaat/RSF/08-08-2024/flow 1/2.on_receiver_recon(sucessful).json
DeHaat/RSF/08-08-2024/flow 2/1.receiver_recon(6 orders).json
DeHaat/RSF/08-08-2024/flow 2/2.on_receiver_recon(incorrect amount for 1 order).json
DeHaat/RSF/08-08-2024/flow 2/3.receiver_recon(corrected).json
DeHaat/RSF/08-08-2024/flow 2/4.on_receiver_recon.json

Resolve issues reported for rsf: https://github.com/ONDC-Official/v1.2.0-logs/issues/2111

---

Ninjacart/Retail/Retail_Buyer/Flow- 1/on_search.json
Ninjacart/Retail/Retail_Buyer/Flow- 1/on_search_increment.json
Ninjacart/Retail/Retail_Buyer/Flow- 1/search.json
Ninjacart/Retail/Retail_Buyer/Flow- 1/search_increment.json

Retail Buyer app logs

---

NDHGO/RET12/flow-1/inc-on_search.json
NDHGO/RET12/flow-1/inc-search.json
NDHGO/RET12/flow-1/on_search.json
NDHGO/RET12/flow-1/search.json
NDHGO/RET12/flow-1/validation-report.json

Addressed Issues mentioned in #2052

NDHGO MSN - RET12 Logs Issue Fixes 2

---

shopclues/seller-logs/RET14/FLOW-1/on_search_full_catalogue.json
shopclues/seller-logs/RET14/FLOW-1/on_search_incremental.json
shopclues/seller-logs/RET14/FLOW-1/search_full_catalogue.json
shopclues/seller-logs/RET14/FLOW-1/search_incremental.json
shopclues/seller-logs/RET16/FLOW-1/on_search_full_catalogue.json
shopclues/seller-logs/RET16/FLOW-1/on_search_incremental.json
shopclues/seller-logs/RET16/FLOW-1/search_full_catalogue.json
shopclues/seller-logs/RET16/FLOW-1/search_incremental.json

hi please check and approve ret 14 and ret 16 flow 1 logs of shopclues

shopclues ret 14 and ret 16 flow 1 logs

---

eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/confirm.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/init.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/on_confirm.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/on_init.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/on_search.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/on_status.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/on_track.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/on_update.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/search.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/status.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/track.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/Order Flow/update.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/cancel.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/confirm.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/init.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/on_cancel.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/on_confirm.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/on_init.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/on_search.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/on_status.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/on_update.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/search.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/status.json
eSamudaay/eSamudaay Logistic Buyer Api Logs/cancel flow/update.json

These are the logs for the eSamudaay Logistics Buyer in relation to the Pidge Logistics Seller. Please review the logs to ensure that all transactions are being processed correctly. If there are any discrepancies or issues identified, we would appreciate your guidance on resolving them.

Logistic Buyer Logs for eSamudaay

---

SellerSetu/BPP/Retail-1.2/RET13/Flow1/on_search_full_catalog_refresh.json
SellerSetu/BPP/Retail-1.2/RET13/Flow1/on_search_inc_refresh.json
SellerSetu/BPP/Retail-1.2/RET13/Flow1/search_full_catalog_refresh.json
SellerSetu/BPP/Retail-1.2/RET13/Flow1/search_inc_refresh.json
SellerSetu/BPP/Retail-1.2/RET13/Flow1/utility_payload.json
SellerSetu/BPP/Retail-1.2/RET13/Flow1/utility_response.json
SellerSetu/BPP/Retail-1.2/RET18/Flow1/on_search_full_catalog_refresh.json
SellerSetu/BPP/Retail-1.2/RET18/Flow1/on_search_inc_refresh.json
SellerSetu/BPP/Retail-1.2/RET18/Flow1/search_full_catalog_refresh.json
SellerSetu/BPP/Retail-1.2/RET18/Flow1/search_inc_refresh.json
SellerSetu/BPP/Retail-1.2/RET18/Flow1/utility_payload.json
SellerSetu/BPP/Retail-1.2/RET18/Flow1/utility_response.json

Resubmitting verified RET13,18 Logs as per comment on #2356
@sandeepshahi

SellerSetu SA:RET13,18

---

Fynd/SellerApp/August 2024/RET14/on_search(full catalog).json
Fynd/SellerApp/August 2024/RET14/on_search(inc).json
Fynd/SellerApp/August 2024/RET14/search(full catalog).json
Fynd/SellerApp/August 2024/RET14/search(inc).json

Fynd: Updated RET14 logs

---

Zoho/Retail/BPC/Flow 1/incremental_onsearch.json
Zoho/Retail/BPC/Flow 1/on_search.json
Zoho/Retail/Home & Kitchen/incremental_onsearch.json
Zoho/Retail/Home & Kitchen/incremental_search.json
Zoho/Retail/Home & Kitchen/on_search.json
Zoho/Retail/Home & Kitchen/search.json

@shivang1131 @sandeepshahi kindly check and approve RET13 and RE16 domain and got success in log validation utility also. 
cc: @subbaiyana

Zoho:Updated Search logs of RET13 and RET16

---

eSamudaay/ONDC_RET12/RET12_flow6/on_search.json
eSamudaay/ONDC_RET12/RET12_flow6/search.json
eSamudaay/ONDC_RET12/RET12_search/on_search.json
eSamudaay/ONDC_RET12/RET12_search/search.json

Please consider this PR, as in previous commit/PR I had mistakenly uploaded the RET11 search and on_search json which I have replaced with RET12 json's in this PR

Resubmission of Logs RET12: eSamudaay

---

Zoho/Retail/Home & Kitchen/incremental_onsearch.json
Zoho/Retail/Home & Kitchen/incremental_search.json
Zoho/Retail/Home & Kitchen/on_search.json
Zoho/Retail/Home & Kitchen/search.json

@shivang1131 fixed this [issue](https://github.com/ONDC-Official/v1.2.0-logs/issues/2420)

Zoho:Updated RET16 logs

---

Mystore/SellerAppF&B/FLOW1/on_search.json
Mystore/SellerAppF&B/FLOW1/search.json

Mystore RET11 catalog as per discussion with @sandeepshahi

Mystore RET11 Flow1

---

only-usable/IGM/Flow1/01. ret_issue.json
only-usable/IGM/Flow1/02. ret_on_issue.json
only-usable/IGM/Flow1/03. ret_issue_status.json
only-usable/IGM/Flow1/04. ret_on_issue_status.json
only-usable/IGM/Flow1/05. ret_on_issue_status_unsolicited.json
only-usable/IGM/Flow1/06. ret_issue_close.json
only-usable/IGM/Flow2/01. ret_issue.json
only-usable/IGM/Flow2/02. ret_on_issue.json
only-usable/IGM/Flow2/03. ret_issue_status.json
only-usable/IGM/Flow2/04. ret_on_issue_status.json
only-usable/IGM/Flow2/05. ret_on_issue_status_unsolicited.json
only-usable/IGM/Flow2/06. ret_issue_close.json

Only Usable buyer app IGM flow logs

IGM FLOW 1 & 2 Logs

---

Dailybee/Ret_12/Flow1/on_search_full_catalog_refresh.json
Dailybee/Ret_12/Flow1/on_search_inc_refresh.json
Dailybee/Ret_12/Flow1/search_full_catalog_refresh.json
Dailybee/Ret_12/Flow1/search_inc_refresh.json
Dailybee/Ret_12/Flow1/utility.json
Dailybee/Ret_13/Flow1/on_search_full_catalog_refresh.json
Dailybee/Ret_13/Flow1/on_search_inc_refresh.json
Dailybee/Ret_13/Flow1/search_full_catalog_refresh.json
Dailybee/Ret_13/Flow1/search_inc_refresh.json
Dailybee/Ret_13/Flow1/utility.json
Dailybee/Ret_16/Flow1/on_search_full_catalog_refresh.json
Dailybee/Ret_16/Flow1/on_search_inc_refresh.json
Dailybee/Ret_16/Flow1/search_full_catalog_refresh.json
Dailybee/Ret_16/Flow1/search_inc_refresh.json
Dailybee/Ret_16/Flow1/utility.json

@sandeepshahi 
@sahil-ondc
@BLR-0118

Dailybee (SA: RET12, RET13, RET16) Logs updated

---

Mystore/SellerAppF&B/FLOW1/on_search.json
Mystore/SellerAppF&B/FLOW1/search.json

Mystore RET11 catalog as per complaince

Mystore RET11 catalog

---

Dailybee/Ret_12/Flow1/body_utility.json
Dailybee/Ret_12/Flow1/on_search_full_catalog_refresh.json
Dailybee/Ret_12/Flow1/on_search_inc_refresh.json
Dailybee/Ret_12/Flow1/utility.json
Dailybee/Ret_16/Flow1/body_utility.json
Dailybee/Ret_16/Flow1/on_search_full_catalog_refresh.json
Dailybee/Ret_16/Flow1/search_full_catalog_refresh.json
Dailybee/Ret_16/Flow1/search_inc_refresh.json
Dailybee/Ret_16/Flow1/utility.json
Dailybee/Ret_18/Flow1/body_utility.json
Dailybee/Ret_18/Flow1/on_search_full_catalog_refresh.json
Dailybee/Ret_18/Flow1/on_search_inc_refresh.json
Dailybee/Ret_18/Flow1/search_full_catalog_refresh.json
Dailybee/Ret_18/Flow1/search_inc_refresh.json
Dailybee/Ret_18/Flow1/utility.json

@sahil-ondc
@sandeepshahi 
@BLR-0118

Dailybee ( SA: RET12,16,18 ) Logs updated

---

Zoho/Retail/Fashion/Flow 1/incremental_onsearch.json
Zoho/Retail/Fashion/Flow 1/incremental_search.json
Zoho/Retail/Fashion/Flow 1/on_search.json
Zoho/Retail/Fashion/Flow 1/search.json
Zoho/Retail/Fashion/Flow 6/confirm.json
Zoho/Retail/Fashion/Flow 6/init.json
Zoho/Retail/Fashion/Flow 6/on_confirm.json
Zoho/Retail/Fashion/Flow 6/on_init.json
Zoho/Retail/Fashion/Flow 6/on_search.json
Zoho/Retail/Fashion/Flow 6/on_select.json
Zoho/Retail/Fashion/Flow 6/on_status_delivered.json
Zoho/Retail/Fashion/Flow 6/on_status_out_for_delivery.json
Zoho/Retail/Fashion/Flow 6/on_status_packed.json
Zoho/Retail/Fashion/Flow 6/on_status_picked.json
Zoho/Retail/Fashion/Flow 6/on_update_approval.json
Zoho/Retail/Fashion/Flow 6/on_update_delivered.json
Zoho/Retail/Fashion/Flow 6/on_update_interim_liquidated.json
Zoho/Retail/Fashion/Flow 6/on_update_interim_reverse_qc.json
Zoho/Retail/Fashion/Flow 6/on_update_liquidated.json
Zoho/Retail/Fashion/Flow 6/on_update_part_cancel.json
Zoho/Retail/Fashion/Flow 6/on_update_picked.json
Zoho/Retail/Fashion/Flow 6/search.json
Zoho/Retail/Fashion/Flow 6/select.json
Zoho/Retail/Fashion/Flow 6/update_liquidated.json
Zoho/Retail/Fashion/Flow 6/update_reverse_qc.json
Zoho/Retail/Fashion/Flow 6/update_settlement_liquidated.json
Zoho/Retail/Fashion/Flow 6/update_settlement_part_cancel.json
Zoho/Retail/Fashion/Flow 6/update_settlement_reverse_qc.json

@sandeepshahi  / @shivang1131  pls review fashion flow 1 and flow6 logs and update asap.

Zoho:RET12 Logs

---

Easy Pay/BuyerApp/RET1A/on_search_full_catalog_refresh.txt
Easy Pay/BuyerApp/RET1A/on_search_inc_refresh.txt
Easy Pay/BuyerApp/RET1A/search_full_catalog_refresh.txt
Easy Pay/BuyerApp/RET1A/search_inc_refresh.txt

EasyPay added RET1A buyer logs

EasyPay added RET1A buyer logs

---

Pidge/LBNP/OrderFlow/Flow2/confirm.json
Pidge/LBNP/OrderFlow/Flow2/init.json
Pidge/LBNP/OrderFlow/Flow2/on_confirm.json
Pidge/LBNP/OrderFlow/Flow2/on_init.json
Pidge/LBNP/OrderFlow/Flow2/on_search.json
Pidge/LBNP/OrderFlow/Flow2/on_status_agent_assigned.json
Pidge/LBNP/OrderFlow/Flow2/on_status_delivered.json
Pidge/LBNP/OrderFlow/Flow2/on_status_ofd.json
Pidge/LBNP/OrderFlow/Flow2/on_status_picked_up.json
Pidge/LBNP/OrderFlow/Flow2/on_track.json
Pidge/LBNP/OrderFlow/Flow2/search.json
Pidge/LBNP/OrderFlow/Flow2/track.json

Added feedback logs for Flow2.
@abhinavv245 .

Updated logs for flow2

---

Easy Pay/Logistic-BuyerApp/Live-LSP/confirm.json
Easy Pay/Logistic-BuyerApp/Live-LSP/init.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_confirm.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_init.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_search.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_status_order_delivered.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_status_order_pickedup.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_status_out_for_delivery.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_status_rider_assigned.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_track.json
Easy Pay/Logistic-BuyerApp/Live-LSP/on_update.json
Easy Pay/Logistic-BuyerApp/Live-LSP/search.json
Easy Pay/Logistic-BuyerApp/Live-LSP/track.json
Easy Pay/Logistic-BuyerApp/Live-LSP/update.json

Live Logs with MP2 Logistics partner

Live Logs with MP2 Logistics partner

---

Easy Pay/BuyerApp/Home & Kitchen-Flow1/on_search_full_catalog_refresh.txt
Easy Pay/BuyerApp/Home & Kitchen-Flow1/on_search_inc_refresh.txt
Easy Pay/BuyerApp/Home & Kitchen-Flow1/search_full_catalog_refresh.txt
Easy Pay/BuyerApp/Home & Kitchen-Flow1/search_inc_refresh.txt

EasyPay Buyer-App-RET16 Logs added for Flow1

EasyPay Buyer-App-RET16 Logs added for Flow1

---

1Bridge/ONDC_RET16/on_search_inc.json
1Bridge/ONDC_RET16/search_inc.json

Fixed a minor bug in incremental search. Resubmitting logs.

updated on_search_inc logs

---

Buynxt_Greenreceipt/RET15_2024_09_27/log_utility_report.json
Buynxt_Greenreceipt/RET15_2024_09_27/on_search.json
Buynxt_Greenreceipt/RET15_2024_09_27/on_search_inc_catalog.json
Buynxt_Greenreceipt/RET15_2024_09_27/on_search_inc_store_close.json
Buynxt_Greenreceipt/RET15_2024_09_27/on_search_inc_store_open.json
Buynxt_Greenreceipt/RET15_2024_09_27/search.json
Buynxt_Greenreceipt/RET15_2024_09_27/search_inc_start.json

ONDC:RET15 logs along with log-utility-report.

ONDC:RET15 logs along with log-utility-report.

---

COSTBO/Logistics/logistics-IGM-28sep/1-issue.json
COSTBO/Logistics/logistics-IGM-28sep/2-onIssue.json
COSTBO/Logistics/logistics-IGM-28sep/3-Issue-status-request.json
COSTBO/Logistics/logistics-IGM-28sep/4-onIssue-status-response.json
COSTBO/Logistics/logistics-IGM-28sep/5-onIssuestatus-resolved.json
COSTBO/Logistics/logistics-IGM-28sep/6-Issue-closed.json

COSTBO logistics IGM - validation verified.

COSTBO logistics IGM

---

Xpress_Baazaar/LBNP/IGM/FLow_1/issue.json
Xpress_Baazaar/LBNP/IGM/FLow_1/issue_closed.json
Xpress_Baazaar/LBNP/IGM/FLow_1/issue_status.json
Xpress_Baazaar/LBNP/IGM/FLow_1/on_issue.json
Xpress_Baazaar/LBNP/IGM/FLow_1/on_issue_status.json
Xpress_Baazaar/LBNP/IGM/FLow_1/unsolicited_on_issue_status.json
Xpress_Baazaar/LBNP/IGM/FLow_2/issue.json
Xpress_Baazaar/LBNP/IGM/FLow_2/issue_closed.json
Xpress_Baazaar/LBNP/IGM/FLow_2/issue_status.json
Xpress_Baazaar/LBNP/IGM/FLow_2/on_issue.json
Xpress_Baazaar/LBNP/IGM/FLow_2/on_issue_status.json
Xpress_Baazaar/LBNP/IGM/FLow_2/unsolicited_on_issue_status.json

logs submitted as feedback

---

Thrive/Logistics Buyer App/RSF/Flow 1/on_receiver_recon.json
Thrive/Logistics Buyer App/RSF/Flow 1/receiver_recon.json
Thrive/Logistics Buyer App/RSF/Flow 2/on_receiver_recon.json
Thrive/Logistics Buyer App/RSF/Flow 2/reciever_recon.json

We have added recon/on_recon both flows for logistics buyer.

Logistics Buyer App - RSF Logs

---

Fynd/SellerApp/July 2024/RET16/Search(inc).json
Fynd/SellerApp/July 2024/RET16/on_search(full_catalog).json
Fynd/SellerApp/July 2024/RET16/on_search(inc).json
Fynd/SellerApp/July 2024/RET16/search(full_catalog).json

Updated: Fynd RET16 logs

---

Krenai_Retail/Retail_13/Flow1/incremental_search.json
Krenai_Retail/Retail_13/Flow1/on_incremental_search.json
Krenai_Retail/Retail_13/Flow1/on_search.json
Krenai_Retail/Retail_13/Flow1/search.json
Krenai_Retail/Retail_16/Flow_1/incremental_search.json
Krenai_Retail/Retail_16/Flow_1/on_incremental_search.json
Krenai_Retail/Retail_16/Flow_1/on_search.json
Krenai_Retail/Retail_16/Flow_1/search.json

1. We have added colour_name for RET16 but for RET13 colour_name is optional for category Fragrance.
2. Hand made products do not have any EAN code, so we have added HSN code.

logs updated as per feedbacks

---

Thrive/Logistics Buyer App/RSF/Flow 1/on_receiver_recon.json
Thrive/Logistics Buyer App/RSF/Flow 1/receiver_recon.json
Thrive/Logistics Buyer App/RSF/Flow 2/on_receiver_recon.json
Thrive/Logistics Buyer App/RSF/Flow 2/reciever_recon.json

https://github.com/ONDC-Official/v1.2.0-logs/issues/2577

Regenerated logs as per feedback

---

Fynd/SellerApp/July 2024/RET16/Search(inc).json
Fynd/SellerApp/July 2024/RET16/on_search(full_catalog).json
Fynd/SellerApp/July 2024/RET16/on_search(inc).json
Fynd/SellerApp/July 2024/RET16/search(full_catalog).json

Updated: RET16 Fynd logs

---

COSTBO/Logistics/logistics-IGM-8thOct/1-issue.json
COSTBO/Logistics/logistics-IGM-8thOct/2-on-issue.json
COSTBO/Logistics/logistics-IGM-8thOct/3-issues-status-request.json
COSTBO/Logistics/logistics-IGM-8thOct/4-on-issue-status-response.json
COSTBO/Logistics/logistics-IGM-8thOct/5-on-issue-status-resolved.json
COSTBO/Logistics/logistics-IGM-8thOct/6-issue-closed.json
COSTBO/Logistics/logistics-RSF-8thOct/Correction-flow/1-receiver-recon.json
COSTBO/Logistics/logistics-RSF-8thOct/Correction-flow/2-on-receiver-recon.json
COSTBO/Logistics/logistics-RSF-8thOct/Happy-flow/1-settle.json
COSTBO/Logistics/logistics-RSF-8thOct/Happy-flow/2-onsettle.json
COSTBO/Logistics/logistics-RSF-8thOct/Happy-flow/3-receiver-recon.json
COSTBO/Logistics/logistics-RSF-8thOct/Happy-flow/4-on-receiver-recon.json

COSTBO logistics-IGM-update

---

Easy Pay/SellerApp/RET1A/Flow 1/on_search_full_catalouge.json
Easy Pay/SellerApp/RET1A/Flow 1/on_search_incremental_catalogue.json
Easy Pay/SellerApp/RET1A/Flow 1/search.json
Easy Pay/SellerApp/RET1A/Flow 1/search_incremental_catalogue.json
Easy Pay/SellerApp/RET1A/Flow 1/validation_report.json

EasyPay Seller RET1A Logs Submission

EasyPay Seller RET1A Logs Submission

---

nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET13/on_search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET13/on_search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET13/reports.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET13/search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET13/search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET14/on_search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET14/on_search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET14/reports.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET14/search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET14/search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET15/on_search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET15/on_search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET15/reports.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET15/search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET15/search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET16/on_search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET16/on_search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET16/reports.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET16/search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET16/search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET18/on_search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET18/on_search_inc.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET18/reports.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET18/search.json
nStore/Retail Buyer App/V1.2Logs/Search OnSearch Logs/ONDC:RET18/search_inc.json

nStore BuyerApp - Search OnSearch Logs resubmission

nStore BuyerApp - Search OnSearch Logs - 16OCT2024

---

open_financial/IGM/FLOW_1/CURL
open_financial/IGM/FLOW_1/ret_issue.json
open_financial/IGM/FLOW_1/ret_issue_close.json
open_financial/IGM/FLOW_1/ret_issue_status.json
open_financial/IGM/FLOW_1/ret_on_issue.json
open_financial/IGM/FLOW_1/ret_on_issue_status.json
open_financial/IGM/FLOW_2/CURL
open_financial/IGM/FLOW_2/lsp_issue.json
open_financial/IGM/FLOW_2/lsp_issue_close.json
open_financial/IGM/FLOW_2/lsp_issue_status.json
open_financial/IGM/FLOW_2/lsp_on_issue.json
open_financial/IGM/FLOW_2/lsp_on_issue_status.json
open_financial/IGM/FLOW_2/ret_issue.json
open_financial/IGM/FLOW_2/ret_issue_close.json
open_financial/IGM/FLOW_2/ret_issue_status.json
open_financial/IGM/FLOW_2/ret_on_issue.json
open_financial/IGM/FLOW_2/ret_on_issue_status.json
open_financial/IGM/FLOW_3/CURL
open_financial/IGM/FLOW_3/lsp_issue.json
open_financial/IGM/FLOW_3/lsp_issue_close.json
open_financial/IGM/FLOW_3/lsp_issue_status.json
open_financial/IGM/FLOW_3/lsp_on_issue.json
open_financial/IGM/FLOW_3/lsp_on_issue_status.json
open_financial/IGM/FLOW_3/ret_issue.json
open_financial/IGM/FLOW_3/ret_issue_close.json
open_financial/IGM/FLOW_3/ret_issue_status.json
open_financial/IGM/FLOW_3/ret_on_issue.json
open_financial/IGM/FLOW_3/ret_on_issue_status.json

submitting Open Financial IGM Logs for review, validation verified.

Open Financial IGM Logs

---

COSTBO/Logistics/logistics-IGM-20thOct/1-issue.json
COSTBO/Logistics/logistics-IGM-20thOct/2-onissue.json
COSTBO/Logistics/logistics-IGM-20thOct/3-issue-status-request.json
COSTBO/Logistics/logistics-IGM-20thOct/4-on-issue-status-response.json
COSTBO/Logistics/logistics-IGM-20thOct/5-on-issue-status-resolved.json
COSTBO/Logistics/logistics-IGM-20thOct/6-issue-closed.json

COSBTO Logistics IGM comment fixed
Rupal had only one comment in the previous iteration and that is fixed.

COSBTO Logistics IGM comment fixed

---

Sabhyasha/Retail/RET10/Flow1/1. search_full_catalog.json
Sabhyasha/Retail/RET10/Flow1/2. on_search_full_catalog.json
Sabhyasha/Retail/RET10/Flow1/3. search_inc_refresh.json
Sabhyasha/Retail/RET10/Flow1/4. on_search_inc_refresh.json
Sabhyasha/Retail/RET10/Flow1/curl.json

Grocery Domain Logs are added successfully uploaded.

Logs For Grocery Domain.

---

Ninjacart/Retail/seller-rsf/Flow-1 Success/on_receiver_recon.json
Ninjacart/Retail/seller-rsf/Flow-1 Success/receiver_recon.json
Ninjacart/Retail/seller-rsf/Flow-2 Correction/on_receiver_recon.json
Ninjacart/Retail/seller-rsf/Flow-2 Correction/receiver_recon.json

ninjacart seller -rsf flow

---

Krenai_Retail/Retail_13/Flow1/incremental_search.json
Krenai_Retail/Retail_13/Flow1/on_incremental_search.json
Krenai_Retail/Retail_13/Flow1/on_search.json
Krenai_Retail/Retail_13/Flow1/search.json
Krenai_Retail/Retail_16/Flow_1/incremental_search.json
Krenai_Retail/Retail_16/Flow_1/on_incremental_search.json
Krenai_Retail/Retail_16/Flow_1/on_search.json
Krenai_Retail/Retail_16/Flow_1/search.json

1. RET13 : Currently we only have vendors with Fragrance category products.
2. RET16 : Currently we have single vendor with handmade Home Decor products only
3. For GPS issue : We are using same GPS and pincode provided by google api , please validate it with google maps. I have attached the the image for your reference as well @sandeepshahi

Retail logs updated

---

COSTBO/Logistics/logistics-RSF-25thOct/Correction-flow/1-receiver-recon.json
COSTBO/Logistics/logistics-RSF-25thOct/Correction-flow/2-on-receiver-recon.json
COSTBO/Logistics/logistics-RSF-25thOct/Happy-flow/1-settle.json
COSTBO/Logistics/logistics-RSF-25thOct/Happy-flow/2-onsettle.json
COSTBO/Logistics/logistics-RSF-25thOct/Happy-flow/3-receiver-recon.json
COSTBO/Logistics/logistics-RSF-25thOct/Happy-flow/4-on-receiver-recon.json

COSTBO LBNP RSF 1.0.0 - errors fixed

COSTBO LBNP RSF 1.0.0 - errors fixed

---

nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/confirm.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/init.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/on_confirm.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/on_init.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/on_select.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/on_status_delivered.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/on_status_out_for_delivery.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/on_status_pending.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/on_status_picked.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/on_track.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/select.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2 (with track)/track.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/confirm.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/init.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/on_confirm.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/on_init.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/on_select.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/on_status_delivered.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/on_status_out_for_delivery.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/on_status_pending.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/on_status_picked.json
nStore/Retail Buyer App/V1.2Logs/F&B Logs V1.2/Flow 2/select.json

nstore
/select payload issue fixed,
/track and /on_track payload is submitted in separate flow,
on_status_packed is not supported from seller, so that payload is not submitted.

nStore-Submitted track flow and flow with select issue  fix  25-oct-2024

---

Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 1/on_search_full_catalog_refresh.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 1/search_full_catalog_refresh.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/confirm.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/init.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_confirm.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_init.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_search_full_catalog_refresh.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_select.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_status_delivered.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_status_out_for_delivery.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_status_packed.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_status_picked.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/on_track.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/search_full_catalog_refresh.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/select.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 2/track.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 3/on_search_full_catalog_refresh.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 3/on_select_out_of_stock.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 3/search_full_catalog_refresh.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 3/select_out_of_stock.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/cancel.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/confirm.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/init.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/on_cancel.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/on_confirm.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/on_init.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/on_search_full_catalog_refresh.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/on_select.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/search_full_catalog_refresh.json
Sequelstring/Retail/Seller/Grocery/Off Network Delivery/Flow 4/select.json

Submitting Logs for Retail Seller

TSP Logs Retail Seller

---

SellerSetu/BPP/Retail-1.2/RET11/Flow1/on_search_full_catalog_refresh.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/on_search_inc_refresh.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/search_full_catalog_refresh.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/search_inc_refresh.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/utility_payload.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/utility_response.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/confirm.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/init.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_confirm.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_init.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_select.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_select_out_of_stock.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_status_delivered.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_status_out_for_delivery.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_status_packed.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_status_picked.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/on_track.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/select.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/select_out_of_stock.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/track.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/utility_payload.json
SellerSetu/BPP/Retail-1.2/RET11/Flow3/utility_response.json

Resubmitting Logs for Flow 1 and 3 based on discussion at #2713 
cc @sellersetu-hub @Ikshan-Tango

SellerSetu (SA: RET11) (2): Flow 1, 3

---

SellerSetu/BPP/Retail-1.2/RET11/Flow1/on_search_full_catalog_refresh.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/on_search_inc_refresh.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/search_full_catalog_refresh.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/search_inc_refresh.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/utility_payload.json
SellerSetu/BPP/Retail-1.2/RET11/Flow1/utility_response.json

Resubmitting Logs for Flow 1 based on discussion at #2713 
cc @sellersetu-hub @Ikshan-Tango

SellerSetu (SA: RET11) (3): Flow 1

---

Futuresoft/SellerApp/ONDC_RET10/Flow1/on_search_full_catalog_refresh.json
Futuresoft/SellerApp/ONDC_RET10/Flow1/on_search_inc_refresh.json
Futuresoft/SellerApp/ONDC_RET10/Flow1/search_full_catalog_refresh.json
Futuresoft/SellerApp/ONDC_RET10/Flow1/search_inc_refresh.json

Please Find the regenerated Flow 1. Below are the some points of recived feedback:
invalid item_id format- gid://shopify/ProductVariant/46069366653183. It should be either uuid or 32 characters long - - alphanumeric without any special characters
> **We have cleared the Fashion domain logs with such id already mentioned on a mail and GitHub issue board and not recieved any reponse from Sahil**

Grocery flow 1

---

Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 1/issue.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 1/issue_closed.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 1/issue_status.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 1/on_issue.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 1/on_issue_status.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 1/on_issue_status_resolved.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 2/issue.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 2/issue_closed.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 2/issue_status.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 2/on_issue.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 2/on_issue_status.json
Tipplr/Tipplr Logistics Buyer/tipplr-LBNP-IGM logs(12 NOV)/Fulfillment 2/on_issue_status_resolved.json

Hi there,
Have added IGM logs of logistics buyer app.
Merge and give feedback on it.
Thank you.

Tipplr LBNP- added Logistics IGM logs

---

shopalyst/phase-1/RSF/flow-1/on_report.json
shopalyst/phase-1/RSF/flow-1/on_settle.json
shopalyst/phase-1/RSF/flow-1/report.json
shopalyst/phase-1/RSF/flow-1/settle.json
shopalyst/phase-1/RSF/flow-2/on_recon.json
shopalyst/phase-1/RSF/flow-2/on_report.json
shopalyst/phase-1/RSF/flow-2/on_settle.json
shopalyst/phase-1/RSF/flow-2/on_settle_after_recon.json
shopalyst/phase-1/RSF/flow-2/recon.json
shopalyst/phase-1/RSF/flow-2/report.json
shopalyst/phase-1/RSF/flow-2/settle.json
shopalyst/phase-1/RSF/flow-2/settle_after_recon.json
shopalyst/phase-1/RSF/flow-3/on_recon.json
shopalyst/phase-1/RSF/flow-3/on_report.json
shopalyst/phase-1/RSF/flow-3/on_settle.json
shopalyst/phase-1/RSF/flow-3/recon.json
shopalyst/phase-1/RSF/flow-3/report.json
shopalyst/phase-1/RSF/flow-3/settle.json
shopalyst/phase-1/RSF/flow-4/on_settle.json
shopalyst/phase-1/RSF/flow-4/settle.json
shopalyst/phase-1/RSF/flow-5/on_settle.json
shopalyst/phase-1/RSF/flow-5/settle.json

RSF 2.0 log files added for all the flows

rsf 2.0 log

---

Tipplr/Tipplr Logistics Buyer/Tipplr-LBNP-RSF-updated(Nov-15)/Flow 1 Success/on_receiver_recon.json
Tipplr/Tipplr Logistics Buyer/Tipplr-LBNP-RSF-updated(Nov-15)/Flow 1 Success/receiver_recon.json
Tipplr/Tipplr Logistics Buyer/Tipplr-LBNP-RSF-updated(Nov-15)/Flow 2 Correction/on_receiver_recon.json
Tipplr/Tipplr Logistics Buyer/Tipplr-LBNP-RSF-updated(Nov-15)/Flow 2 Correction/receiver_recon.json

Hi there,
We are working on logistics buyer app.
We have added RSF logs for verification.
Merge our logs.
Thanks

tipplr LBNP- Added Rsf logs

---

MaasERP_Solutions/Retail/RET18/on_search_full_catalog_refresh.json
MaasERP_Solutions/Retail/RET18/on_search_inc_refresh.json
MaasERP_Solutions/Retail/RET18/search_full_catalog_refresh.json
MaasERP_Solutions/Retail/RET18/search_inc_refresh.json

MaasERP RET 18

---

MaasERP_Solutions/Retail/RET16/on_search_full_catalog_refresh.json
MaasERP_Solutions/Retail/RET16/on_search_inc_refresh.json
MaasERP_Solutions/Retail/RET16/search_full_catalog_refresh.json
MaasERP_Solutions/Retail/RET16/search_inc_refresh.json

MaasERP RET 16

---

MaasERP_Solutions/Retail/RET14/on_search_full_catalog_refresh.json
MaasERP_Solutions/Retail/RET14/on_search_inc_refresh.json
MaasERP_Solutions/Retail/RET14/search_full_catalog_refresh.json
MaasERP_Solutions/Retail/RET14/search_inc_refresh.json

MaasERP RET 14

---

MaasERP_Solutions/Retail/RET13/on_search_full_catalog_refresh.json
MaasERP_Solutions/Retail/RET13/on_search_inc_refresh.json
MaasERP_Solutions/Retail/RET13/search_full_catalog_refresh.json
MaasERP_Solutions/Retail/RET13/search_inc_refresh.json

MaasERP RET 13

---

Krenai_Retail/Retail_12/Flow 1/incremental_search.json
Krenai_Retail/Retail_12/Flow 1/on_incremental_search.json
Krenai_Retail/Retail_12/Flow 1/on_search.json
Krenai_Retail/Retail_12/Flow 1/search.json
Krenai_Retail/Retail_13/Flow1/incremental_search.json
Krenai_Retail/Retail_13/Flow1/on_incremental_search.json
Krenai_Retail/Retail_13/Flow1/on_search.json
Krenai_Retail/Retail_13/Flow1/search.json
Krenai_Retail/Retail_16/Flow_1/on_incremental_search.json
Krenai_Retail/Retail_16/Flow_1/on_search.json

RET:12 logs added & logs for RET-16,13 updated as per the feedbacks

RET:12 logs added & 16,13 updated

---

SellerSetu/BPP/RSF-2.0/Flow1/01_settle.json
SellerSetu/BPP/RSF-2.0/Flow1/02_on_settle.json
SellerSetu/BPP/RSF-2.0/Flow1/03_report.json
SellerSetu/BPP/RSF-2.0/Flow1/04_on_report.json
SellerSetu/BPP/RSF-2.0/Flow2/01_settle.json
SellerSetu/BPP/RSF-2.0/Flow2/02_on_settle.json
SellerSetu/BPP/RSF-2.0/Flow2/03_report.json
SellerSetu/BPP/RSF-2.0/Flow2/04_on_report.json
SellerSetu/BPP/RSF-2.0/Flow2/05_recon.json
SellerSetu/BPP/RSF-2.0/Flow2/06_on_recon.json
SellerSetu/BPP/RSF-2.0/Flow2/07_settle.json
SellerSetu/BPP/RSF-2.0/Flow2/08_on_settle.json
SellerSetu/BPP/RSF-2.0/Flow3/01_settle.json
SellerSetu/BPP/RSF-2.0/Flow3/02_on_settle.json
SellerSetu/BPP/RSF-2.0/Flow3/03_report.json
SellerSetu/BPP/RSF-2.0/Flow3/04_on_report.json
SellerSetu/BPP/RSF-2.0/Flow3/05_recon.json
SellerSetu/BPP/RSF-2.0/Flow3/06_on_recon.json
SellerSetu/BPP/RSF-2.0/Flow4/01_settle.json
SellerSetu/BPP/RSF-2.0/Flow4/02_on_settle.json
SellerSetu/BPP/RSF-2.0/Flow4/03_report.json
SellerSetu/BPP/RSF-2.0/Flow4/04_on_report.json
SellerSetu/BPP/RSF-2.0/Flow5/01_settle.json
SellerSetu/BPP/RSF-2.0/Flow5/02_on_settle.json

RSF 2.0 Logs for SellerSetu SA
cc @sellersetu-hub

SellerSetu BPP: RSF 2.0

---

STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/confirm.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/init.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/log_validation_response.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_confirm.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_init.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_search.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_select.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_select_out_of_stock.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_status_delivered.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_status_out_for_delivery.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_status_packed.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_status_pending.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/on_status_picked.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/search.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/select.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/RET14/Retail/flow3/select_out_of_stock.json

Request for the Buyer App log submission for the RET14 domain, covering Modification in Retail Flow 3 .
Kindly review and merge it.
@sandeepshahi @BLR-0118

STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/ Retail changes after review

---

Channelier/AGR_10/Flow 1/on_search.json
Channelier/AGR_10/Flow 1/on_search_inc.json
Channelier/AGR_10/Flow 1/search.json
Channelier/AGR_10/Flow 1/search_inc.json
Channelier/RET_1A/Flow 1/on_search.json
Channelier/RET_1A/Flow 1/on_search_inc.json
Channelier/RET_1A/Flow 1/search.json
Channelier/RET_1A/Flow 1/search_inc.json

Updated logs for channelier New Categories RET1A and AGR10
after review #2844

Updated logs for channelier New Categories RET1A and AGR10

---

Buyume/IGM/report.json
Buyume/IGM/ret_issue_close.json
Buyume/IGM/ret_on_issue.json
Buyume/IGM/ret_on_issue_status.json
Buyume/RSF/on_receiver_recon.json
Buyume/RSF/receiver_recon.json
Buyume/RSF/report.json

Hi please check the IGM and RFS logs from buyume and merge it.

IGM and RSF logs

---

Channelier/AGR_10/Flow 1/on_search.json
Channelier/AGR_10/Flow 1/on_search_inc.json
Channelier/AGR_10/Flow 1/search.json
Channelier/AGR_10/Flow 1/search_inc.json
Channelier/RET_1A/Flow 1/on_search.json
Channelier/RET_1A/Flow 1/on_search_inc.json
Channelier/RET_1A/Flow 1/search.json
Channelier/RET_1A/Flow 1/search_inc.json

Channelier Updated Logs for RET1A and AGR10

---

Squadcube/RSF-2.0/Flow-1/01_settle.json
Squadcube/RSF-2.0/Flow-1/02_on_settle.json
Squadcube/RSF-2.0/Flow-1/03_report.json
Squadcube/RSF-2.0/Flow-1/04_on_report.json
Squadcube/RSF-2.0/Flow-2/01_settle.json
Squadcube/RSF-2.0/Flow-2/02_on_settle.json
Squadcube/RSF-2.0/Flow-2/03_report.json
Squadcube/RSF-2.0/Flow-2/04_on_report.json
Squadcube/RSF-2.0/Flow-2/05_recon.json
Squadcube/RSF-2.0/Flow-2/06_on_recon.json
Squadcube/RSF-2.0/Flow-2/07_settle.json
Squadcube/RSF-2.0/Flow-2/08_on_settle.json

RSF - 2.0 Flow-1 and Flow-2 Bug fixes Updated

RSF-2.0 Flow-1 and Flow-2 Bug fixes Updated

---

WITSLAB/wits-nexus-logistics/IGM/10_on_issue_status.json
WITSLAB/wits-nexus-logistics/IGM/1_search.json
WITSLAB/wits-nexus-logistics/IGM/2_on_search.json
WITSLAB/wits-nexus-logistics/IGM/3_init.json
WITSLAB/wits-nexus-logistics/IGM/4_on_init.json
WITSLAB/wits-nexus-logistics/IGM/5_confirm.json
WITSLAB/wits-nexus-logistics/IGM/6_on_confirm.json
WITSLAB/wits-nexus-logistics/IGM/7_issue.json
WITSLAB/wits-nexus-logistics/IGM/8_on_issue.json
WITSLAB/wits-nexus-logistics/IGM/9_issue_status.json

logistics igm logs

---

Sabhyasha/RSF 2.0/flow1/01_settle.json
Sabhyasha/RSF 2.0/flow1/02_on_settle.json
Sabhyasha/RSF 2.0/flow1/03_report.json
Sabhyasha/RSF 2.0/flow1/04_on_report.json
Sabhyasha/RSF 2.0/flow2/01_settle.json
Sabhyasha/RSF 2.0/flow2/02_on_settle.json
Sabhyasha/RSF 2.0/flow2/03_report.json
Sabhyasha/RSF 2.0/flow2/04_on_report.json
Sabhyasha/RSF 2.0/flow2/05_recon.json
Sabhyasha/RSF 2.0/flow2/06_on_recon.json
Sabhyasha/RSF 2.0/flow2/07_settle.json
Sabhyasha/RSF 2.0/flow2/08_on_settle.json
Sabhyasha/RSF 2.0/flow3/01_settle.json
Sabhyasha/RSF 2.0/flow3/02_on_settle.json
Sabhyasha/RSF 2.0/flow3/03_report.json
Sabhyasha/RSF 2.0/flow3/04_on_report.json
Sabhyasha/RSF 2.0/flow3/05_recon.json
Sabhyasha/RSF 2.0/flow3/06_on_recon.json
Sabhyasha/RSF 2.0/flow4/01_settle.json
Sabhyasha/RSF 2.0/flow4/02_on_settle.json
Sabhyasha/RSF 2.0/flow4/03_report.json
Sabhyasha/RSF 2.0/flow4/04_on_report.json
Sabhyasha/RSF 2.0/flow5/01_settle.json
Sabhyasha/RSF 2.0/flow5/02_on_settle.json

Upload the RSF 2.0 Logs according to RSF 2.0 Contract Flows mentioned .

Upload the RSF 2.0 Logs .

---

MaasERP_Solutions/Retail/2025-01-02/RET13/on_search_full_catalog_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET13/on_search_inc_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET13/search_full_catalog_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET13/search_inc_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET13/utility_report.json
MaasERP_Solutions/Retail/2025-01-02/RET14/on_search_full_catalog_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET14/on_search_inc_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET14/search_full_catalog_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET14/search_inc_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET14/utility_report.json
MaasERP_Solutions/Retail/2025-01-02/RET16/on_search_full_catalog_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET16/on_search_inc_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET16/search_full_catalog_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET16/search_inc_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET16/utility_report.json
MaasERP_Solutions/Retail/2025-01-02/RET18/on_search_full_catalog_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET18/on_search_inc_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET18/search_full_catalog_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET18/search_inc_refresh.json
MaasERP_Solutions/Retail/2025-01-02/RET18/utility_report.json

Added items.@ondc/org/statutory_reqs_packaged_commodities after feedback.

MaasErp RET13,14,16 & 18

---

yuukke/RET10/IGM/FLOW1/ret_issue.json
yuukke/RET10/IGM/FLOW1/ret_issue_close.json
yuukke/RET10/IGM/FLOW1/ret_issue_status.json
yuukke/RET10/IGM/FLOW1/ret_on_issue.json
yuukke/RET10/IGM/FLOW1/ret_on_issue_status.json
yuukke/RET10/IGM/FLOW2/ret_issue.json
yuukke/RET10/IGM/FLOW2/ret_issue_close.json
yuukke/RET10/IGM/FLOW2/ret_issue_status.json
yuukke/RET10/IGM/FLOW2/ret_on_issue.json
yuukke/RET10/IGM/FLOW2/ret_on_issue_status.json
yuukke/RSF_Logs/flow 1/on_report.json
yuukke/RSF_Logs/flow 1/on_settle.json
yuukke/RSF_Logs/flow 1/report.json
yuukke/RSF_Logs/flow 1/settle.json
yuukke/RSF_Logs/flow 3/on_reciver_recon.json
yuukke/RSF_Logs/flow 3/on_report.json
yuukke/RSF_Logs/flow 3/on_settle.json
yuukke/RSF_Logs/flow 3/reciver_recon.json
yuukke/RSF_Logs/flow 3/report.json
yuukke/RSF_Logs/flow 3/settle.json

IGM and RSF Log corrections done

IGM and RSF Log corrections done

---

Futuresoft/SellerApp/ONDC_RET15/Flow1/on_search_full_catalog_refresh.json
Futuresoft/SellerApp/ONDC_RET15/Flow1/on_search_inc_refresh.json
Futuresoft/SellerApp/ONDC_RET15/Flow1/search_full_catalog_refresh.json
Futuresoft/SellerApp/ONDC_RET15/Flow1/search_inc_refresh.json
Futuresoft/SellerApp/ONDC_RET15/Utility/Flow1/Payload.json
Futuresoft/SellerApp/ONDC_RET15/Utility/Flow1/Response.json

Utility added 

---

Easy Pay/SellerApp/AGR10/on_search_full_catalog_refresh.json
Easy Pay/SellerApp/AGR10/on_search_inc_refresh.json
Easy Pay/SellerApp/AGR10/response.json
Easy Pay/SellerApp/AGR10/search_full_catalog_refresh.json
Easy Pay/SellerApp/AGR10/search_inc_refresh.json

EasyPay Seller: Added Flow - 1 for AGR10 category

EasyPay Seller: Added Flow - 1 for AGR10 category

---

Easy Pay/BuyerApp/Agriculture-Flow1/on_search_full_catalog_refresh.txt
Easy Pay/BuyerApp/Agriculture-Flow1/on_search_inc_refresh.txt
Easy Pay/BuyerApp/Agriculture-Flow1/search_full_catalog_refresh.txt
Easy Pay/BuyerApp/Agriculture-Flow1/search_inc_refresh.txt

EasyPay Buyer App - Agriculture Flow 1 Logs Added

EasyPay Buyer App - Agriculture Flow 1 Logs Added

---

yuukke/RSF_Logs/flow 3/on_reciver_recon.json
yuukke/RSF_Logs/flow 3/on_report.json
yuukke/RSF_Logs/flow 3/on_settle.json
yuukke/RSF_Logs/flow 3/reciver_recon.json
yuukke/RSF_Logs/flow 3/report.json
yuukke/RSF_Logs/flow 3/settle.json

 RSF Log correction done

---

foxyCoop/RSF2/flow1/on_report.json
foxyCoop/RSF2/flow1/report.json
foxyCoop/RSF2/flow2/on_recon.json
foxyCoop/RSF2/flow2/on_report.json
foxyCoop/RSF2/flow2/on_settle.json
foxyCoop/RSF2/flow2/recon.json
foxyCoop/RSF2/flow2/report.json
foxyCoop/RSF2/flow3/on_recon.json
foxyCoop/RSF2/flow3/on_report.json
foxyCoop/RSF2/flow3/on_settle.json
foxyCoop/RSF2/flow3/recon.json
foxyCoop/RSF2/flow3/report.json
foxyCoop/RSF2/flow4/on_report.json
foxyCoop/RSF2/flow4/report.json

foxyCoop (BA) RSF 2 logs updated as feedback received

foxyCoop (BA) RSF 2 logs updated as feedback received

---

Easy Pay/SellerApp/AGR10/on_search_full_catalog_refresh.json
Easy Pay/SellerApp/AGR10/on_search_inc_refresh.json
Easy Pay/SellerApp/AGR10/response.json
Easy Pay/SellerApp/AGR10/search_full_catalog_refresh.json
Easy Pay/SellerApp/AGR10/search_inc_refresh.json

EasyPay Seller App Update Flow - 1 for AGR10 category

EasyPay Seller App Update Flow - 1 for AGR10 category

---

yuukke/RET10/IGM/FLOW1/ret_issue.json
yuukke/RET10/IGM/FLOW1/ret_issue_close.json
yuukke/RET10/IGM/FLOW1/ret_issue_status.json
yuukke/RET10/IGM/FLOW1/ret_on_issue.json
yuukke/RET10/IGM/FLOW1/ret_on_issue_status.json
yuukke/RET10/IGM/FLOW2/ret_issue.json
yuukke/RET10/IGM/FLOW2/ret_issue_close.json
yuukke/RET10/IGM/FLOW2/ret_issue_status.json
yuukke/RET10/IGM/FLOW2/ret_on_issue.json
yuukke/RET10/IGM/FLOW2/ret_on_issue_status.json

IGM Correction done

---

Protean/agr-buyer-logs/flow_1_on_search/on_search_farmigo
Protean/agr-buyer-logs/flow_1_on_search/search_agr10
Protean/agr-buyer-logs/flow_2_happy_flow/confirm.json
Protean/agr-buyer-logs/flow_2_happy_flow/init.json
Protean/agr-buyer-logs/flow_2_happy_flow/on_confirm.json
Protean/agr-buyer-logs/flow_2_happy_flow/on_init.json
Protean/agr-buyer-logs/flow_2_happy_flow/on_select.json
Protean/agr-buyer-logs/flow_2_happy_flow/on_status_order_delivered.json
Protean/agr-buyer-logs/flow_2_happy_flow/on_status_out_for_delivery.json
Protean/agr-buyer-logs/flow_2_happy_flow/on_status_packed.json
Protean/agr-buyer-logs/flow_2_happy_flow/on_status_pending.json
Protean/agr-buyer-logs/flow_2_happy_flow/on_status_picked_up.json
Protean/agr-buyer-logs/flow_2_happy_flow/select.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/cancel.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/confirm.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/init.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/on_cancel.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/on_confirm.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/on_init.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/on_select.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/on_status_pending.json
Protean/agr-buyer-logs/flow_3_buyer_cancels_order/select.json

Protean TSP AGR10 Buyer Logs

---

Futuresoft/SellerApp/ONDC_RET15/Flow1/on_search_full_catalog_refresh.json
Futuresoft/SellerApp/ONDC_RET15/Flow1/on_search_inc_refresh.json
Futuresoft/SellerApp/ONDC_RET15/Flow1/search_full_catalog_refresh.json
Futuresoft/SellerApp/ONDC_RET15/Flow1/search_inc_refresh.json
Futuresoft/SellerApp/ONDC_RET15/Utility/Flow1/Payload.json
Futuresoft/SellerApp/ONDC_RET15/Utility/Flow1/Response.json

issue resolved for appliances domain
Note: Please check the issue board for the invalid issue.

issue resolved for appliances domain

---

yuukke/RET10/IGM/FLOW1/ret_issue.json
yuukke/RET10/IGM/FLOW1/ret_issue_close.json
yuukke/RET10/IGM/FLOW1/ret_issue_status.json
yuukke/RET10/IGM/FLOW1/ret_on_issue.json
yuukke/RET10/IGM/FLOW1/ret_on_issue_status.json
yuukke/RET10/IGM/FLOW2/ret_issue.json
yuukke/RET10/IGM/FLOW2/ret_issue_close.json
yuukke/RET10/IGM/FLOW2/ret_issue_status.json
yuukke/RET10/IGM/FLOW2/ret_on_issue.json
yuukke/RET10/IGM/FLOW2/ret_on_issue_status.json

IGM Issue resolved

---

Squadcube/RSF-2.0/Flow-1/01_settle.json
Squadcube/RSF-2.0/Flow-1/02_on_settle.json
Squadcube/RSF-2.0/Flow-1/03_report.json
Squadcube/RSF-2.0/Flow-1/04_on_report.json
Squadcube/RSF-2.0/Flow-2/01_settle.json
Squadcube/RSF-2.0/Flow-2/02_on_settle.json
Squadcube/RSF-2.0/Flow-2/03_report.json
Squadcube/RSF-2.0/Flow-2/04_on_report.json
Squadcube/RSF-2.0/Flow-2/05_recon.json
Squadcube/RSF-2.0/Flow-2/06_on_recon.json
Squadcube/RSF-2.0/Flow-2/07_settle.json
Squadcube/RSF-2.0/Flow-2/08_on_settle.json
Squadcube/RSF-2.0/Flow-3/01_settle.json
Squadcube/RSF-2.0/Flow-3/02_on_settle.json
Squadcube/RSF-2.0/Flow-3/03_report.json
Squadcube/RSF-2.0/Flow-3/04_on_report.json
Squadcube/RSF-2.0/Flow-3/05_recon.json
Squadcube/RSF-2.0/Flow-3/06_on_recon.json
Squadcube/RSF-2.0/Flow-4/01_settle.json
Squadcube/RSF-2.0/Flow-4/02_on_settle.json
Squadcube/RSF-2.0/Flow-4/03_report.json
Squadcube/RSF-2.0/Flow-4/04_on_report.json
Squadcube/RSF-2.0/Flow-5/01_settle.json
Squadcube/RSF-2.0/Flow-5/02_on_settle.json

The mentioned RSF issues are resolved.
https://github.com/ONDC-Official/v1.2.0-logs/issues/2944

RSF FLow logs Updated

---

ekart/IGM/issue_close.json
ekart/IGM/issue_create.json
ekart/IGM/issue_status_resolved.json
ekart/IGM/on_issue_create.json
ekart/IGM/on_issue_status_resolved.json

Log issue fixed https://github.com/ONDC-Official/v1.2.0-logs/issues/3134

Ekart Logistics seller provider IGM logs

---

Easy Pay/BuyerApp/Agriculture-Flow1/on_search_full_catalog_refresh.json
Easy Pay/BuyerApp/Agriculture-Flow1/on_search_inc_refresh.json
Easy Pay/BuyerApp/Agriculture-Flow1/search_full_catalog_refresh.json
Easy Pay/BuyerApp/Agriculture-Flow1/search_inc_refresh.json

EasyPay Buyer App: Agriculture flow 1 Logs update

EasyPay Buyer App: Agriculture flow 1 Logs update

---

Squadcube/RET-10/Flow-1/on_search_full_catalog_refresh.json
Squadcube/RET-10/Flow-1/on_search_inc_refresh.json
Squadcube/RET-10/Flow-1/report.json
Squadcube/RET-10/Flow-1/search_full_catalog_refresh.json
Squadcube/RET-10/Flow-1/search_inc_refresh.json

Hi Team,
I have resolved the Grocery domain issues mentioned in https://github.com/ONDC-Official/v1.2.0-logs/issues/3145

Squadcube ( SA:RET10) Flow-1 Bug fixes

---

yuukke/RET16/on_search_inc_refresh.json
yuukke/RET16/search_full_catalog_refresh.json
yuukke/RET16/search_inc_refresh.json

 RET16 Log Correction done

---

Squadcube/RSF-2.0/Flow-2/01_settle.json
Squadcube/RSF-2.0/Flow-2/02_on_settle.json
Squadcube/RSF-2.0/Flow-2/03_report.json
Squadcube/RSF-2.0/Flow-2/04_on_report.json
Squadcube/RSF-2.0/Flow-2/05_recon.json
Squadcube/RSF-2.0/Flow-2/07_settle.json
Squadcube/RSF-2.0/Flow-2/08_on_settle.json

Fixed the Flow-2 Bug fixes as mentioned in the Complaince - https://github.com/ONDC-Official/v1.2.0-logs/issues/2944

Squadcube SA (RSF-2.0) Flow-2 Bug fixes

---

Futuresoft/SellerApp/ONDC_RET16/Flow1/on_search_full_catalog_refresh.json
Futuresoft/SellerApp/ONDC_RET16/Flow1/on_search_inc_refresh.json
Futuresoft/SellerApp/ONDC_RET16/Flow1/search_full_catalog_refresh.json
Futuresoft/SellerApp/ONDC_RET16/Flow1/search_inc_refresh.json
Futuresoft/SellerApp/ONDC_RET16/Utility/Flow1/Payload.json
Futuresoft/SellerApp/ONDC_RET16/Utility/Flow1/Response.json

Pls note: we have already cleared Ret10, 12 and 15 logs. Please help to clear RET16 asap.

home and kitchen log

---

KiranaPro/BUYER-APP/Pramaan Logs/FLOW 1 A.json
KiranaPro/BUYER-APP/Pramaan Logs/FLOW 2.json
KiranaPro/BUYER-APP/Pramaan Logs/FLOW 3A.json
KiranaPro/BUYER-APP/Pramaan Logs/FLOW 4 B.json
KiranaPro/BUYER-APP/Pramaan Logs/FLOW 4A.json
KiranaPro/BUYER-APP/Pramaan Logs/FLOW 7.json
KiranaPro/BUYER-APP/Pramaan Logs/Flow 6.json
KiranaPro/BUYER-APP/Pramaan Logs/flow 1 B.json
KiranaPro/BUYER-APP/Pramaan Logs/flow 3b.json
KiranaPro/BUYER-APP/Pramaan Logs/flow 5.json
KiranaPro/BUYER-APP/Pramaan Logs/flow 8.json
KiranaPro/BUYER-APP/Pramaan Logs/flow 9.json

This PR contains all the logs generated using the Pramaan utility.

KiranaPro Pramaan Logs

---

Fynd/SellerApp/RET18/on_search_full_catalog.json
Fynd/SellerApp/RET18/search_full_catalog.json

Added RET18

---

yuukke/RET16/on_search_full_catalog_refresh.json
yuukke/RET16/on_search_inc_refresh.json
yuukke/RET16/search_full_catalog_refresh.json
yuukke/RET16/search_inc_refresh.json

Ret16 correction done

---

Zoho/RSF_v2/flow1/on_report.json
Zoho/RSF_v2/flow1/on_settle.json
Zoho/RSF_v2/flow1/report.json
Zoho/RSF_v2/flow1/settle.json
Zoho/RSF_v2/flow2/on_recon.json
Zoho/RSF_v2/flow2/on_report.json
Zoho/RSF_v2/flow2/on_settle.json
Zoho/RSF_v2/flow2/recon.json
Zoho/RSF_v2/flow2/report.json
Zoho/RSF_v2/flow2/settle.json
Zoho/RSF_v2/flow3/on_recon.json
Zoho/RSF_v2/flow3/on_report.json
Zoho/RSF_v2/flow3/on_settle.json
Zoho/RSF_v2/flow3/recon.json
Zoho/RSF_v2/flow3/report.json
Zoho/RSF_v2/flow3/settle.json
Zoho/RSF_v2/flow4/on_settle.json
Zoho/RSF_v2/flow4/settle.json
Zoho/RSF_v2/flow5/on_settle.json
Zoho/RSF_v2/flow5/settle.json

add vikra-rsf logs

---

Lekhha/IGM for Retail Seller/Flow 2/step 1a: ret_issue (buyer creates issue).json
Lekhha/IGM for Retail Seller/Flow 2/step 1b: ret_on_issue (seller marks as processing).json
Lekhha/IGM for Retail Seller/Flow 2/step 2: ret_on_issue (seller proposes resolution options).json
Lekhha/IGM for Retail Seller/Flow 2/step 3: ret_issue (buyer escalates).json
Lekhha/IGM for Retail Seller/Flow 2/step 4: ret_on_issue (seller marks escalation as processing).json
Lekhha/IGM for Retail Seller/Flow 2/step 5: ret_on_issue (seller proposes resolution options).json
Lekhha/IGM for Retail Seller/Flow 2/step 6: ret_issue (buyer accepts resolution).json
Lekhha/IGM for Retail Seller/Flow 2/step 7: ret_on_issue (seller resolves).json
Lekhha/IGM for Retail Seller/Flow 2/step 8: ret_issue (buyer marks as closed).json
Lekhha/RSF for Retail Seller/Flow 1/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 1/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 1/step 2a report (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 1/step 2b on_report (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 2/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 2 recon (receiver-buyer to collector-seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 3 on_recon (collector-seller to receiver-buyer).json
Lekhha/RSF for Retail Seller/Flow 2/step 4a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 2/step 4b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 3/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 2 recon (receiver-buyer to collector-seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 3 on_recon (collector-seller to receiver-buyer).json
Lekhha/RSF for Retail Seller/Flow 4/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 4/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 5/step 1a settle (seller to SA)
Lekhha/RSF for Retail Seller/Flow 5/step 1b on_settle (SA to seller)

RSF logs for Retail Seller in domain ONDC:RET10

RSF + IGM (Flow 2) logs for Retail Seller in domain ONDC:RET10

---

Zoho/RSF_v2/flow1/on_report.json
Zoho/RSF_v2/flow1/on_settle.json
Zoho/RSF_v2/flow1/report.json
Zoho/RSF_v2/flow1/settle.json

fix context.ttl #3265

---

ekart/IGM/issue_close.json
ekart/IGM/issue_create.json
ekart/IGM/issue_status_resolved.json
ekart/IGM/on_issue_create.json
ekart/IGM/on_issue_status_resolved.json

Log issue fixed https://github.com/ONDC-Official/v1.2.0-logs/issues/3192

Ekart Logistics seller provider IGM

---

Sequelstring/IGM-2.0/Flow 1/issue_1_open.json
Sequelstring/IGM-2.0/Flow 1/issue_2_sharing_more_info.json
Sequelstring/IGM-2.0/Flow 1/issue_3_selecting_resolution.json
Sequelstring/IGM-2.0/Flow 1/issue_4_closed.json
Sequelstring/IGM-2.0/Flow 1/on_issue_1_processing.json
Sequelstring/IGM-2.0/Flow 1/on_issue_2_need_info.json
Sequelstring/IGM-2.0/Flow 1/on_issue_2_processing.json
Sequelstring/IGM-2.0/Flow 1/on_issue_2_resolution_options.json
Sequelstring/IGM-2.0/Flow 1/on_issue_resolved.json

IGM 2.0 Logs 

---

Easy Pay/BuyerApp/RSF2.0/Flow1/on_report.json
Easy Pay/BuyerApp/RSF2.0/Flow1/on_settel.json
Easy Pay/BuyerApp/RSF2.0/Flow1/report.json
Easy Pay/BuyerApp/RSF2.0/Flow1/settle.json
Easy Pay/BuyerApp/RSF2.0/Flow2/on_recon.json
Easy Pay/BuyerApp/RSF2.0/Flow2/on_report.json
Easy Pay/BuyerApp/RSF2.0/Flow2/on_settle.json
Easy Pay/BuyerApp/RSF2.0/Flow2/recon.json
Easy Pay/BuyerApp/RSF2.0/Flow2/report.json
Easy Pay/BuyerApp/RSF2.0/Flow2/settle.json
Easy Pay/BuyerApp/RSF2.0/Flow2/settle_reinitiate.json
Easy Pay/BuyerApp/RSF2.0/Flow3/on_recon.json
Easy Pay/BuyerApp/RSF2.0/Flow3/on_report.json
Easy Pay/BuyerApp/RSF2.0/Flow3/on_settle.json
Easy Pay/BuyerApp/RSF2.0/Flow3/recon.json
Easy Pay/BuyerApp/RSF2.0/Flow3/report.json
Easy Pay/BuyerApp/RSF2.0/Flow3/settle.json
Easy Pay/BuyerApp/RSF2.0/Flow4/on_settle.json
Easy Pay/BuyerApp/RSF2.0/Flow4/settle.json

EasyPay Buyer App RSF 2.0 Log update

EasyPay Buyer App RSF 2.0 Log update

---

Easy Pay/SellerApp/RSF-2.0.0/Flow - 1/on_report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 1/on_settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 1/report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 1/settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/on_recon.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/on_report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/on_settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/on_settle_reinitiate.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/recon.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/settle_reinitiate.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/on_recon.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/on_report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/on_settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/recon.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 4/on_settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 4/settle.json

RSF Flow 1 to 4 for Easy Pay Seller NP

RSF Flow 1 to 4 for Easy Pay Seller NP

---

Lekhha/RSF for Retail Seller/Flow 1/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 1/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 1/step 2a report (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 1/step 2b on_report (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 2/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 1c report (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 2/step 1d on_report (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 2 recon (receiver-buyer to collector-seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 3 on_recon (collector-seller to receiver-buyer).json
Lekhha/RSF for Retail Seller/Flow 2/step 4a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 2/step 4b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 3/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 1c report (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 3/step 1d on_report (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 2 recon (receiver-buyer to collector-seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 3 on_recon (collector-seller to receiver-buyer).json

RSF: Re-submitting Flow 1, 2 and 3 logs for Retail Seller in domain ONDC:RET10

RSF: Re-submitting Flow 1, 2 and 3 logs for Retail Seller in domain ONDC:RET10

---

SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/1_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/2_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/3_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/4_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/5_issue_status.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/6_on_issue_status.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/7_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/8_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/1_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/2_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/3_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/4_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/5_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/6_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/7_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/8_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 2/9_issue.json

Hello,
I have added Flow 1 and Flow 2 logs for IGM 2.0, Please review
cc
rishabhnand.singh@ondc.org

Added SimtelAI IGM v2.0 logs

---

Lekhha/RSF for Retail Seller/Flow 1/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 1/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 1/step 2a report (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 1/step 2b on_report (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 2/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 1c report (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 2/step 1d on_report (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 2 recon (receiver-buyer to collector-seller).json
Lekhha/RSF for Retail Seller/Flow 2/step 3 on_recon (collector-seller to receiver-buyer).json
Lekhha/RSF for Retail Seller/Flow 2/step 4a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 2/step 4b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 1a settle (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 3/step 1b on_settle (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 1c report (seller to SA).json
Lekhha/RSF for Retail Seller/Flow 3/step 1d on_report (SA to seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 2 recon (receiver-buyer to collector-seller).json
Lekhha/RSF for Retail Seller/Flow 3/step 3 on_recon (collector-seller to receiver-buyer).json

Re-submitting RSF Flow 1, 2 and 3 logs

Re-submitting RSF Flow 1, 2 and 3 logs

---

Easy Pay/SellerApp/RSF-2.0.0/Flow - 1/on_report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 1/on_settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 1/report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 1/settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/on_recon.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/on_report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/on_settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/on_settle_reinitiate.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/recon.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 2/settle_reinitiate.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/on_recon.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/on_report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/on_settle.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/recon.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/report.json
Easy Pay/SellerApp/RSF-2.0.0/Flow - 3/settle.json

Easy Pay - Seller: RSF Observation Resolved for Flow 1 to 3

Easy Pay - Seller: RSF Observation Resolved for Flow 1 to 3

---

ShopEG/RSF 2.0 - with mock server/Flow 1/on_report.json
ShopEG/RSF 2.0 - with mock server/Flow 1/on_settle.json
ShopEG/RSF 2.0 - with mock server/Flow 1/report.json
ShopEG/RSF 2.0 - with mock server/Flow 1/settle.json
ShopEG/RSF 2.0 - with mock server/Flow 2/on_recon.json
ShopEG/RSF 2.0 - with mock server/Flow 2/on_report.json
ShopEG/RSF 2.0 - with mock server/Flow 2/on_settle.json
ShopEG/RSF 2.0 - with mock server/Flow 2/on_settle_reinitiate.json
ShopEG/RSF 2.0 - with mock server/Flow 2/recon.json
ShopEG/RSF 2.0 - with mock server/Flow 2/report.json
ShopEG/RSF 2.0 - with mock server/Flow 2/settle.json
ShopEG/RSF 2.0 - with mock server/Flow 2/settle_reinitiate.json
ShopEG/RSF 2.0 - with mock server/Flow 3/on_recon.json
ShopEG/RSF 2.0 - with mock server/Flow 3/on_report.json
ShopEG/RSF 2.0 - with mock server/Flow 3/on_settle.json
ShopEG/RSF 2.0 - with mock server/Flow 3/recon.json
ShopEG/RSF 2.0 - with mock server/Flow 3/report.json
ShopEG/RSF 2.0 - with mock server/Flow 3/settle.json
ShopEG/RSF 2.0 - with mock server/Flow 4/on_settle.json
ShopEG/RSF 2.0 - with mock server/Flow 4/settle.json

RSF 1.0 approval: [https://github.com/ONDC-Official/v1.2.0-logs/issues/937#issuecomment-2055953582](https://github.com/ONDC-Official/v1.2.0-logs/issues/937#issuecomment-2055953582)
RSF 1.0 logs: [https://github.com/ONDC-Official/v1.2.0-logs/tree/master/ShopEG/RSF%20-%20With%20local%20mock%20server](https://github.com/ONDC-Official/v1.2.0-logs/tree/master/ShopEG/RSF%20-%20With%20local%20mock%20server)

ShopEG: SA RSF 2.0 logs

---

OGOSHOP/RSF/FLOW_1/1_settle.json
OGOSHOP/RSF/FLOW_1/2_on_settle.json
OGOSHOP/RSF/FLOW_1/3_report.json
OGOSHOP/RSF/FLOW_1/4_on_report.json
OGOSHOP/RSF/FLOW_2/1_settle.json
OGOSHOP/RSF/FLOW_2/2_on_settle.json
OGOSHOP/RSF/FLOW_2/3_report.json
OGOSHOP/RSF/FLOW_2/4_on_report.json
OGOSHOP/RSF/FLOW_2/5_recon.json
OGOSHOP/RSF/FLOW_2/6_on_recon.json
OGOSHOP/RSF/FLOW_2/7_settle.json
OGOSHOP/RSF/FLOW_2/8_on_settle.json
OGOSHOP/RSF/FLOW_3/1_settle.json
OGOSHOP/RSF/FLOW_3/2_on_settle.json
OGOSHOP/RSF/FLOW_3/3_report.json
OGOSHOP/RSF/FLOW_3/4_on_report.json
OGOSHOP/RSF/FLOW_3/5_recon.json
OGOSHOP/RSF/FLOW_3/6_on_recon.json
OGOSHOP/RSF/FLOW_4/1_settle.json
OGOSHOP/RSF/FLOW_4/2_on_settle.json

Seller RSF 2.0 logs

---

SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/10_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/11_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/1_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/2_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/5_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/6_issue_status.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/7_on_issue_status.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/8_on_issue.json
SimtelAI/BuyerApp/RET14/IGMv2/Flow 1/9_issue.json

Please merge to master, IGM v2 changes, to flow1

Changed flow 1 to incorporate changes

---

OGOSHOP/IGM/FLOW_1/10_ret_on_issue.json
OGOSHOP/IGM/FLOW_1/11_ret_issue.json
OGOSHOP/IGM/FLOW_1/1_ret_issue.json
OGOSHOP/IGM/FLOW_1/2_ret_on_issue.json
OGOSHOP/IGM/FLOW_1/3_ret_issue_status.json
OGOSHOP/IGM/FLOW_1/4_ret_on_issue_status.json
OGOSHOP/IGM/FLOW_1/5_ret_on_issue.json
OGOSHOP/IGM/FLOW_1/6_ret_issue.json
OGOSHOP/IGM/FLOW_1/7_ret_on_issue.json
OGOSHOP/IGM/FLOW_1/8_ret_on_issue.json
OGOSHOP/IGM/FLOW_1/9_ret_issue.json
OGOSHOP/IGM/FLOW_2/10_ret_on_issue_status.json
OGOSHOP/IGM/FLOW_2/11_ret_issue.json
OGOSHOP/IGM/FLOW_2/1_ret_issue.json
OGOSHOP/IGM/FLOW_2/2_ret_on_issue.json
OGOSHOP/IGM/FLOW_2/3_ret_on_issue.json
OGOSHOP/IGM/FLOW_2/4_ret_issue.json
OGOSHOP/IGM/FLOW_2/5_ret_on_issue.json
OGOSHOP/IGM/FLOW_2/6_ret_on_issue.json
OGOSHOP/IGM/FLOW_2/7_ret_issue.json
OGOSHOP/IGM/FLOW_2/8_ret_on_issue.json
OGOSHOP/IGM/FLOW_2/9_ret_issue_status.json

IGM 2.0 logs

---

OGOSHOP/RSF/FLOW_3/1_settle.json
OGOSHOP/RSF/FLOW_3/2_on_settle.json
OGOSHOP/RSF/FLOW_3/3_report.json
OGOSHOP/RSF/FLOW_3/4_on_report.json
OGOSHOP/RSF/FLOW_3/5_recon.json
OGOSHOP/RSF/FLOW_3/6_on_recon.json

RSF2.0 flow 3 resubmit 

---

Aekiva/RET13/FLOW 1/log_validation_utility.json
Aekiva/RET13/FLOW 1/on_search_full_catalog_refresh.json
Aekiva/RET13/FLOW 1/on_search_inc_refresh.json
Aekiva/RET13/FLOW 1/search_full_catalog_refresh.json
Aekiva/RET13/FLOW 1/search_inc_refresh.json
Aekiva/RET16/FLOW 1/log_validation_utility.json
Aekiva/RET16/FLOW 1/on_search_full_catalog_refresh.json
Aekiva/RET16/FLOW 1/on_search_inc_refresh.json
Aekiva/RET16/FLOW 1/search_full_catalog_refresh.json
Aekiva/RET16/FLOW 1/search_inc_refresh.json
Aekiva/RET18/FLOW 1/log_validation_utility.json
Aekiva/RET18/FLOW 1/on_search_full_catalog_refresh.json
Aekiva/RET18/FLOW 1/on_search_inc_refresh.json
Aekiva/RET18/FLOW 1/search_full_catalog_refresh.json
Aekiva/RET18/FLOW 1/search_inc_refresh.json

Added logs for Aekiva for FLOW 1 of RET13 RET16 and RET18

Added logs for FLOW 1 of RET13 RET16 and RET18

---

Sequelstring/RSF-2.0/on_recon_1.json
Sequelstring/RSF-2.0/on_recon_2.json
Sequelstring/RSF-2.0/recon_1.json
Sequelstring/RSF-2.0/recon_2.json

Submitting tech logs for RSF 2.0

RSF 2.0 Logs Sequelstring

---

Pradivya_23Jan2025/Flow6/on_report.json
Pradivya_23Jan2025/Flow6/on_update_liquidated.json
Pradivya_23Jan2025/Flow6/on_update_part_cancel.json
Pradivya_23Jan2025/Flow6/report.json
Pradivya_23Jan2025/Flow6/update_liquidated.json
Pradivya_23Jan2025/Flow6/update_settlement_liquidated.json
Pradivya_23Jan2025/Flow6/update_settlement_part_cancel.json
Pradivya_23Jan2025/IGM/Flow1/issue_closed.json
Pradivya_23Jan2025/IGM/Flow1/issue_status.json
Pradivya_23Jan2025/IGM/Flow1/on_report.json
Pradivya_23Jan2025/IGM/Flow1/report.json

Pradivya Buyer app logs for REt10 Domain

---

SimtelAI/BuyerApp/RET13/Flow 1/1_search_full_catalog_refresh.json
SimtelAI/BuyerApp/RET13/Flow 1/2_on_search_full_catalog_refresh.json
SimtelAI/BuyerApp/RET13/Flow 1/3_search_inc_refresh.json
SimtelAI/BuyerApp/RET13/Flow 1/4_on_search_inc_refresh.json
SimtelAI/BuyerApp/RET13/Flow 1/report.json
SimtelAI/BuyerApp/RET15/Flow 1/1_search_full_catalog_refresh.json
SimtelAI/BuyerApp/RET15/Flow 1/2_on_search_full_catalog_refresh.json
SimtelAI/BuyerApp/RET15/Flow 1/3_search_inc_refresh.json
SimtelAI/BuyerApp/RET15/Flow 1/4_on_search_inc_refresh.json
SimtelAI/BuyerApp/RET15/Flow 1/report.json
SimtelAI/BuyerApp/RET16/Flow 1/1_search_full_catalog_refresh.json
SimtelAI/BuyerApp/RET16/Flow 1/2_on_search_full_catalog_refresh.json
SimtelAI/BuyerApp/RET16/Flow 1/3_search_inc_refresh.json
SimtelAI/BuyerApp/RET16/Flow 1/4_on_search_inc_refresh.json
SimtelAI/BuyerApp/RET16/Flow 1/report.json

Dear ONDC team,
Please review and merge the RET13, RET15 and RET16 Flow 1 logs
thanks,
Ravi Kaushik
+91 9513333472

Added RET13, RET15, and RET16 Flow 1

---

Futuresoft/SellerApp/RSF 2.0.0/Flow1/1_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow1/2_on_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow1/3_report.json
Futuresoft/SellerApp/RSF 2.0.0/Flow1/4_on_report.json
Futuresoft/SellerApp/RSF 2.0.0/Flow2/1_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow2/2_on_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow2/3_report.json
Futuresoft/SellerApp/RSF 2.0.0/Flow2/4_on_report.json
Futuresoft/SellerApp/RSF 2.0.0/Flow2/5_recon.json
Futuresoft/SellerApp/RSF 2.0.0/Flow2/6_on_recon.json
Futuresoft/SellerApp/RSF 2.0.0/Flow2/7_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow2/8_on_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow3/1_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow3/2_on_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow3/3_report.json
Futuresoft/SellerApp/RSF 2.0.0/Flow3/4_on_report.json
Futuresoft/SellerApp/RSF 2.0.0/Flow3/5_recon.json
Futuresoft/SellerApp/RSF 2.0.0/Flow3/6_on_recon.json
Futuresoft/SellerApp/RSF 2.0.0/Flow4/1_settle.json
Futuresoft/SellerApp/RSF 2.0.0/Flow4/2_on_settle.json

Please clear the logs asap. I have resolved all of the issues.

Futuresoft: RSF 2.0.0

---

Pradivya_23Jan2025/RSF/Flow1/on_report.json
Pradivya_23Jan2025/RSF/Flow1/on_settle.json
Pradivya_23Jan2025/RSF/Flow1/report.json
Pradivya_23Jan2025/RSF/Flow1/settle.json
Pradivya_23Jan2025/RSF/Flow2/on_recon.json
Pradivya_23Jan2025/RSF/Flow2/on_report.json
Pradivya_23Jan2025/RSF/Flow2/on_settle.json
Pradivya_23Jan2025/RSF/Flow2/on_settle_success.json
Pradivya_23Jan2025/RSF/Flow2/recon.json
Pradivya_23Jan2025/RSF/Flow2/report.json
Pradivya_23Jan2025/RSF/Flow2/settle.json
Pradivya_23Jan2025/RSF/Flow2/settle_success.json
Pradivya_23Jan2025/RSF/Flow3/on_recon.json
Pradivya_23Jan2025/RSF/Flow3/on_report.json
Pradivya_23Jan2025/RSF/Flow3/on_settle.json
Pradivya_23Jan2025/RSF/Flow3/recon.json
Pradivya_23Jan2025/RSF/Flow3/report.json
Pradivya_23Jan2025/RSF/Flow3/settle.json
Pradivya_23Jan2025/RSF/Flow4/on_settle.json
Pradivya_23Jan2025/RSF/Flow4/settle.json
Pradivya_23Jan2025/RSF/Flow5/on_settle.json
Pradivya_23Jan2025/RSF/Flow5/settle.json

Pradivya Buyer App Logs for RET10 Domain RSF Logs

---

shopalyst/phase-1/IGM/flow-1/1-issue_created.json
shopalyst/phase-1/IGM/flow-1/10-on_issue_resolved.json
shopalyst/phase-1/IGM/flow-1/11-issue_closed.json
shopalyst/phase-1/IGM/flow-1/2-on_issue_processing.json
shopalyst/phase-1/IGM/flow-1/3-on_issue_need_more_info.json
shopalyst/phase-1/IGM/flow-1/4-issue_info_provided.json
shopalyst/phase-1/IGM/flow-1/5-on_issue_processing_2.json
shopalyst/phase-1/IGM/flow-1/6-issue_status.json
shopalyst/phase-1/IGM/flow-1/7-on_issue_status.json
shopalyst/phase-1/IGM/flow-1/8-on_issue_resolution_proposed.json
shopalyst/phase-1/IGM/flow-1/9-issue_resolution_accepted.json
shopalyst/phase-1/IGM/flow-2/1-issue_created.json
shopalyst/phase-1/IGM/flow-2/2-on_issue_processing.json
shopalyst/phase-1/IGM/flow-2/3-on_issue_resolution_proposed.json
shopalyst/phase-1/IGM/flow-2/4.-issue-escalated.json
shopalyst/phase-1/IGM/flow-2/5-on_issue_processing.json
shopalyst/phase-1/IGM/flow-2/6-on_issue_resolution_proposed.json
shopalyst/phase-1/IGM/flow-2/7-issue_resolution_accepted.json
shopalyst/phase-1/IGM/flow-2/8-on_issue_resolved.json
shopalyst/phase-1/IGM/flow-2/9-issue_closed.json
shopalyst/phase-1/IGM/flow-3/1-issue.json
shopalyst/phase-1/IGM/flow-3/2.on_issue_processing.json
shopalyst/phase-1/IGM/flow-3/3.on_issue_resolution_proposed.json
shopalyst/phase-1/IGM/flow-3/4.issue_resolution_accepted.json
shopalyst/phase-1/IGM/flow-3/5.on_issue_resolved.json

updated flow-1 , flow-2 and added flow-3
issue thread link - [Link](https://github.com/ONDC-Official/v1.2.0-logs/issues/3373#issuecomment-2742145460:~:text=While%20testing%20Flow,we%20consider%20here%20%3F)

Shopalyst IGM 2.0.0 (BPP) 

---

agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/issue_closed.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/issue_info_provided.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/issue_open.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/issue_resolution_accepted.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/log_validation_utility_report.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/on_issue_info_required.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/on_issue_processing_1.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/on_issue_processing_2.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/on_issue_resolution_proposed.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.1/on_issue_resolved.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/issue_close.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/issue_escalated.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/issue_open.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/issue_resolution_accepted_1.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/issue_resolution_accepted_2.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/log_validation_utility_report.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/on_issue_gro_processing.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/on_issue_gro_resolution_proposed.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/on_issue_gro_resolved.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/on_issue_processing.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/on_issue_resolution_proposed.json
agrikheti/BuyerApp/IGM 2.0/FLOW NO.2/on_issue_resolved.json

Adding flow for IGM 2.0

---

STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/issue_close.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/issue_esclated.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/issue_open.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/issue_resolution_accepted.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/log_validation_response.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/on_issue_gro_processing.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/on_issue_gro_resolution_proposed.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/on_issue_gro_resolved.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/on_issue_processing.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/on_issue_resolution_proposed.json
STS(SYNERGY_TECHNOLOGY_SERVICES)/Seller_APP/RET14/IGM/Flow2/on_issue_resolved.json

@amitsinha07
We have fixed timestamp validation in Flow 2. But for issue_closed we are sending valid timestamp then also error is visible.

STS Electronics RET14 IGM Flow 2 Resolved timestamp validation Issue

---

Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/1. issue_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/10. on_issue_resolved_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/11. issue_closed_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/2. on_issue_processing_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/3. on_issue_info_req_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/4. issue_info_provided_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/5. on_issue_processing_2.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/6. issue_status_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/7. on_issue_status.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/8. on_issue_resolution_op_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow A/9. issue_resolution_acpt_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/1. issue_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/2. on_issue_processing_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/3. on_issue_resolution_op_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/4. issue_escalated.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/5. on_issue_processing_2.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/6. on_issue_gro_resolutions_op_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/7. issue_resolution_acpt_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/8. on_issue_resolved_1.json
Aurikatech/Seller App/ONDC RET 12/IGM 2.0/Flow B/9. issue_closed_1.json

- both flow-a and flow-b added for igm 2.0, Aurikatech, Seller-App

Aurikatech-SellerApp IGM 2.0 logs

---

Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 1 (NP to NP successful fund movement)/1.settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 1 (NP to NP successful fund movement)/2.on_settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/1. settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/2. on_settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/3. report.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/4. on_report.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/5. recon_received.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/6. on_recon.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/7. settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/8. on_settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 3 (Unsuccessful Fund Movement With Collector Disagreeing)/1. settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 3 (Unsuccessful Fund Movement With Collector Disagreeing)/2. on_settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 3 (Unsuccessful Fund Movement With Collector Disagreeing)/3. report.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 3 (Unsuccessful Fund Movement With Collector Disagreeing)/4. on_report.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 3 (Unsuccessful Fund Movement With Collector Disagreeing)/5. recon_received.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 3 (Unsuccessful Fund Movement With Collector Disagreeing)/6. on_recon.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 4 (Miscellaneous Fund Movement)/1.settle.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 4 (Miscellaneous Fund Movement)/2.on_settle.json

Hi there,
We have added new logs of rsf v2.
Please approve our PR.
Thanks.

Tipplr SA-Added RSF v2 logs

---

Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 1 (NP to NP successful fund movement)/log_validation_response.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 2 (Unsuccessful Fund Movement With Collector Agreeing)/log_validation_response.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 3 (Unsuccessful Fund Movement With Collector Disagreeing)/log_validation_response.json
Tipplr/Tipplr-Seller-App-RSFv2/RSF2.0(APR-04)/Flow 4 (Miscellaneous Fund Movement)/log_validation_response.json

Hi there,
Was asked to add log validation resp file for each flow based on #3480 .
Please merge.

Tipplr SA-RSF v2-Added log validation res file

---

smartsell_samitha/IGM/Flow-1/flow-1_validate_report.json
smartsell_samitha/IGM/Flow-1/flow-1_validate_request.json
smartsell_samitha/RSF/Flow-1/flow-1_validate_report.json
smartsell_samitha/RSF/Flow-1/flow-1_validate_request.json
smartsell_samitha/RSF/Flow-1/on_report.json
smartsell_samitha/RSF/Flow-1/on_settle.json
smartsell_samitha/RSF/Flow-1/report.json
smartsell_samitha/RSF/Flow-1/settle.json
smartsell_samitha/RSF/Flow-2/flow-2_validate_report.json
smartsell_samitha/RSF/Flow-2/flow-2_validate_request.json
smartsell_samitha/RSF/Flow-2/on_recon.json
smartsell_samitha/RSF/Flow-2/on_report.json
smartsell_samitha/RSF/Flow-2/on_settle.json
smartsell_samitha/RSF/Flow-2/on_settle_reinitialized.json
smartsell_samitha/RSF/Flow-2/recon.json
smartsell_samitha/RSF/Flow-2/report.json
smartsell_samitha/RSF/Flow-2/settle.json
smartsell_samitha/RSF/Flow-2/settle_reinitialized.json
smartsell_samitha/RSF/Flow-3/flow-3_validate_report.json
smartsell_samitha/RSF/Flow-3/flow-3_validate_request.json
smartsell_samitha/RSF/Flow-3/on_recon.json
smartsell_samitha/RSF/Flow-3/on_report.json
smartsell_samitha/RSF/Flow-3/on_settle.json
smartsell_samitha/RSF/Flow-3/recon.json
smartsell_samitha/RSF/Flow-3/report.json
smartsell_samitha/RSF/Flow-3/settle.json
smartsell_samitha/RSF/Flow-4/flow-4_validate_report.json
smartsell_samitha/RSF/Flow-4/flow-4_validate_request.json
smartsell_samitha/RSF/Flow-4/on_settle.json
smartsell_samitha/RSF/Flow-4/settle.json

Log updated for IGM & RSF

---

Easy Pay/BuyerApp/RSF2.0/Flow1/log_validation_response.json
Easy Pay/BuyerApp/RSF2.0/Flow2/log_validation_response.json
Easy Pay/BuyerApp/RSF2.0/Flow2/settle_reinitiate.json
Easy Pay/BuyerApp/RSF2.0/Flow3/log_validation_response.json
Easy Pay/BuyerApp/RSF2.0/Flow4/log_validation_response.json
Easy Pay/BuyerApp/RSF2.0/Flow4/on_settle.json
Easy Pay/BuyerApp/RSF2.0/Flow4/settle.json
Easy Pay/BuyerApp/RSF2.0/Flow5/log_validation_response.json
Easy Pay/BuyerApp/RSF2.0/Flow5/on_settle.json
Easy Pay/BuyerApp/RSF2.0/Flow5/settle.json

EasyPay Buyer App - RSF 2.0 Log update

EasyPay Buyer App - RSF 2.0 Log update

---

Aurikatech/Buyer App/ONDC RET 10/CORE-APIS/Flow 1/on_search_full_catalog_refresh.json
Aurikatech/Buyer App/ONDC RET 10/CORE-APIS/Flow 1/on_search_inc_refresh.json
Aurikatech/Buyer App/ONDC RET 10/CORE-APIS/Flow 1/response.json
Aurikatech/Buyer App/ONDC RET 10/CORE-APIS/Flow 1/search_full_catalog_refresh.json
Aurikatech/Buyer App/ONDC RET 10/CORE-APIS/Flow 1/search_inc_refresh.json

- updated latest response from log validation utility

Retail logs added for ONDC:RET10, flow 1

---

Mobibharat/Retail/Buyer-App/IGM/Flow_1/1_issue_open.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/2.on_issue_processing-1.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/3.on_issue_info_required.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/4.issue_info_provided.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/5.on_issue_processing-2.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/6.on_issue_resolution_proposed.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/7.issue_resolution_accepted.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/8.on_issue_resolved.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/9.issue_closed.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/utility_payload.json
Mobibharat/Retail/Buyer-App/IGM/Flow_1/utility_response.json

This pull request includes the submission of IGM (Issue, Grievance, and Monitoring) logs for the RET10 domain as per ONDC protocol requirements.

Submit IGM Logs for ONDC RET10 Domain Compliance

---

Tata_Buyer_RSF2.0_Logs/Flow1/on_report.json
Tata_Buyer_RSF2.0_Logs/Flow1/on_settle.json
Tata_Buyer_RSF2.0_Logs/Flow1/report.json
Tata_Buyer_RSF2.0_Logs/Flow1/settle.json
Tata_Buyer_RSF2.0_Logs/Flow2/on_recon.json
Tata_Buyer_RSF2.0_Logs/Flow2/on_report.json
Tata_Buyer_RSF2.0_Logs/Flow2/on_settle1.json
Tata_Buyer_RSF2.0_Logs/Flow2/on_settle2.json
Tata_Buyer_RSF2.0_Logs/Flow2/recon.json
Tata_Buyer_RSF2.0_Logs/Flow2/report.json
Tata_Buyer_RSF2.0_Logs/Flow2/settle1.json
Tata_Buyer_RSF2.0_Logs/Flow2/settle2.json
Tata_Buyer_RSF2.0_Logs/Flow3/on_recon.json
Tata_Buyer_RSF2.0_Logs/Flow3/on_report.json
Tata_Buyer_RSF2.0_Logs/Flow3/on_settle.json
Tata_Buyer_RSF2.0_Logs/Flow3/recon.json
Tata_Buyer_RSF2.0_Logs/Flow3/report.json
Tata_Buyer_RSF2.0_Logs/Flow3/settle.json
Tata_Buyer_RSF2.0_Logs/Flow4/on_settle.json
Tata_Buyer_RSF2.0_Logs/Flow4/settle.json
Tata_Buyer_RSF2.0_Logs/Flow5/on_settle.json
Tata_Buyer_RSF2.0_Logs/Flow5/settle.json

Adding RSF2.0 logs Tata Buyer

---

Fynd/SellerApp/RET15/on_search(full_catalog).json
Fynd/SellerApp/RET15/on_search(inc).json
Fynd/SellerApp/RET15/search(full_catalog).json
Fynd/SellerApp/RET15/search(inc).json
Fynd/SellerApp/RET15/validation_utility_payload.json
Fynd/SellerApp/RET15/validation_utility_response.json

Fynd SA RET15 logs

---

airpay/buyer_app/Flow3_29_04_2025/issue1.json
airpay/buyer_app/Flow3_29_04_2025/issue2.json
airpay/buyer_app/Flow3_29_04_2025/issue3.json
airpay/buyer_app/Flow3_29_04_2025/issue4.json
airpay/buyer_app/Flow3_29_04_2025/on_issue1.json
airpay/buyer_app/Flow3_29_04_2025/on_issue2.json
airpay/buyer_app/Flow3_29_04_2025/on_issue3.json
airpay/buyer_app/Flow3_29_04_2025/on_issue4.json
airpay/buyer_app/Flow3_29_04_2025/on_issue5.json
airpay/buyer_app/Flow3_29_04_2025/validation_utility_report.json

Submitting buyerapp igm flow3 to ondc

Submitting buyerapp igm flow3 to ondc

---

only-usable/ret13/flow2/01. search_full_catalog_refresh.json
only-usable/ret13/flow2/02. on_search_full_catalog_refresh.json
only-usable/ret13/flow2/03. select.json
only-usable/ret13/flow2/04. on_select.json
only-usable/ret13/flow2/05. init.json
only-usable/ret13/flow2/06. on_init.json
only-usable/ret13/flow2/07. confirm.json
only-usable/ret13/flow2/08. on_confirm.json
only-usable/ret13/flow2/09. on_status_pending.json
only-usable/ret13/flow2/10. on_status_packed.json
only-usable/ret13/flow2/11. on_status_picked.json
only-usable/ret13/flow2/12. on_status_out_for_delivery.json
only-usable/ret13/flow2/13. on_status_delivered.json
only-usable/ret13/flow2/log-validation-report/validation-report.json

Hey Team,
I am Ayush from Only Usable , we are already live for RET10 and RET11 and now we are expanding for RET13 , we had a talk with one of your team member and we were told to upload one flow to the github as we are already live for the other 2 domains , let me know if any other changes are required for the verification of this flow , we have completed the flow using the pramaan testflow server.
Some changes were requested by @sandeepshahi , which are here resolved from previous PR , please let me know if any other change is required.

Techlog for RET13 Domain

---

shopalyst/phase-1/IGM/flow-1/1-issue_created.json
shopalyst/phase-1/IGM/flow-1/10-on_issue_resolved.json
shopalyst/phase-1/IGM/flow-1/11-issue_closed.json
shopalyst/phase-1/IGM/flow-1/2-on_issue_processing.json
shopalyst/phase-1/IGM/flow-1/3-on_issue_need_more_info.json
shopalyst/phase-1/IGM/flow-1/4-issue_info_provided.json
shopalyst/phase-1/IGM/flow-1/5-on_issue_processing_2.json
shopalyst/phase-1/IGM/flow-1/6-issue_status.json
shopalyst/phase-1/IGM/flow-1/7-on_issue_status.json
shopalyst/phase-1/IGM/flow-1/8-on_issue_resolution_proposed.json
shopalyst/phase-1/IGM/flow-1/9-issue_resolution_accepted.json
shopalyst/phase-1/IGM/flow-1/utility_report/validate_api_curl.txt
shopalyst/phase-1/IGM/flow-1/utility_report/validate_api_response.json

Context updated
[Issue thread Link](https://github.com/ONDC-Official/v1.2.0-logs/issues/3373#issuecomment-2877311934)

Shopalyst IGM 2.0.0 (BPP)

---

Aurikatech/Seller App/ONDC RET 10/CORE-APIS/FLOW 1/on_search.json
Aurikatech/Seller App/ONDC RET 10/CORE-APIS/FLOW 1/on_search_incr.json
Aurikatech/Seller App/ONDC RET 10/CORE-APIS/FLOW 1/search.json
Aurikatech/Seller App/ONDC RET 10/CORE-APIS/FLOW 1/search_incr.json
Aurikatech/Seller App/ONDC RET 10/CORE-APIS/FLOW 1/utiltiy_response.json

- fixed all issues from utility

Aurikatech Grocery Flow 1 logs for Seller App

---

Zeitgeist_Retail-Buyer_App/RSF/Flow 1/1_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 1/2_on_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 1/3_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 1/4_on_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 1/log_validation_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 2/1_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 2/2_on_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 2/3_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 2/4_on_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 2/5_recon.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 2/6_on_recon.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 2/log_validation_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 3/1_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 3/2_on_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 3/3_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 3/4_on_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 3/5_recon.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 3/6_on_recon.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 3/log_validation_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 4/1_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 4/2_on_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 4/log_validation_report.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 5/1_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 5/2_on_settle.json
Zeitgeist_Retail-Buyer_App/RSF/Flow 5/log_validation_report.json

Kindly review and merge the RSF 2.0 logs of our Buyer App

RSF 2.0 LOGS FLOW 1-5

---

Aekiva/IGM 2.0/Flow 1/issue_closed.json
Aekiva/IGM 2.0/Flow 1/issue_info_provided.json
Aekiva/IGM 2.0/Flow 1/issue_open.json
Aekiva/IGM 2.0/Flow 1/issue_resolution_accepted.json
Aekiva/IGM 2.0/Flow 1/log_validation_response.json
Aekiva/IGM 2.0/Flow 1/on_issue_info_required.json
Aekiva/IGM 2.0/Flow 1/on_issue_processing_1.json
Aekiva/IGM 2.0/Flow 1/on_issue_processing_2.json
Aekiva/IGM 2.0/Flow 1/on_issue_resolution_proposed.json
Aekiva/IGM 2.0/Flow 1/on_issue_resolved.json
Aekiva/IGM 2.0/Flow 2/issue_close.json
Aekiva/IGM 2.0/Flow 2/issue_esclated.json
Aekiva/IGM 2.0/Flow 2/issue_open.json
Aekiva/IGM 2.0/Flow 2/issue_resolution_accepted.json
Aekiva/IGM 2.0/Flow 2/log_validation_response.json
Aekiva/IGM 2.0/Flow 2/on_issue_processing_1.json
Aekiva/IGM 2.0/Flow 2/on_issue_processing_2.json
Aekiva/IGM 2.0/Flow 2/on_issue_resolution_proposed_1.json
Aekiva/IGM 2.0/Flow 2/on_issue_resolution_proposed_2.json
Aekiva/IGM 2.0/Flow 2/on_issue_resolved.json

Added logs for IGM 2.0 for Aekiva business solutions. Kindly review it.

Aekiva logs for IGM 2.0

---

ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/1. issue_open.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/2. on_issue_processing_1.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/3. on_issue_info_required.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/4. issue_info_provided.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/5. on_issue_processing_2.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/6. on_issue_resolution_proposed.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/7. issue_resolution_accepted.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/8. on_issue_resolved.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/9. issue_closed.json
ToneTag/IGM-2.0-Logs-BuyerApp/FLOW-1/response.json

IGM 2.0 Logs has been submitted for revision for RET:11 buyer app from ToneTag

IGM 2.0 logs submission for buyer RET:11

---

Digiit/Retail/RET15/log_validation_utility.json
Digiit/Retail/RET15/on_search_full_catalog_refresh.json
Digiit/Retail/RET15/on_search_inc_refresh.json
Digiit/Retail/RET15/search_full_catalog_refresh.json
Digiit/Retail/RET15/search_inc_refresh.json

@sandeepshahi  @Jagannath-wits kindly review the RET15 logs

Digiit RET15 Logs

---

shopclues/seller-logs/RET13/FLOW-1/full_search_on_search.json
shopclues/seller-logs/RET13/FLOW-1/increment_search_on_search.json

review and approve  for ret 13

RET-13 search on search logs
